
%--------------------------------------------------------------------------
% File     : 
% Domain   : Petri-nets
% Problem  : BridgeAndVehicles 
% Version  : 1.0
% Refs     : The Model Checking Contest
% Source   : https://pnrepository.lip6.fr/mcc/models/all/browser.html
%
% Status (linear) : Theorem
% Rating (linear) : 0.00 v1.0.0
%--------------------------------------------------------------------------
fof(inital_state, axiom, ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * NB_ATTENTE_A_0 * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * NB_ATTENTE_B_0 * CHOIX_1 * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * COMPTEUR_0).
fof(timeout_B_2_1_5_0, axiom, !( (NB_ATTENTE_A_5 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_5 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_0_6_0, axiom, !( (NB_ATTENTE_A_6 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_6 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_3_0_9, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_9 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_9 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_0_0_5, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_5 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_5 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_B_2_3, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_3 * ATTENTE_B) -o (NB_ATTENTE_B_2 * CHOIX_2 * SUR_PONT_B) ) ).
fof(timeout_A_1_0_0_10, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_10 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_10 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_8_8_0, axiom, !( (NB_ATTENTE_A_8 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_8 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_4_0_2, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_2 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_2 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_5_0_5, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_5 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_5 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(decision_2_7, axiom, !( (CHOIX_2 * COMPTEUR_7) -o (CONTROLEUR_2 * COMPTEUR_8) ) ).
fof(timeout_B_2_6_9_0, axiom, !( (NB_ATTENTE_A_9 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_9 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_5_4_0, axiom, !( (NB_ATTENTE_A_4 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_4 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_4_0_6, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_6 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_6 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_5_10_0, axiom, !( (NB_ATTENTE_A_10 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_10 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_4_0_4, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_4 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_4 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_1_0_4, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_4 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_4 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_A_1_8, axiom, !( (NB_ATTENTE_A_8 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_7 * SUR_PONT_A * CHOIX_1) ) ).
fof(timeout_A_1_0_0_3, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_3 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_3 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(decision_2_3, axiom, !( (CHOIX_2 * COMPTEUR_3) -o (CONTROLEUR_2 * COMPTEUR_4) ) ).
fof(timeout_A_1_1_0_2, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_2 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_2 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_0_7_0, axiom, !( (NB_ATTENTE_A_7 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_7 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_3_0_4, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_4 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_4 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_3_8_0, axiom, !( (NB_ATTENTE_A_8 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_8 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_A_7, axiom, !( (ROUTE_A * NB_ATTENTE_A_7) -o (NB_ATTENTE_A_8 * ATTENTE_A) ) ).
fof(timeout_A_1_6_0_2, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_2 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_2 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_A_1_9, axiom, !( (NB_ATTENTE_A_9 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_8 * SUR_PONT_A * CHOIX_1) ) ).
fof(decision_1_3, axiom, !( (CHOIX_1 * COMPTEUR_3) -o (CONTROLEUR_1 * COMPTEUR_4) ) ).
fof(timeout_B_2_1_2_0, axiom, !( (NB_ATTENTE_A_2 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_2 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(autorisation_A_1_3, axiom, !( (NB_ATTENTE_A_3 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_2 * SUR_PONT_A * CHOIX_1) ) ).
fof(timeout_B_2_7_10_0, axiom, !( (NB_ATTENTE_A_10 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_10 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_0_5_0, axiom, !( (NB_ATTENTE_A_5 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_5 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(altern_cpt_1_10, axiom, !( (CHOIX_1 * COMPTEUR_10) -o (VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_5_0_8, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_8 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_8 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(enregistrement_A_2, axiom, !( (ROUTE_A * NB_ATTENTE_A_2) -o (NB_ATTENTE_A_3 * ATTENTE_A) ) ).
fof(autorisation_A_1_6, axiom, !( (NB_ATTENTE_A_6 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_5 * SUR_PONT_A * CHOIX_1) ) ).
fof(timeout_A_1_4_0_5, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_5 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_5 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_2_9_0, axiom, !( (NB_ATTENTE_A_9 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_9 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_3_5_0, axiom, !( (NB_ATTENTE_A_5 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_5 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_2_0_9, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_9 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_9 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_1_0_9, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_9 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_9 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(decision_2_0, axiom, !( (CHOIX_2 * COMPTEUR_0) -o (CONTROLEUR_2 * COMPTEUR_1) ) ).
fof(timeout_A_1_5_0_3, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_3 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_3 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_9_0_4, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_4 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_4 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_1_0_6, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_6 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_6 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_4_9_0, axiom, !( (NB_ATTENTE_A_9 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_9 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_2_1_0, axiom, !( (NB_ATTENTE_A_1 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_1 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_1_6_0, axiom, !( (NB_ATTENTE_A_6 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_6 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_5_6_0, axiom, !( (NB_ATTENTE_A_6 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_6 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_3_6_0, axiom, !( (NB_ATTENTE_A_6 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_6 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_3_2_0, axiom, !( (NB_ATTENTE_A_2 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_2 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_8_10_0, axiom, !( (NB_ATTENTE_A_10 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_10 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(decision_2_4, axiom, !( (CHOIX_2 * COMPTEUR_4) -o (CONTROLEUR_2 * COMPTEUR_5) ) ).
fof(timeout_B_2_8_3_0, axiom, !( (NB_ATTENTE_A_3 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_3 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_10_0_7, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_7 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_7 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_10_0_8, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_8 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_8 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_B_2_2, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_2 * ATTENTE_B) -o (NB_ATTENTE_B_1 * CHOIX_2 * SUR_PONT_B) ) ).
fof(timeout_B_2_10_5_0, axiom, !( (NB_ATTENTE_A_5 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_5 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(autorisation_A_1_7, axiom, !( (NB_ATTENTE_A_7 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_6 * SUR_PONT_A * CHOIX_1) ) ).
fof(timeout_B_2_1_10_0, axiom, !( (NB_ATTENTE_A_10 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_10 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_2_3_0, axiom, !( (NB_ATTENTE_A_3 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_3 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(decision_1_8, axiom, !( (CHOIX_1 * COMPTEUR_8) -o (CONTROLEUR_1 * COMPTEUR_9) ) ).
fof(altern_cpt_2_10, axiom, !( (CHOIX_2 * COMPTEUR_10) -o (VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_B_1, axiom, !( (NB_ATTENTE_B_1 * ROUTE_B) -o (NB_ATTENTE_B_2 * ATTENTE_B) ) ).
fof(timeout_B_2_2_8_0, axiom, !( (NB_ATTENTE_A_8 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_8 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_8_0_4, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_4 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_4 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_7_7_0, axiom, !( (NB_ATTENTE_A_7 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_7 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(decision_1_6, axiom, !( (CHOIX_1 * COMPTEUR_6) -o (CONTROLEUR_1 * COMPTEUR_7) ) ).
fof(timeout_B_2_0_10_0, axiom, !( (NB_ATTENTE_A_10 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_10 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_6_0_10, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_10 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_10 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_6_0_7, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_7 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_7 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_4_1_0, axiom, !( (NB_ATTENTE_A_1 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_1 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_0_0_9, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_9 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_9 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_8_5_0, axiom, !( (NB_ATTENTE_A_5 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_5 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_6_10_0, axiom, !( (NB_ATTENTE_A_10 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_10 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_9_5_0, axiom, !( (NB_ATTENTE_A_5 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_5 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_9_0_6, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_6 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_6 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_9_6_0, axiom, !( (NB_ATTENTE_A_6 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_6 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_8_0_7, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_7 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_7 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_2_0_8, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_8 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_8 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(decision_1_1, axiom, !( (CHOIX_1 * COMPTEUR_1) -o (CONTROLEUR_1 * COMPTEUR_2) ) ).
fof(timeout_A_1_2_0_10, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_10 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_10 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_10_9_0, axiom, !( (NB_ATTENTE_A_9 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_9 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_5_5_0, axiom, !( (NB_ATTENTE_A_5 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_5 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_10_2_0, axiom, !( (NB_ATTENTE_A_2 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_2 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_7_0_5, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_5 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_5 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_0_2_0, axiom, !( (NB_ATTENTE_A_2 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_2 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_7_0_4, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_4 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_4 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_10_0_4, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_4 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_4 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_8_0_5, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_5 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_5 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_9_9_0, axiom, !( (NB_ATTENTE_A_9 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_9 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_3_9_0, axiom, !( (NB_ATTENTE_A_9 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_9 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(autorisation_B_2_1, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_1 * ATTENTE_B) -o (NB_ATTENTE_B_0 * CHOIX_2 * SUR_PONT_B) ) ).
fof(timeout_A_1_0_0_2, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_2 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_2 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_3_0_1, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_1 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_1 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_4_4_0, axiom, !( (NB_ATTENTE_A_4 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_4 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_4_0_1, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_1 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_1 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_3_0_5, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_5 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_5 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_1_7_0, axiom, !( (NB_ATTENTE_A_7 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_7 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_5_0_7, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_7 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_7 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_0_0_6, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_6 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_6 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_2_0_6, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_6 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_6 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_10_1_0, axiom, !( (NB_ATTENTE_A_1 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_1 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_0_1_0, axiom, !( (NB_ATTENTE_A_1 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_1 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(autorisation_A_1_4, axiom, !( (NB_ATTENTE_A_4 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_3 * SUR_PONT_A * CHOIX_1) ) ).
fof(timeout_A_1_2_0_3, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_3 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_3 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_9_0_1, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_1 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_1 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_5_1_0, axiom, !( (NB_ATTENTE_A_1 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_1 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(liberation_B, axiom, !( (SUR_PONT_B) -o (CAPACITE * SORTI_B) ) ).
fof(timeout_B_2_6_4_0, axiom, !( (NB_ATTENTE_A_4 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_4 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_10_8_0, axiom, !( (NB_ATTENTE_A_8 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_8 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_7_2_0, axiom, !( (NB_ATTENTE_A_2 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_2 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_8_0_6, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_6 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_6 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(liberation_A, axiom, !( (SUR_PONT_A) -o (SORTI_A * CAPACITE) ) ).
fof(timeout_A_1_1_0_7, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_7 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_7 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_10_7_0, axiom, !( (NB_ATTENTE_A_7 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_7 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_1_4_0, axiom, !( (NB_ATTENTE_A_4 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_4 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_A_1, axiom, !( (ROUTE_A * NB_ATTENTE_A_1) -o (NB_ATTENTE_A_2 * ATTENTE_A) ) ).
fof(timeout_B_2_3_3_0, axiom, !( (NB_ATTENTE_A_3 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_3 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_6_1_0, axiom, !( (NB_ATTENTE_A_1 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_1 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_5_8_0, axiom, !( (NB_ATTENTE_A_8 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_8 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_A_5, axiom, !( (ROUTE_A * NB_ATTENTE_A_5) -o (NB_ATTENTE_A_6 * ATTENTE_A) ) ).
fof(decision_1_9, axiom, !( (CHOIX_1 * COMPTEUR_9) -o (CONTROLEUR_1 * COMPTEUR_10) ) ).
fof(timeout_B_2_7_6_0, axiom, !( (NB_ATTENTE_A_6 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_6 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_6_0_5, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_5 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_5 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_1_0_3, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_3 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_3 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_3_4_0, axiom, !( (NB_ATTENTE_A_4 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_4 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_7_0_3, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_3 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_3 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_0_4_0, axiom, !( (NB_ATTENTE_A_4 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_4 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_1_3_0, axiom, !( (NB_ATTENTE_A_3 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_3 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_2_2_0, axiom, !( (NB_ATTENTE_A_2 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_2 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_1_0_5, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_5 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_5 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_2_0_7, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_7 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_7 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_4_0_9, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_9 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_9 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_7_1_0, axiom, !( (NB_ATTENTE_A_1 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_1 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_5_0_1, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_1 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_1 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_3_0_2, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_2 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_2 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_5_9_0, axiom, !( (NB_ATTENTE_A_9 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_9 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_3_0_6, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_6 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_6 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_A_1_10, axiom, !( (NB_ATTENTE_A_10 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_9 * SUR_PONT_A * CHOIX_1) ) ).
fof(timeout_A_1_8_0_9, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_9 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_9 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(enregistrement_B_8, axiom, !( (NB_ATTENTE_B_8 * ROUTE_B) -o (NB_ATTENTE_B_9 * ATTENTE_B) ) ).
fof(timeout_B_2_6_3_0, axiom, !( (NB_ATTENTE_A_3 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_3 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_2_0_2, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_2 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_2 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_8_4_0, axiom, !( (NB_ATTENTE_A_4 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_4 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_7_0_6, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_6 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_6 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(decision_1_2, axiom, !( (CHOIX_1 * COMPTEUR_2) -o (CONTROLEUR_1 * COMPTEUR_3) ) ).
fof(timeout_A_1_1_0_8, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_8 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_8 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_8_0_8, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_8 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_8 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(decision_2_5, axiom, !( (CHOIX_2 * COMPTEUR_5) -o (CONTROLEUR_2 * COMPTEUR_6) ) ).
fof(decision_2_9, axiom, !( (CHOIX_2 * COMPTEUR_9) -o (CONTROLEUR_2 * COMPTEUR_10) ) ).
fof(timeout_A_1_10_0_1, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_1 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_1 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_9_2_0, axiom, !( (NB_ATTENTE_A_2 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_2 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_5_0_10, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_10 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_10 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_8_0_3, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_3 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_3 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_6_0_6, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_6 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_6 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_1_8_0, axiom, !( (NB_ATTENTE_A_8 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_8 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(decision_2_1, axiom, !( (CHOIX_2 * COMPTEUR_1) -o (CONTROLEUR_2 * COMPTEUR_2) ) ).
fof(timeout_B_2_10_3_0, axiom, !( (NB_ATTENTE_A_3 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_3 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_1_9_0, axiom, !( (NB_ATTENTE_A_9 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_9 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(decision_2_6, axiom, !( (CHOIX_2 * COMPTEUR_6) -o (CONTROLEUR_2 * COMPTEUR_7) ) ).
fof(timeout_B_2_7_4_0, axiom, !( (NB_ATTENTE_A_4 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_4 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_8_6_0, axiom, !( (NB_ATTENTE_A_6 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_6 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_0_0_7, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_7 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_7 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(enregistrement_B_7, axiom, !( (NB_ATTENTE_B_7 * ROUTE_B) -o (NB_ATTENTE_B_8 * ATTENTE_B) ) ).
fof(timeout_A_1_7_0_8, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_8 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_8 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_7_5_0, axiom, !( (NB_ATTENTE_A_5 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_5 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_5_0_4, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_4 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_4 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_5_0_6, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_6 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_6 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(decision_2_8, axiom, !( (CHOIX_2 * COMPTEUR_8) -o (CONTROLEUR_2 * COMPTEUR_9) ) ).
fof(timeout_A_1_8_0_2, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_2 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_2 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_0_0_4, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_4 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_4 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_4_5_0, axiom, !( (NB_ATTENTE_A_5 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_5 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_B_9, axiom, !( (NB_ATTENTE_B_9 * ROUTE_B) -o (NB_ATTENTE_B_10 * ATTENTE_B) ) ).
fof(timeout_A_1_10_0_10, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_10 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_10 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_6_0_4, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_4 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_4 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_6_0_8, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_8 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_8 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_A_1_5, axiom, !( (NB_ATTENTE_A_5 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_4 * SUR_PONT_A * CHOIX_1) ) ).
fof(timeout_B_2_0_8_0, axiom, !( (NB_ATTENTE_A_8 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_8 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(autorisation_A_1_1, axiom, !( (NB_ATTENTE_A_1 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_0 * SUR_PONT_A * CHOIX_1) ) ).
fof(timeout_B_2_1_1_0, axiom, !( (NB_ATTENTE_A_1 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_1 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_3_0_10, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_10 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_10 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(enregistrement_B_10, axiom, !( (NB_ATTENTE_B_10 * ROUTE_B) -o (NB_ATTENTE_B_0 * ATTENTE_B) ) ).
fof(timeout_B_2_7_9_0, axiom, !( (NB_ATTENTE_A_9 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_9 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_5_3_0, axiom, !( (NB_ATTENTE_A_3 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_3 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_9_0_9, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_9 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_9 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_8_1_0, axiom, !( (NB_ATTENTE_A_1 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_1 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_2_5_0, axiom, !( (NB_ATTENTE_A_5 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_5 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_8_0_10, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_10 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_10 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_4_8_0, axiom, !( (NB_ATTENTE_A_8 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_8 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_7_3_0, axiom, !( (NB_ATTENTE_A_3 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_3 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_9_3_0, axiom, !( (NB_ATTENTE_A_3 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_3 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_8_0_1, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_1 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_1 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_9_0_2, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_2 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_2 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_9_7_0, axiom, !( (NB_ATTENTE_A_7 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_7 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_2_0_4, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_4 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_4 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_B_2_9, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_9 * ATTENTE_B) -o (NB_ATTENTE_B_8 * CHOIX_2 * SUR_PONT_B) ) ).
fof(timeout_B_2_9_1_0, axiom, !( (NB_ATTENTE_A_1 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_1 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(autorisation_B_2_4, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_4 * ATTENTE_B) -o (NB_ATTENTE_B_3 * CHOIX_2 * SUR_PONT_B) ) ).
fof(timeout_B_2_4_7_0, axiom, !( (NB_ATTENTE_A_7 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_7 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_3_0_8, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_8 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_8 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_4_10_0, axiom, !( (NB_ATTENTE_A_10 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_10 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_9_8_0, axiom, !( (NB_ATTENTE_A_8 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_8 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_0_0_8, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_8 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_8 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_9_10_0, axiom, !( (NB_ATTENTE_A_10 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_10 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_6_8_0, axiom, !( (NB_ATTENTE_A_8 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_8 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_6_0_1, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_1 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_1 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_1_0_10, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_10 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_10 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_7_0_7, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_7 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_7 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(enregistrement_B_5, axiom, !( (NB_ATTENTE_B_5 * ROUTE_B) -o (NB_ATTENTE_B_6 * ATTENTE_B) ) ).
fof(timeout_A_1_3_0_7, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_7 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_7 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_B_2_5, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_5 * ATTENTE_B) -o (NB_ATTENTE_B_4 * CHOIX_2 * SUR_PONT_B) ) ).
fof(timeout_B_2_10_6_0, axiom, !( (NB_ATTENTE_A_6 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_6 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_5_0_2, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_2 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_2 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_4_2_0, axiom, !( (NB_ATTENTE_A_2 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_2 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_B_0, axiom, !( (NB_ATTENTE_B_0 * ROUTE_B) -o (NB_ATTENTE_B_1 * ATTENTE_B) ) ).
fof(decision_1_0, axiom, !( (CHOIX_1 * COMPTEUR_0) -o (CONTROLEUR_1 * COMPTEUR_1) ) ).
fof(timeout_B_2_6_2_0, axiom, !( (NB_ATTENTE_A_2 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_2 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_2_10_0, axiom, !( (NB_ATTENTE_A_10 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_10 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(decision_1_7, axiom, !( (CHOIX_1 * COMPTEUR_7) -o (CONTROLEUR_1 * COMPTEUR_8) ) ).
fof(timeout_A_1_9_0_3, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_3 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_3 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_A_1_2, axiom, !( (NB_ATTENTE_A_2 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_1 * SUR_PONT_A * CHOIX_1) ) ).
fof(enregistrement_A_8, axiom, !( (ROUTE_A * NB_ATTENTE_A_8) -o (NB_ATTENTE_A_9 * ATTENTE_A) ) ).
fof(timeout_A_1_4_0_3, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_3 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_3 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(basculement_1, axiom, !( (CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * VIDANGE_1) -o (CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CHOIX_1) ) ).
fof(timeout_A_1_4_0_8, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_8 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_8 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_B_2_8, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_8 * ATTENTE_B) -o (NB_ATTENTE_B_7 * CHOIX_2 * SUR_PONT_B) ) ).
fof(enregistrement_B_3, axiom, !( (NB_ATTENTE_B_3 * ROUTE_B) -o (NB_ATTENTE_B_4 * ATTENTE_B) ) ).
fof(timeout_B_2_6_7_0, axiom, !( (NB_ATTENTE_A_7 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_7 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_A_6, axiom, !( (ROUTE_A * NB_ATTENTE_A_6) -o (NB_ATTENTE_A_7 * ATTENTE_A) ) ).
fof(timeout_B_2_7_8_0, axiom, !( (NB_ATTENTE_A_8 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_8 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_6_5_0, axiom, !( (NB_ATTENTE_A_5 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_5 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_7_0_10, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_10 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_10 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_7_0_2, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_2 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_2 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_7_0_9, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_9 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_9 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_8_2_0, axiom, !( (NB_ATTENTE_A_2 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_2 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_A_0, axiom, !( (ROUTE_A * NB_ATTENTE_A_0) -o (NB_ATTENTE_A_1 * ATTENTE_A) ) ).
fof(timeout_B_2_4_3_0, axiom, !( (NB_ATTENTE_A_3 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_3 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(autorisation_B_2_10, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_10 * ATTENTE_B) -o (NB_ATTENTE_B_9 * CHOIX_2 * SUR_PONT_B) ) ).
fof(autorisation_B_2_6, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_6 * ATTENTE_B) -o (NB_ATTENTE_B_5 * CHOIX_2 * SUR_PONT_B) ) ).
fof(timeout_B_2_0_3_0, axiom, !( (NB_ATTENTE_A_3 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_3 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_6_0_9, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_9 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_9 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_4_6_0, axiom, !( (NB_ATTENTE_A_6 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_6 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(decision_1_5, axiom, !( (CHOIX_1 * COMPTEUR_5) -o (CONTROLEUR_1 * COMPTEUR_6) ) ).
fof(timeout_A_1_10_0_2, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_2 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_2 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_B_2_7, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_7 * ATTENTE_B) -o (NB_ATTENTE_B_6 * CHOIX_2 * SUR_PONT_B) ) ).
fof(timeout_A_1_4_0_10, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_10 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_10 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_0_9_0, axiom, !( (NB_ATTENTE_A_9 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_9 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_3_10_0, axiom, !( (NB_ATTENTE_A_10 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_10 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_5_2_0, axiom, !( (NB_ATTENTE_A_2 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_2 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_B_6, axiom, !( (NB_ATTENTE_B_6 * ROUTE_B) -o (NB_ATTENTE_B_7 * ATTENTE_B) ) ).
fof(timeout_A_1_7_0_1, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_1 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_1 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(basculement_2, axiom, !( (CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * VIDANGE_2) -o (CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CHOIX_2) ) ).
fof(timeout_A_1_1_0_1, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_1 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_1 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_9_0_5, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_5 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_5 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_10_4_0, axiom, !( (NB_ATTENTE_A_4 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_4 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_10_0_3, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_3 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_3 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(enregistrement_A_10, axiom, !( (ROUTE_A * NB_ATTENTE_A_10) -o (NB_ATTENTE_A_0 * ATTENTE_A) ) ).
fof(timeout_B_2_6_6_0, axiom, !( (NB_ATTENTE_A_6 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_6 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_10_0_6, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_6 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_6 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_10_0_5, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_5 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_5 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_4_0_7, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_7 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_7 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_9_0_8, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_8 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_8 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_10_10_0, axiom, !( (NB_ATTENTE_A_10 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_10 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_B_4, axiom, !( (NB_ATTENTE_B_4 * ROUTE_B) -o (NB_ATTENTE_B_5 * ATTENTE_B) ) ).
fof(enregistrement_A_9, axiom, !( (ROUTE_A * NB_ATTENTE_A_9) -o (NB_ATTENTE_A_10 * ATTENTE_A) ) ).
fof(decision_1_4, axiom, !( (CHOIX_1 * COMPTEUR_4) -o (CONTROLEUR_1 * COMPTEUR_5) ) ).
fof(timeout_A_1_5_0_9, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_9 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_9 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_10_0_9, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_9 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_9 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(enregistrement_A_3, axiom, !( (ROUTE_A * NB_ATTENTE_A_3) -o (NB_ATTENTE_A_4 * ATTENTE_A) ) ).
fof(timeout_A_1_6_0_3, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_3 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_3 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_1_2_0_1, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_1 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_1 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_9_4_0, axiom, !( (NB_ATTENTE_A_4 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_4 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_A_4, axiom, !( (ROUTE_A * NB_ATTENTE_A_4) -o (NB_ATTENTE_A_5 * ATTENTE_A) ) ).
fof(timeout_B_2_8_7_0, axiom, !( (NB_ATTENTE_A_7 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_7 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_2_0_5, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_5 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_5 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(decision_2_2, axiom, !( (CHOIX_2 * COMPTEUR_2) -o (CONTROLEUR_2 * COMPTEUR_3) ) ).
fof(timeout_A_1_9_0_7, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_7 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_7 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_3_7_0, axiom, !( (NB_ATTENTE_A_7 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_7 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_3_1_0, axiom, !( (NB_ATTENTE_A_1 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_1 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_2_4_0, axiom, !( (NB_ATTENTE_A_4 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_4 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_0_0_1, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_1 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_1 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_2_6_0, axiom, !( (NB_ATTENTE_A_6 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_6 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_8_9_0, axiom, !( (NB_ATTENTE_A_9 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_9 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_9_0_10, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_10 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_10 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(enregistrement_B_2, axiom, !( (NB_ATTENTE_B_2 * ROUTE_B) -o (NB_ATTENTE_B_3 * ATTENTE_B) ) ).
fof(timeout_B_2_2_7_0, axiom, !( (NB_ATTENTE_A_7 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_7 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_1_3_0_3, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_3 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_3 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_5_7_0, axiom, !( (NB_ATTENTE_A_7 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_7 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(con1, conjecture, CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CHOIX_2 * COMPTEUR_1 * NB_ATTENTE_A_0 * NB_ATTENTE_B_0 * SORTI_A * SORTI_A * SORTI_A * SORTI_A * SORTI_A * SORTI_A * SORTI_A * SORTI_A * SORTI_A * SORTI_A * SORTI_B * SORTI_B * SORTI_B * SORTI_B * SORTI_B * SORTI_B * SORTI_B * SORTI_B * SORTI_B * SUR_PONT_B).

%--------------------------------------------------------------------------
