
%--------------------------------------------------------------------------
% File     : 
% Domain   : Petri-nets
% Problem  : BridgeAndVehicles 
% Version  : 1.0
% Refs     : The Model Checking Contest
% Source   : https://pnrepository.lip6.fr/mcc/models/all/browser.html
%
% Status (linear) : Theorem
% Rating (linear) : 0.00 v1.0.0
%--------------------------------------------------------------------------
fof(inital_state, axiom, ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * NB_ATTENTE_A_0 * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * NB_ATTENTE_B_0 * CHOIX_1 * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * COMPTEUR_0).
fof(autorisation_B_2_20, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_20 * ATTENTE_B) -o (NB_ATTENTE_B_19 * CHOIX_2 * SUR_PONT_B) ) ).
fof(timeout_A_0_3_1_4, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_4 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_4 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_18_10_2_0, axiom, !( (NB_ATTENTE_A_18 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_18 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_3_3_2_0, axiom, !( (NB_ATTENTE_A_3 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_3 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(decision_7_2, axiom, !( (CHOIX_2 * COMPTEUR_7) -o (CONTROLEUR_2 * COMPTEUR_8) ) ).
fof(timeout_B_16_0_2_0, axiom, !( (NB_ATTENTE_A_16 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_16 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_12_4_2_0, axiom, !( (NB_ATTENTE_A_12 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_12 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_10_7_2_0, axiom, !( (NB_ATTENTE_A_10 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_10 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_6_1_14, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_14 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_14 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_2_1_5, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_5 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_5 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_6_3_2_0, axiom, !( (NB_ATTENTE_A_6 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_6 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_18_3_2_0, axiom, !( (NB_ATTENTE_A_18 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_18 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_6_2_0, axiom, !( (NB_ATTENTE_A_2 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_2 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_7_1_11, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_11 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_11 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_4_7_2_0, axiom, !( (NB_ATTENTE_A_4 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_4 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_1_1_2, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_2 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_2 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_10_1_3, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_3 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_3 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_A_15_1, axiom, !( (NB_ATTENTE_A_15 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_14 * SUR_PONT_A * CHOIX_1) ) ).
fof(timeout_B_6_0_2_0, axiom, !( (NB_ATTENTE_A_6 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_6 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_4_9_2_0, axiom, !( (NB_ATTENTE_A_4 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_4 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_6_9_2_0, axiom, !( (NB_ATTENTE_A_6 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_6 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_2_1_7, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_7 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_7 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_8_1_7, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_7 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_7 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_3_1_15, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_15 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_15 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_3_1_10, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_10 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_10 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_13_6_2_0, axiom, !( (NB_ATTENTE_A_13 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_13 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_14_6_2_0, axiom, !( (NB_ATTENTE_A_14 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_14 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_13_2_2_0, axiom, !( (NB_ATTENTE_A_13 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_13 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_2_1_19, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_19 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_19 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(decision_0_1, axiom, !( (CHOIX_1 * COMPTEUR_0) -o (CONTROLEUR_1 * COMPTEUR_1) ) ).
fof(decision_8_2, axiom, !( (CHOIX_2 * COMPTEUR_8) -o (CONTROLEUR_2 * COMPTEUR_9) ) ).
fof(timeout_A_0_6_1_6, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_6 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_6 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_8_1_10, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_10 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_10 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_20_10_2_0, axiom, !( (NB_ATTENTE_A_20 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_20 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_6_1_19, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_19 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_19 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_3_10_2_0, axiom, !( (NB_ATTENTE_A_3 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_3 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_6_1_2, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_2 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_2 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_19_10_2_0, axiom, !( (NB_ATTENTE_A_19 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_19 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_9_1_5, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_5 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_5 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_10_1_7, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_7 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_7 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_2_1_6, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_6 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_6 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_20_6_2_0, axiom, !( (NB_ATTENTE_A_20 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_20 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_14_7_2_0, axiom, !( (NB_ATTENTE_A_14 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_14 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_B_17, axiom, !( (NB_ATTENTE_B_17 * ROUTE_B) -o (NB_ATTENTE_B_18 * ATTENTE_B) ) ).
fof(timeout_A_0_10_1_12, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_12 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_12 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_6_1_9, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_9 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_9 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_15_1_2_0, axiom, !( (NB_ATTENTE_A_15 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_15 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_18_1_2_0, axiom, !( (NB_ATTENTE_A_18 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_18 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_5_1_7, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_7 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_7 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_6_1_4, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_4 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_4 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_9_1_14, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_14 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_14 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_20_9_2_0, axiom, !( (NB_ATTENTE_A_20 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_20 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_6_1_1, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_1 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_1 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_1_1_10, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_10 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_10 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_3_1_5, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_5 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_5 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_6_6_2_0, axiom, !( (NB_ATTENTE_A_6 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_6 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_4_1_11, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_11 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_11 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_5_1_20, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_20 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_20 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_4_0_2_0, axiom, !( (NB_ATTENTE_A_4 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_4 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(autorisation_B_2_2, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_2 * ATTENTE_B) -o (NB_ATTENTE_B_1 * CHOIX_2 * SUR_PONT_B) ) ).
fof(timeout_A_0_3_1_16, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_16 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_16 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_7_1_8, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_8 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_8 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_9_6_2_0, axiom, !( (NB_ATTENTE_A_9 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_9 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_A_10, axiom, !( (ROUTE_A * NB_ATTENTE_A_10) -o (NB_ATTENTE_A_11 * ATTENTE_A) ) ).
fof(timeout_A_0_0_1_7, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_7 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_7 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_3_1_3, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_3 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_3 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_4_3_2_0, axiom, !( (NB_ATTENTE_A_4 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_4 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_16_2_2_0, axiom, !( (NB_ATTENTE_A_16 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_16 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_4_1_19, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_19 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_19 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_4_1_5, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_5 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_5 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_6_7_2_0, axiom, !( (NB_ATTENTE_A_6 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_6 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_8_1_5, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_5 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_5 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_1_1_4, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_4 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_4 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_5_1_10, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_10 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_10 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(decision_0_2, axiom, !( (CHOIX_2 * COMPTEUR_0) -o (CONTROLEUR_2 * COMPTEUR_1) ) ).
fof(timeout_A_0_7_1_7, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_7 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_7 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_19_2_2_0, axiom, !( (NB_ATTENTE_A_19 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_19 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_1_1_16, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_16 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_16 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_4_1_15, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_15 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_15 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(decision_1_1, axiom, !( (CHOIX_1 * COMPTEUR_1) -o (CONTROLEUR_1 * COMPTEUR_2) ) ).
fof(timeout_A_0_2_1_16, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_16 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_16 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_6_2_2_0, axiom, !( (NB_ATTENTE_A_6 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_6 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_2_1_2, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_2 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_2 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_10_1_2, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_2 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_2 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_7_1_1, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_1 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_1 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_5_1_19, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_19 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_19 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_10_2_0, axiom, !( (NB_ATTENTE_A_2 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_2 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_8_1_9, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_9 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_9 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_8_1_17, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_17 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_17 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(enregistrement_B_14, axiom, !( (NB_ATTENTE_B_14 * ROUTE_B) -o (NB_ATTENTE_B_15 * ATTENTE_B) ) ).
fof(timeout_A_0_8_1_20, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_20 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_20 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_A_1_1, axiom, !( (NB_ATTENTE_A_1 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_0 * SUR_PONT_A * CHOIX_1) ) ).
fof(timeout_B_14_0_2_0, axiom, !( (NB_ATTENTE_A_14 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_14 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_4_1_6, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_6 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_6 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_A_16_1, axiom, !( (NB_ATTENTE_A_16 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_15 * SUR_PONT_A * CHOIX_1) ) ).
fof(timeout_A_0_8_1_13, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_13 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_13 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_7_10_2_0, axiom, !( (NB_ATTENTE_A_7 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_7 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(autorisation_B_2_19, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_19 * ATTENTE_B) -o (NB_ATTENTE_B_18 * CHOIX_2 * SUR_PONT_B) ) ).
fof(timeout_A_0_1_1_7, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_7 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_7 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_3_1_19, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_19 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_19 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_17_7_2_0, axiom, !( (NB_ATTENTE_A_17 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_17 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_0_1_2, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_2 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_2 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_4_1_13, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_13 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_13 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_11_9_2_0, axiom, !( (NB_ATTENTE_A_11 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_11 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_8_5_2_0, axiom, !( (NB_ATTENTE_A_8 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_8 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(decision_8_1, axiom, !( (CHOIX_1 * COMPTEUR_8) -o (CONTROLEUR_1 * COMPTEUR_9) ) ).
fof(timeout_B_10_3_2_0, axiom, !( (NB_ATTENTE_A_10 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_10 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_12_1_2_0, axiom, !( (NB_ATTENTE_A_12 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_12 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_5_8_2_0, axiom, !( (NB_ATTENTE_A_5 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_5 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(liberation_B, axiom, !( (SUR_PONT_B) -o (CAPACITE * SORTI_B) ) ).
fof(timeout_A_0_6_1_15, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_15 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_15 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_11_0_2_0, axiom, !( (NB_ATTENTE_A_11 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_11 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_7_1_10, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_10 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_10 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_8_1_3, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_3 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_3 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_10_1_5, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_5 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_5 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(liberation_A, axiom, !( (SUR_PONT_A) -o (SORTI_A * CAPACITE) ) ).
fof(timeout_B_20_8_2_0, axiom, !( (NB_ATTENTE_A_20 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_20 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_12_6_2_0, axiom, !( (NB_ATTENTE_A_12 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_12 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_15_4_2_0, axiom, !( (NB_ATTENTE_A_15 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_15 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_3_1_8, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_8 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_8 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(enregistrement_A_5, axiom, !( (ROUTE_A * NB_ATTENTE_A_5) -o (NB_ATTENTE_A_6 * ATTENTE_A) ) ).
fof(timeout_A_0_7_1_9, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_9 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_9 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_1_1_13, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_13 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_13 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(enregistrement_A_13, axiom, !( (ROUTE_A * NB_ATTENTE_A_13) -o (NB_ATTENTE_A_14 * ATTENTE_A) ) ).
fof(timeout_A_0_4_1_2, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_2 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_2 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(enregistrement_A_15, axiom, !( (ROUTE_A * NB_ATTENTE_A_15) -o (NB_ATTENTE_A_16 * ATTENTE_A) ) ).
fof(autorisation_B_2_6, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_6 * ATTENTE_B) -o (NB_ATTENTE_B_5 * CHOIX_2 * SUR_PONT_B) ) ).
fof(timeout_B_4_2_2_0, axiom, !( (NB_ATTENTE_A_4 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_4 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_B_12, axiom, !( (NB_ATTENTE_B_12 * ROUTE_B) -o (NB_ATTENTE_B_13 * ATTENTE_B) ) ).
fof(timeout_A_0_0_1_16, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_16 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_16 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_2_2_0, axiom, !( (NB_ATTENTE_A_2 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_2 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_18_0_2_0, axiom, !( (NB_ATTENTE_A_18 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_18 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_1_0_2_0, axiom, !( (NB_ATTENTE_A_1 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_1 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_3_6_2_0, axiom, !( (NB_ATTENTE_A_3 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_3 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_15_8_2_0, axiom, !( (NB_ATTENTE_A_15 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_15 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_B_8, axiom, !( (NB_ATTENTE_B_8 * ROUTE_B) -o (NB_ATTENTE_B_9 * ATTENTE_B) ) ).
fof(timeout_B_15_9_2_0, axiom, !( (NB_ATTENTE_A_15 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_15 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_0_1_10, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_10 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_10 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_11_7_2_0, axiom, !( (NB_ATTENTE_A_11 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_11 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_16_6_2_0, axiom, !( (NB_ATTENTE_A_16 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_16 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_16_5_2_0, axiom, !( (NB_ATTENTE_A_16 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_16 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_11_8_2_0, axiom, !( (NB_ATTENTE_A_11 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_11 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_13_4_2_0, axiom, !( (NB_ATTENTE_A_13 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_13 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_10_1_2_0, axiom, !( (NB_ATTENTE_A_10 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_10 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_20_7_2_0, axiom, !( (NB_ATTENTE_A_20 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_20 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_10_6_2_0, axiom, !( (NB_ATTENTE_A_10 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_10 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_1_1_3, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_3 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_3 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(enregistrement_B_7, axiom, !( (NB_ATTENTE_B_7 * ROUTE_B) -o (NB_ATTENTE_B_8 * ATTENTE_B) ) ).
fof(timeout_B_2_9_2_0, axiom, !( (NB_ATTENTE_A_2 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_2 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(decision_5_2, axiom, !( (CHOIX_2 * COMPTEUR_5) -o (CONTROLEUR_2 * COMPTEUR_6) ) ).
fof(timeout_A_0_0_1_18, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_18 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_18 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_3_1_17, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_17 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_17 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_4_1_4, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_4 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_4 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(enregistrement_B_20, axiom, !( (NB_ATTENTE_B_20 * ROUTE_B) -o (NB_ATTENTE_B_0 * ATTENTE_B) ) ).
fof(decision_5_1, axiom, !( (CHOIX_1 * COMPTEUR_5) -o (CONTROLEUR_1 * COMPTEUR_6) ) ).
fof(timeout_A_0_8_1_8, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_8 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_8 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_6_1_5, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_5 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_5 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_6_5_2_0, axiom, !( (NB_ATTENTE_A_6 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_6 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(autorisation_B_2_11, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_11 * ATTENTE_B) -o (NB_ATTENTE_B_10 * CHOIX_2 * SUR_PONT_B) ) ).
fof(enregistrement_A_18, axiom, !( (ROUTE_A * NB_ATTENTE_A_18) -o (NB_ATTENTE_A_19 * ATTENTE_A) ) ).
fof(timeout_A_0_5_1_6, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_6 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_6 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_1_7_2_0, axiom, !( (NB_ATTENTE_A_1 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_1 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_7_1_6, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_6 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_6 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_8_1_1, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_1 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_1 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_20_1_2_0, axiom, !( (NB_ATTENTE_A_20 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_20 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_9_1_3, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_3 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_3 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_9_2_2_0, axiom, !( (NB_ATTENTE_A_9 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_9 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_4_1_12, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_12 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_12 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_2_1_11, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_11 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_11 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_10_4_2_0, axiom, !( (NB_ATTENTE_A_10 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_10 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(autorisation_B_2_18, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_18 * ATTENTE_B) -o (NB_ATTENTE_B_17 * CHOIX_2 * SUR_PONT_B) ) ).
fof(enregistrement_B_18, axiom, !( (NB_ATTENTE_B_18 * ROUTE_B) -o (NB_ATTENTE_B_19 * ATTENTE_B) ) ).
fof(timeout_A_0_0_1_9, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_9 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_9 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_A_14_1, axiom, !( (NB_ATTENTE_A_14 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_13 * SUR_PONT_A * CHOIX_1) ) ).
fof(timeout_B_8_8_2_0, axiom, !( (NB_ATTENTE_A_8 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_8 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_10_1_14, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_14 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_14 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_3_1_14, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_14 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_14 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(enregistrement_B_10, axiom, !( (NB_ATTENTE_B_10 * ROUTE_B) -o (NB_ATTENTE_B_11 * ATTENTE_B) ) ).
fof(timeout_A_0_4_1_3, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_3 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_3 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_13_10_2_0, axiom, !( (NB_ATTENTE_A_13 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_13 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_2_1_10, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_10 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_10 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_9_0_2_0, axiom, !( (NB_ATTENTE_A_9 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_9 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_6_1_2_0, axiom, !( (NB_ATTENTE_A_6 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_6 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_0_1_14, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_14 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_14 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_5_1_18, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_18 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_18 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_0_1_4, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_4 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_4 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_7_2_2_0, axiom, !( (NB_ATTENTE_A_7 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_7 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_0_1_17, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_17 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_17 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_2_1_18, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_18 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_18 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_B_2_9, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_9 * ATTENTE_B) -o (NB_ATTENTE_B_8 * CHOIX_2 * SUR_PONT_B) ) ).
fof(timeout_B_2_8_2_0, axiom, !( (NB_ATTENTE_A_2 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_2 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_11_10_2_0, axiom, !( (NB_ATTENTE_A_11 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_11 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_1_2_2_0, axiom, !( (NB_ATTENTE_A_1 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_1 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_10_2_2_0, axiom, !( (NB_ATTENTE_A_10 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_10 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_0_2_0, axiom, !( (NB_ATTENTE_A_2 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_2 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(decision_7_1, axiom, !( (CHOIX_1 * COMPTEUR_7) -o (CONTROLEUR_1 * COMPTEUR_8) ) ).
fof(timeout_A_0_9_1_19, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_19 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_19 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_2_1_8, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_8 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_8 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_1_1_18, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_18 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_18 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_7_1_18, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_18 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_18 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_0_1_11, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_11 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_11 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_1_10_2_0, axiom, !( (NB_ATTENTE_A_1 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_1 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_B_5, axiom, !( (NB_ATTENTE_B_5 * ROUTE_B) -o (NB_ATTENTE_B_6 * ATTENTE_B) ) ).
fof(autorisation_B_2_5, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_5 * ATTENTE_B) -o (NB_ATTENTE_B_4 * CHOIX_2 * SUR_PONT_B) ) ).
fof(timeout_B_3_0_2_0, axiom, !( (NB_ATTENTE_A_3 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_3 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_9_1_2_0, axiom, !( (NB_ATTENTE_A_9 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_9 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_4_2_0, axiom, !( (NB_ATTENTE_A_2 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_2 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_B_0, axiom, !( (NB_ATTENTE_B_0 * ROUTE_B) -o (NB_ATTENTE_B_1 * ATTENTE_B) ) ).
fof(timeout_A_0_8_1_11, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_11 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_11 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_0_1_8, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_8 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_8 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_5_4_2_0, axiom, !( (NB_ATTENTE_A_5 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_5 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_15_0_2_0, axiom, !( (NB_ATTENTE_A_15 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_15 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_3_1_18, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_18 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_18 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_8_1_6, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_6 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_6 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_10_1_13, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_13 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_13 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_7_1_16, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_16 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_16 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_3_1_11, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_11 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_11 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(enregistrement_B_3, axiom, !( (NB_ATTENTE_B_3 * ROUTE_B) -o (NB_ATTENTE_B_4 * ATTENTE_B) ) ).
fof(autorisation_A_13_1, axiom, !( (NB_ATTENTE_A_13 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_12 * SUR_PONT_A * CHOIX_1) ) ).
fof(timeout_B_17_4_2_0, axiom, !( (NB_ATTENTE_A_17 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_17 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_3_1_13, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_13 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_13 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(decision_9_1, axiom, !( (CHOIX_1 * COMPTEUR_9) -o (CONTROLEUR_1 * COMPTEUR_10) ) ).
fof(autorisation_B_2_12, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_12 * ATTENTE_B) -o (NB_ATTENTE_B_11 * CHOIX_2 * SUR_PONT_B) ) ).
fof(timeout_A_0_0_1_3, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_3 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_3 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_7_1_20, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_20 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_20 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_8_1_2_0, axiom, !( (NB_ATTENTE_A_8 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_8 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(autorisation_B_2_16, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_16 * ATTENTE_B) -o (NB_ATTENTE_B_15 * CHOIX_2 * SUR_PONT_B) ) ).
fof(timeout_B_15_2_2_0, axiom, !( (NB_ATTENTE_A_15 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_15 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_4_6_2_0, axiom, !( (NB_ATTENTE_A_4 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_4 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_7_1_4, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_4 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_4 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_10_1_11, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_11 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_11 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(altern_cpt_10_2, axiom, !( (CHOIX_2 * COMPTEUR_10) -o (VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_B_11, axiom, !( (NB_ATTENTE_B_11 * ROUTE_B) -o (NB_ATTENTE_B_12 * ATTENTE_B) ) ).
fof(timeout_B_18_2_2_0, axiom, !( (NB_ATTENTE_A_18 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_18 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_7_1_13, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_13 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_13 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_9_1_11, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_11 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_11 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_3_2_0, axiom, !( (NB_ATTENTE_A_2 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_2 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_18_4_2_0, axiom, !( (NB_ATTENTE_A_18 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_18 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(autorisation_B_2_7, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_7 * ATTENTE_B) -o (NB_ATTENTE_B_6 * CHOIX_2 * SUR_PONT_B) ) ).
fof(timeout_B_6_8_2_0, axiom, !( (NB_ATTENTE_A_6 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_6 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_18_5_2_0, axiom, !( (NB_ATTENTE_A_18 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_18 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_3_4_2_0, axiom, !( (NB_ATTENTE_A_3 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_3 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(autorisation_B_2_15, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_15 * ATTENTE_B) -o (NB_ATTENTE_B_14 * CHOIX_2 * SUR_PONT_B) ) ).
fof(timeout_A_0_9_1_15, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_15 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_15 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(enregistrement_B_6, axiom, !( (NB_ATTENTE_B_6 * ROUTE_B) -o (NB_ATTENTE_B_7 * ATTENTE_B) ) ).
fof(timeout_A_0_9_1_9, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_9 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_9 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_4_1_16, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_16 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_16 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_5_1_12, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_12 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_12 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_5_1_16, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_16 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_16 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_8_7_2_0, axiom, !( (NB_ATTENTE_A_8 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_8 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_20_0_2_0, axiom, !( (NB_ATTENTE_A_20 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_20 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_3_1_2, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_2 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_2 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_A_18_1, axiom, !( (NB_ATTENTE_A_18 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_17 * SUR_PONT_A * CHOIX_1) ) ).
fof(timeout_A_0_1_1_14, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_14 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_14 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_6_1_18, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_18 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_18 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_5_1_4, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_4 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_4 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(enregistrement_B_4, axiom, !( (NB_ATTENTE_B_4 * ROUTE_B) -o (NB_ATTENTE_B_5 * ATTENTE_B) ) ).
fof(enregistrement_A_9, axiom, !( (ROUTE_A * NB_ATTENTE_A_9) -o (NB_ATTENTE_A_10 * ATTENTE_A) ) ).
fof(timeout_B_1_6_2_0, axiom, !( (NB_ATTENTE_A_1 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_1 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_14_4_2_0, axiom, !( (NB_ATTENTE_A_14 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_14 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_16_10_2_0, axiom, !( (NB_ATTENTE_A_16 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_16 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_8_2_2_0, axiom, !( (NB_ATTENTE_A_8 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_8 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(autorisation_A_9_1, axiom, !( (NB_ATTENTE_A_9 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_8 * SUR_PONT_A * CHOIX_1) ) ).
fof(timeout_A_0_7_1_5, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_5 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_5 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_5_1_14, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_14 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_14 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_5_1_3, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_3 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_3 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(decision_3_2, axiom, !( (CHOIX_2 * COMPTEUR_3) -o (CONTROLEUR_2 * COMPTEUR_4) ) ).
fof(enregistrement_B_2, axiom, !( (NB_ATTENTE_B_2 * ROUTE_B) -o (NB_ATTENTE_B_3 * ATTENTE_B) ) ).
fof(timeout_A_0_6_1_10, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_10 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_10 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_7_1_15, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_15 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_15 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_5_1_2, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_2 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_2 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_1_1_1, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_1 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_1 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_1_1_19, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_19 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_19 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_10_1_16, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_16 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_16 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_13_5_2_0, axiom, !( (NB_ATTENTE_A_13 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_13 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(autorisation_B_2_3, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_3 * ATTENTE_B) -o (NB_ATTENTE_B_2 * CHOIX_2 * SUR_PONT_B) ) ).
fof(timeout_B_8_0_2_0, axiom, !( (NB_ATTENTE_A_8 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_8 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_7_1_19, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_19 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_19 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_A_8_1, axiom, !( (NB_ATTENTE_A_8 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_7 * SUR_PONT_A * CHOIX_1) ) ).
fof(timeout_B_5_3_2_0, axiom, !( (NB_ATTENTE_A_5 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_5 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_2_1_3, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_3 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_3 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_16_1_2_0, axiom, !( (NB_ATTENTE_A_16 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_16 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_A_11, axiom, !( (ROUTE_A * NB_ATTENTE_A_11) -o (NB_ATTENTE_A_12 * ATTENTE_A) ) ).
fof(timeout_B_10_8_2_0, axiom, !( (NB_ATTENTE_A_10 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_10 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_5_10_2_0, axiom, !( (NB_ATTENTE_A_5 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_5 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_19_9_2_0, axiom, !( (NB_ATTENTE_A_19 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_19 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_16_7_2_0, axiom, !( (NB_ATTENTE_A_16 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_16 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_1_9_2_0, axiom, !( (NB_ATTENTE_A_1 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_1 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(altern_cpt_10_1, axiom, !( (CHOIX_1 * COMPTEUR_10) -o (VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_9_7_2_0, axiom, !( (NB_ATTENTE_A_9 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_9 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_17_5_2_0, axiom, !( (NB_ATTENTE_A_17 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_17 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_7_0_2_0, axiom, !( (NB_ATTENTE_A_7 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_7 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_10_1_10, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_10 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_10 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(enregistrement_A_17, axiom, !( (ROUTE_A * NB_ATTENTE_A_17) -o (NB_ATTENTE_A_18 * ATTENTE_A) ) ).
fof(timeout_B_8_10_2_0, axiom, !( (NB_ATTENTE_A_8 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_8 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_18_9_2_0, axiom, !( (NB_ATTENTE_A_18 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_18 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_7_2_0, axiom, !( (NB_ATTENTE_A_2 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_2 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_5_1_9, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_9 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_9 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_A_7_1, axiom, !( (NB_ATTENTE_A_7 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_6 * SUR_PONT_A * CHOIX_1) ) ).
fof(autorisation_B_2_10, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_10 * ATTENTE_B) -o (NB_ATTENTE_B_9 * CHOIX_2 * SUR_PONT_B) ) ).
fof(timeout_B_17_2_2_0, axiom, !( (NB_ATTENTE_A_17 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_17 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_4_1_14, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_14 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_14 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_8_3_2_0, axiom, !( (NB_ATTENTE_A_8 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_8 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_A_2, axiom, !( (ROUTE_A * NB_ATTENTE_A_2) -o (NB_ATTENTE_A_3 * ATTENTE_A) ) ).
fof(timeout_A_0_4_1_17, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_17 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_17 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_13_9_2_0, axiom, !( (NB_ATTENTE_A_13 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_13 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_1_1_6, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_6 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_6 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_2_1_1, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_1 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_1 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_17_3_2_0, axiom, !( (NB_ATTENTE_A_17 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_17 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_7_1_2, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_2 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_2 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_3_1_1, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_1 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_1 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_12_5_2_0, axiom, !( (NB_ATTENTE_A_12 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_12 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_6_1_13, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_13 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_13 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_4_1_8, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_8 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_8 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_10_1_20, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_20 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_20 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_1_1_8, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_8 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_8 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_10_1_19, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_19 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_19 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_19_4_2_0, axiom, !( (NB_ATTENTE_A_19 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_19 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_13_3_2_0, axiom, !( (NB_ATTENTE_A_13 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_13 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(autorisation_A_5_1, axiom, !( (NB_ATTENTE_A_5 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_4 * SUR_PONT_A * CHOIX_1) ) ).
fof(timeout_B_16_3_2_0, axiom, !( (NB_ATTENTE_A_16 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_16 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(decision_4_1, axiom, !( (CHOIX_1 * COMPTEUR_4) -o (CONTROLEUR_1 * COMPTEUR_5) ) ).
fof(timeout_A_0_10_1_18, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_18 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_18 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_14_5_2_0, axiom, !( (NB_ATTENTE_A_14 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_14 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_16_8_2_0, axiom, !( (NB_ATTENTE_A_16 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_16 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_17_6_2_0, axiom, !( (NB_ATTENTE_A_17 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_17 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(decision_1_2, axiom, !( (CHOIX_2 * COMPTEUR_1) -o (CONTROLEUR_2 * COMPTEUR_2) ) ).
fof(timeout_A_0_8_1_2, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_2 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_2 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_1_1_9, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_9 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_9 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_A_6_1, axiom, !( (NB_ATTENTE_A_6 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_5 * SUR_PONT_A * CHOIX_1) ) ).
fof(enregistrement_B_1, axiom, !( (NB_ATTENTE_B_1 * ROUTE_B) -o (NB_ATTENTE_B_2 * ATTENTE_B) ) ).
fof(enregistrement_A_20, axiom, !( (ROUTE_A * NB_ATTENTE_A_20) -o (NB_ATTENTE_A_0 * ATTENTE_A) ) ).
fof(timeout_A_0_6_1_8, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_8 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_8 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_7_7_2_0, axiom, !( (NB_ATTENTE_A_7 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_7 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_7_6_2_0, axiom, !( (NB_ATTENTE_A_7 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_7 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_5_1_15, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_15 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_15 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_A_11_1, axiom, !( (NB_ATTENTE_A_11 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_10 * SUR_PONT_A * CHOIX_1) ) ).
fof(timeout_B_9_4_2_0, axiom, !( (NB_ATTENTE_A_9 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_9 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_12_7_2_0, axiom, !( (NB_ATTENTE_A_12 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_12 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_19_7_2_0, axiom, !( (NB_ATTENTE_A_19 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_19 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_19_5_2_0, axiom, !( (NB_ATTENTE_A_19 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_19 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_5_2_2_0, axiom, !( (NB_ATTENTE_A_5 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_5 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_6_1_3, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_3 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_3 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_10_0_2_0, axiom, !( (NB_ATTENTE_A_10 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_10 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_5_1_1, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_1 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_1 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_20_2_2_0, axiom, !( (NB_ATTENTE_A_20 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_20 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_7_1_14, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_14 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_14 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_15_6_2_0, axiom, !( (NB_ATTENTE_A_15 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_15 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_8_1_4, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_4 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_4 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(decision_6_1, axiom, !( (CHOIX_1 * COMPTEUR_6) -o (CONTROLEUR_1 * COMPTEUR_7) ) ).
fof(timeout_A_0_8_1_12, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_12 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_12 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_3_5_2_0, axiom, !( (NB_ATTENTE_A_3 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_3 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_17_8_2_0, axiom, !( (NB_ATTENTE_A_17 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_17 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_11_2_2_0, axiom, !( (NB_ATTENTE_A_11 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_11 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_15_10_2_0, axiom, !( (NB_ATTENTE_A_15 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_15 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_5_1_13, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_13 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_13 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_2_1_9, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_9 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_9 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_B_2_17, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_17 * ATTENTE_B) -o (NB_ATTENTE_B_16 * CHOIX_2 * SUR_PONT_B) ) ).
fof(timeout_B_3_2_2_0, axiom, !( (NB_ATTENTE_A_3 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_3 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_12_8_2_0, axiom, !( (NB_ATTENTE_A_12 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_12 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_10_5_2_0, axiom, !( (NB_ATTENTE_A_10 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_10 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_19_6_2_0, axiom, !( (NB_ATTENTE_A_19 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_19 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_19_3_2_0, axiom, !( (NB_ATTENTE_A_19 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_19 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_9_1_1, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_1 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_1 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_1_4_2_0, axiom, !( (NB_ATTENTE_A_1 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_1 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_4_1_10, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_10 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_10 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_B_2_1, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_1 * ATTENTE_B) -o (NB_ATTENTE_B_0 * CHOIX_2 * SUR_PONT_B) ) ).
fof(timeout_B_7_3_2_0, axiom, !( (NB_ATTENTE_A_7 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_7 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_3_1_20, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_20 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_20 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_11_3_2_0, axiom, !( (NB_ATTENTE_A_11 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_11 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_3_1_12, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_12 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_12 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_9_1_8, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_8 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_8 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_18_8_2_0, axiom, !( (NB_ATTENTE_A_18 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_18 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(autorisation_A_20_1, axiom, !( (NB_ATTENTE_A_20 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_19 * SUR_PONT_A * CHOIX_1) ) ).
fof(timeout_A_0_4_1_20, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_20 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_20 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_7_1_2_0, axiom, !( (NB_ATTENTE_A_7 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_7 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_2_1_4, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_4 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_4 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_0_1_5, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_5 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_5 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_10_1_9, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_9 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_9 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_6_10_2_0, axiom, !( (NB_ATTENTE_A_6 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_6 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(decision_4_2, axiom, !( (CHOIX_2 * COMPTEUR_4) -o (CONTROLEUR_2 * COMPTEUR_5) ) ).
fof(timeout_A_0_6_1_20, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_20 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_20 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_2_1_2_0, axiom, !( (NB_ATTENTE_A_2 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_2 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_9_1_16, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_16 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_16 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_5_7_2_0, axiom, !( (NB_ATTENTE_A_5 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_5 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_A_1, axiom, !( (ROUTE_A * NB_ATTENTE_A_1) -o (NB_ATTENTE_A_2 * ATTENTE_A) ) ).
fof(timeout_B_20_3_2_0, axiom, !( (NB_ATTENTE_A_20 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_20 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_3_8_2_0, axiom, !( (NB_ATTENTE_A_3 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_3 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_19_1_2_0, axiom, !( (NB_ATTENTE_A_19 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_19 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_13_0_2_0, axiom, !( (NB_ATTENTE_A_13 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_13 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_6_1_7, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_7 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_7 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_13_7_2_0, axiom, !( (NB_ATTENTE_A_13 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_13 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_1_1_17, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_17 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_17 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_4_1_9, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_9 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_9 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(basculement_1, axiom, !( (CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * VIDANGE_1) -o (CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CHOIX_1) ) ).
fof(timeout_A_0_0_1_13, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_13 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_13 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_19_8_2_0, axiom, !( (NB_ATTENTE_A_19 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_19 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_9_1_6, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_6 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_6 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_1_1_12, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_12 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_12 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_5_6_2_0, axiom, !( (NB_ATTENTE_A_5 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_5 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_9_1_12, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_12 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_12 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_A_12_1, axiom, !( (NB_ATTENTE_A_12 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_11 * SUR_PONT_A * CHOIX_1) ) ).
fof(decision_2_1, axiom, !( (CHOIX_1 * COMPTEUR_2) -o (CONTROLEUR_1 * COMPTEUR_3) ) ).
fof(timeout_A_0_0_1_19, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_19 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_19 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_8_6_2_0, axiom, !( (NB_ATTENTE_A_8 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_8 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_4_5_2_0, axiom, !( (NB_ATTENTE_A_4 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_4 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_10_1_17, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_17 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_17 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_9_1_10, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_10 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_10 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_7_4_2_0, axiom, !( (NB_ATTENTE_A_7 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_7 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_10_1_8, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_8 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_8 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_12_2_2_0, axiom, !( (NB_ATTENTE_A_12 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_12 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_11_5_2_0, axiom, !( (NB_ATTENTE_A_11 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_11 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_1_5_2_0, axiom, !( (NB_ATTENTE_A_1 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_1 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_13_1_2_0, axiom, !( (NB_ATTENTE_A_13 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_13 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_9_1_4, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_4 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_4 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_7_1_3, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_3 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_3 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(decision_6_2, axiom, !( (CHOIX_2 * COMPTEUR_6) -o (CONTROLEUR_2 * COMPTEUR_7) ) ).
fof(timeout_B_4_8_2_0, axiom, !( (NB_ATTENTE_A_4 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_4 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(autorisation_B_2_14, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_14 * ATTENTE_B) -o (NB_ATTENTE_B_13 * CHOIX_2 * SUR_PONT_B) ) ).
fof(timeout_B_9_3_2_0, axiom, !( (NB_ATTENTE_A_9 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_9 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_10_1_4, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_4 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_4 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_4_1_18, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_18 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_18 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_0_1_20, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_20 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_20 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(enregistrement_B_15, axiom, !( (NB_ATTENTE_B_15 * ROUTE_B) -o (NB_ATTENTE_B_16 * ATTENTE_B) ) ).
fof(timeout_A_0_0_1_6, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_6 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_6 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_17_10_2_0, axiom, !( (NB_ATTENTE_A_17 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_17 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_4_4_2_0, axiom, !( (NB_ATTENTE_A_4 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_4 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_1_1_2_0, axiom, !( (NB_ATTENTE_A_1 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_1 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_7_1_17, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_17 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_17 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_9_9_2_0, axiom, !( (NB_ATTENTE_A_9 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_9 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_2_1_12, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_12 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_12 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_14_9_2_0, axiom, !( (NB_ATTENTE_A_14 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_14 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_9_1_13, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_13 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_13 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_8_1_18, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_18 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_18 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_A_2_1, axiom, !( (NB_ATTENTE_A_2 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_1 * SUR_PONT_A * CHOIX_1) ) ).
fof(timeout_A_0_0_1_1, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_1 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_1 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_14_8_2_0, axiom, !( (NB_ATTENTE_A_14 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_14 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_B_16, axiom, !( (NB_ATTENTE_B_16 * ROUTE_B) -o (NB_ATTENTE_B_17 * ATTENTE_B) ) ).
fof(timeout_B_9_8_2_0, axiom, !( (NB_ATTENTE_A_9 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_9 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_1_1_20, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_20 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_20 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_0_1_15, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_15 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_15 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_15_7_2_0, axiom, !( (NB_ATTENTE_A_15 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_15 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_B_9, axiom, !( (NB_ATTENTE_B_9 * ROUTE_B) -o (NB_ATTENTE_B_10 * ATTENTE_B) ) ).
fof(timeout_B_15_3_2_0, axiom, !( (NB_ATTENTE_A_15 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_15 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_2_1_20, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_20 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_20 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_17_9_2_0, axiom, !( (NB_ATTENTE_A_17 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_17 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_1_1_5, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_5 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_5 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_9_1_18, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_18 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_18 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_5_1_5, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_5 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_5 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_A_3_1, axiom, !( (NB_ATTENTE_A_3 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_2 * SUR_PONT_A * CHOIX_1) ) ).
fof(timeout_A_0_4_1_1, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_1 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_1 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_2_1_17, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_17 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_17 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_10_10_2_0, axiom, !( (NB_ATTENTE_A_10 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_10 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_1_1_11, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_11 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_11 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_9_5_2_0, axiom, !( (NB_ATTENTE_A_9 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_9 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_16_9_2_0, axiom, !( (NB_ATTENTE_A_16 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_16 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_B_19, axiom, !( (NB_ATTENTE_B_19 * ROUTE_B) -o (NB_ATTENTE_B_20 * ATTENTE_B) ) ).
fof(timeout_B_10_9_2_0, axiom, !( (NB_ATTENTE_A_10 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_10 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_11_4_2_0, axiom, !( (NB_ATTENTE_A_11 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_11 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_5_9_2_0, axiom, !( (NB_ATTENTE_A_5 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_5 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_6_1_12, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_12 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_12 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_7_1_12, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_12 * COMPTEUR_7) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_12 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_B_2_4, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_4 * ATTENTE_B) -o (NB_ATTENTE_B_3 * CHOIX_2 * SUR_PONT_B) ) ).
fof(timeout_A_0_3_1_7, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_7 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_7 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(decision_3_1, axiom, !( (CHOIX_1 * COMPTEUR_3) -o (CONTROLEUR_1 * COMPTEUR_4) ) ).
fof(timeout_B_14_10_2_0, axiom, !( (NB_ATTENTE_A_14 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_14 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_9_1_2, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_2 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_2 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_5_1_8, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_8 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_8 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_4_1_2_0, axiom, !( (NB_ATTENTE_A_4 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_4 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_11_1_2_0, axiom, !( (NB_ATTENTE_A_11 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_11 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_9_1_7, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_7 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_7 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(enregistrement_A_19, axiom, !( (ROUTE_A * NB_ATTENTE_A_19) -o (NB_ATTENTE_A_20 * ATTENTE_A) ) ).
fof(timeout_A_0_8_1_16, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_16 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_16 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_1_8_2_0, axiom, !( (NB_ATTENTE_A_1 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_1 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_14_1_2_0, axiom, !( (NB_ATTENTE_A_14 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_14 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_6_4_2_0, axiom, !( (NB_ATTENTE_A_6 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_6 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_12_3_2_0, axiom, !( (NB_ATTENTE_A_12 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_12 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_3_1_6, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_6 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_6 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_5_1_11, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_11 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_11 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_17_1_2_0, axiom, !( (NB_ATTENTE_A_17 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_17 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_18_7_2_0, axiom, !( (NB_ATTENTE_A_18 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_18 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_A_14, axiom, !( (ROUTE_A * NB_ATTENTE_A_14) -o (NB_ATTENTE_A_15 * ATTENTE_A) ) ).
fof(timeout_A_0_8_1_14, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_14 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_14 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_4_10_2_0, axiom, !( (NB_ATTENTE_A_4 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_4 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_19_0_2_0, axiom, !( (NB_ATTENTE_A_19 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_19 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_7_9_2_0, axiom, !( (NB_ATTENTE_A_7 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_7 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_6_1_16, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_16 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_16 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(enregistrement_A_8, axiom, !( (ROUTE_A * NB_ATTENTE_A_8) -o (NB_ATTENTE_A_9 * ATTENTE_A) ) ).
fof(timeout_A_0_10_1_6, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_6 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_6 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_B_2_8, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_8 * ATTENTE_B) -o (NB_ATTENTE_B_7 * CHOIX_2 * SUR_PONT_B) ) ).
fof(enregistrement_A_6, axiom, !( (ROUTE_A * NB_ATTENTE_A_6) -o (NB_ATTENTE_A_7 * ATTENTE_A) ) ).
fof(timeout_B_7_5_2_0, axiom, !( (NB_ATTENTE_A_7 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_7 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(autorisation_A_4_1, axiom, !( (NB_ATTENTE_A_4 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_3 * SUR_PONT_A * CHOIX_1) ) ).
fof(timeout_B_3_1_2_0, axiom, !( (NB_ATTENTE_A_3 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_3 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_20_5_2_0, axiom, !( (NB_ATTENTE_A_20 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_20 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_13_8_2_0, axiom, !( (NB_ATTENTE_A_13 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_13 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_17_0_2_0, axiom, !( (NB_ATTENTE_A_17 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_17 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_14_2_2_0, axiom, !( (NB_ATTENTE_A_14 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_2) -o (NB_ATTENTE_A_14 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_A_16, axiom, !( (ROUTE_A * NB_ATTENTE_A_16) -o (NB_ATTENTE_A_17 * ATTENTE_A) ) ).
fof(timeout_B_7_8_2_0, axiom, !( (NB_ATTENTE_A_7 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_8) -o (NB_ATTENTE_A_7 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_A_0, axiom, !( (ROUTE_A * NB_ATTENTE_A_0) -o (NB_ATTENTE_A_1 * ATTENTE_A) ) ).
fof(enregistrement_A_7, axiom, !( (ROUTE_A * NB_ATTENTE_A_7) -o (NB_ATTENTE_A_8 * ATTENTE_A) ) ).
fof(timeout_B_8_4_2_0, axiom, !( (NB_ATTENTE_A_8 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_8 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_3_1_9, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_9 * COMPTEUR_3) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_9 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_A_10_1, axiom, !( (NB_ATTENTE_A_10 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_9 * SUR_PONT_A * CHOIX_1) ) ).
fof(autorisation_B_2_13, axiom, !( (CAPACITE * CONTROLEUR_2 * NB_ATTENTE_B_13 * ATTENTE_B) -o (NB_ATTENTE_B_12 * CHOIX_2 * SUR_PONT_B) ) ).
fof(timeout_B_18_6_2_0, axiom, !( (NB_ATTENTE_A_18 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_18 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_A_12, axiom, !( (ROUTE_A * NB_ATTENTE_A_12) -o (NB_ATTENTE_A_13 * ATTENTE_A) ) ).
fof(timeout_A_0_10_1_1, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_1 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_1 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_9_1_17, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_17 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_17 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_10_1_15, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_15 * COMPTEUR_10) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_15 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(decision_9_2, axiom, !( (CHOIX_2 * COMPTEUR_9) -o (CONTROLEUR_2 * COMPTEUR_10) ) ).
fof(timeout_A_0_6_1_11, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_11 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_11 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_1_3_2_0, axiom, !( (NB_ATTENTE_A_1 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_1 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_16_4_2_0, axiom, !( (NB_ATTENTE_A_16 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_16 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_12_0_2_0, axiom, !( (NB_ATTENTE_A_12 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_12 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_2_5_2_0, axiom, !( (NB_ATTENTE_A_2 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_2 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(basculement_2, axiom, !( (CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * VIDANGE_2) -o (CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CHOIX_2) ) ).
fof(timeout_A_0_9_1_20, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_20 * COMPTEUR_9) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_20 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_5_5_2_0, axiom, !( (NB_ATTENTE_A_5 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_5 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_20_4_2_0, axiom, !( (NB_ATTENTE_A_20 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_4) -o (NB_ATTENTE_A_20 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_8_9_2_0, axiom, !( (NB_ATTENTE_A_8 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_8 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_6_1_17, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_17 * COMPTEUR_6) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_17 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_1_1_15, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_15 * COMPTEUR_1) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_15 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_14_3_2_0, axiom, !( (NB_ATTENTE_A_14 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_3) -o (NB_ATTENTE_A_14 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_11_6_2_0, axiom, !( (NB_ATTENTE_A_11 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_6) -o (NB_ATTENTE_A_11 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_8_1_15, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_15 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_15 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(autorisation_A_17_1, axiom, !( (NB_ATTENTE_A_17 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_16 * SUR_PONT_A * CHOIX_1) ) ).
fof(timeout_B_12_9_2_0, axiom, !( (NB_ATTENTE_A_12 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_12 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_3_7_2_0, axiom, !( (NB_ATTENTE_A_3 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_7) -o (NB_ATTENTE_A_3 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_3_9_2_0, axiom, !( (NB_ATTENTE_A_3 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_9) -o (NB_ATTENTE_A_3 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_A_3, axiom, !( (ROUTE_A * NB_ATTENTE_A_3) -o (NB_ATTENTE_A_4 * ATTENTE_A) ) ).
fof(timeout_B_15_5_2_0, axiom, !( (NB_ATTENTE_A_15 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_5) -o (NB_ATTENTE_A_15 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_A_0_0_1_12, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_12 * COMPTEUR_0) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_12 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_4_1_7, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_7 * COMPTEUR_4) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_7 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(enregistrement_A_4, axiom, !( (ROUTE_A * NB_ATTENTE_A_4) -o (NB_ATTENTE_A_5 * ATTENTE_A) ) ).
fof(timeout_A_0_5_1_17, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_17 * COMPTEUR_5) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_17 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_2_1_14, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_14 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_14 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(decision_2_2, axiom, !( (CHOIX_2 * COMPTEUR_2) -o (CONTROLEUR_2 * COMPTEUR_3) ) ).
fof(timeout_A_0_2_1_15, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_15 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_15 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_5_0_2_0, axiom, !( (NB_ATTENTE_A_5 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_0) -o (NB_ATTENTE_A_5 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(timeout_B_9_10_2_0, axiom, !( (NB_ATTENTE_A_9 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_9 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(enregistrement_B_13, axiom, !( (NB_ATTENTE_B_13 * ROUTE_B) -o (NB_ATTENTE_B_14 * ATTENTE_B) ) ).
fof(timeout_B_5_1_2_0, axiom, !( (NB_ATTENTE_A_5 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_1) -o (NB_ATTENTE_A_5 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(autorisation_A_19_1, axiom, !( (NB_ATTENTE_A_19 * ATTENTE_A * CAPACITE * CONTROLEUR_1) -o (NB_ATTENTE_A_18 * SUR_PONT_A * CHOIX_1) ) ).
fof(timeout_A_0_8_1_19, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_19 * COMPTEUR_8) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_19 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_A_0_2_1_13, axiom, !( (NB_ATTENTE_A_0 * CONTROLEUR_1 * NB_ATTENTE_B_13 * COMPTEUR_2) -o (NB_ATTENTE_A_0 * NB_ATTENTE_B_13 * VIDANGE_2 * COMPTEUR_0) ) ).
fof(timeout_B_12_10_2_0, axiom, !( (NB_ATTENTE_A_12 * CONTROLEUR_2 * NB_ATTENTE_B_0 * COMPTEUR_10) -o (NB_ATTENTE_A_12 * NB_ATTENTE_B_0 * VIDANGE_1 * COMPTEUR_0) ) ).
fof(con1, conjecture, ATTENTE_A * ATTENTE_A * ATTENTE_A * ATTENTE_B * ATTENTE_B * ATTENTE_B * ATTENTE_B * ATTENTE_B * ATTENTE_B * ATTENTE_B * ATTENTE_B * ATTENTE_B * ATTENTE_B * ATTENTE_B * ATTENTE_B * ATTENTE_B * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * CAPACITE * COMPTEUR_1 * CONTROLEUR_2 * NB_ATTENTE_A_3 * NB_ATTENTE_B_13 * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_A * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B * ROUTE_B).

%--------------------------------------------------------------------------
