
%--------------------------------------------------------------------------
% File     : 
% Domain   : Petri-nets
% Problem  : SharedMemory 
% Version  : 1.0
% Refs     : The Model Checking Contest
% Source   : https://pnrepository.lip6.fr/mcc/models/all/browser.html
%
% Status (linear) : Theorem
% Rating (linear) : 0.00 v1.0.0
%--------------------------------------------------------------------------
fof(inital_state, axiom, Ext_Bus * Active_7 * Active_8 * Active_5 * Active_6 * Active_11 * Active_12 * Active_9 * Active_10 * Memory_19 * Memory_20 * Memory_17 * Memory_18 * Active_3 * Active_4 * Active_1 * Active_2 * Memory_12 * Memory_11 * Memory_10 * Memory_9 * Memory_16 * Memory_15 * Memory_14 * Memory_13 * Memory_4 * Memory_3 * Memory_2 * Memory_1 * Memory_8 * Memory_7 * Memory_6 * Memory_5 * Active_14 * Active_13 * Active_16 * Active_15 * Active_18 * Active_17 * Active_20 * Active_19).
fof(End_Ext_Acc_17_4, axiom, !( (Ext_Mem_Acc_17_4) -o (Memory_4 * Active_17 * Ext_Bus) ) ).
fof(End_Ext_Acc_3_2, axiom, !( (Ext_Mem_Acc_3_2) -o (Ext_Bus * Active_3 * Memory_2) ) ).
fof(End_Ext_Acc_11_7, axiom, !( (Ext_Mem_Acc_11_7) -o (Active_11 * Memory_7 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_19_5, axiom, !( (Queue_19 * Memory_5 * Ext_Bus) -o (Ext_Mem_Acc_19_5) ) ).
fof(End_Ext_Acc_14_13, axiom, !( (Ext_Mem_Acc_14_13) -o (Active_14 * Memory_13 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_5_13, axiom, !( (Queue_5 * Ext_Bus * Memory_13) -o (Ext_Mem_Acc_5_13) ) ).
fof(End_Ext_Acc_18_12, axiom, !( (Ext_Mem_Acc_18_12) -o (Active_18 * Memory_12 * Ext_Bus) ) ).
fof(End_Ext_Acc_1_19, axiom, !( (Ext_Mem_Acc_1_19) -o (Memory_19 * Active_1 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_5_19, axiom, !( (Queue_5 * Ext_Bus * Memory_19) -o (Ext_Mem_Acc_5_19) ) ).
fof(Begin_Ext_Acc_16_18, axiom, !( (Queue_16 * Memory_18 * Ext_Bus) -o (Ext_Mem_Acc_16_18) ) ).
fof(Begin_Ext_Acc_16_15, axiom, !( (Ext_Bus * Memory_15 * Queue_16) -o (Ext_Mem_Acc_16_15) ) ).
fof(Begin_Ext_Acc_18_8, axiom, !( (Ext_Bus * Memory_8 * Queue_18) -o (Ext_Mem_Acc_18_8) ) ).
fof(Begin_Ext_Acc_20_19, axiom, !( (Queue_20 * Ext_Bus * Memory_19) -o (Ext_Mem_Acc_20_19) ) ).
fof(Begin_Ext_Acc_1_11, axiom, !( (Ext_Bus * Memory_11 * Queue_1) -o (Ext_Mem_Acc_1_11) ) ).
fof(Begin_Ext_Acc_3_10, axiom, !( (Memory_10 * Ext_Bus * Queue_3) -o (Ext_Mem_Acc_3_10) ) ).
fof(Begin_Ext_Acc_14_7, axiom, !( (Queue_14 * Ext_Bus * Memory_7) -o (Ext_Mem_Acc_14_7) ) ).
fof(End_Ext_Acc_7_4, axiom, !( (Ext_Mem_Acc_7_4) -o (Ext_Bus * Active_7 * Memory_4) ) ).
fof(Begin_Ext_Acc_16_8, axiom, !( (Ext_Bus * Memory_8 * Queue_16) -o (Ext_Mem_Acc_16_8) ) ).
fof(Begin_Ext_Acc_9_13, axiom, !( (Queue_9 * Memory_13 * Ext_Bus) -o (Ext_Mem_Acc_9_13) ) ).
fof(Begin_Ext_Acc_7_9, axiom, !( (Memory_9 * Ext_Bus * Queue_7) -o (Ext_Mem_Acc_7_9) ) ).
fof(End_Ext_Acc_9_11, axiom, !( (Ext_Mem_Acc_9_11) -o (Active_9 * Memory_11 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_7_6, axiom, !( (Memory_6 * Ext_Bus * Queue_7) -o (Ext_Mem_Acc_7_6) ) ).
fof(End_Ext_Acc_18_10, axiom, !( (Ext_Mem_Acc_18_10) -o (Ext_Bus * Active_18 * Memory_10) ) ).
fof(Begin_Ext_Acc_7_13, axiom, !( (Queue_7 * Ext_Bus * Memory_13) -o (Ext_Mem_Acc_7_13) ) ).
fof(Begin_Own_Acc_10, axiom, !( (Active_10) -o (OwnMemAcc_10) ) ).
fof(Begin_Ext_Acc_15_18, axiom, !( (Queue_15 * Memory_18 * Ext_Bus) -o (Ext_Mem_Acc_15_18) ) ).
fof(Begin_Ext_Acc_7_14, axiom, !( (Queue_7 * Ext_Bus * Memory_14) -o (Ext_Mem_Acc_7_14) ) ).
fof(End_Ext_Acc_6_18, axiom, !( (Ext_Mem_Acc_6_18) -o (Active_6 * Memory_18 * Ext_Bus) ) ).
fof(End_Ext_Acc_15_16, axiom, !( (Ext_Mem_Acc_15_16) -o (Ext_Bus * Active_15 * Memory_16) ) ).
fof(End_Ext_Acc_9_10, axiom, !( (Ext_Mem_Acc_9_10) -o (Memory_10 * Active_9 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_15_2, axiom, !( (Queue_15 * Ext_Bus * Memory_2) -o (Ext_Mem_Acc_15_2) ) ).
fof(End_Ext_Acc_11_2, axiom, !( (Ext_Mem_Acc_11_2) -o (Ext_Bus * Memory_2 * Active_11) ) ).
fof(End_Ext_Acc_13_20, axiom, !( (Ext_Mem_Acc_13_20) -o (Ext_Bus * Active_13 * Memory_20) ) ).
fof(End_Ext_Acc_2_14, axiom, !( (Ext_Mem_Acc_2_14) -o (Ext_Bus * Active_2 * Memory_14) ) ).
fof(End_Ext_Acc_16_15, axiom, !( (Ext_Mem_Acc_16_15) -o (Ext_Bus * Memory_15 * Active_16) ) ).
fof(End_Ext_Acc_6_5, axiom, !( (Ext_Mem_Acc_6_5) -o (Ext_Bus * Memory_5 * Active_6) ) ).
fof(Begin_Ext_Acc_5_6, axiom, !( (Memory_6 * Ext_Bus * Queue_5) -o (Ext_Mem_Acc_5_6) ) ).
fof(End_Ext_Acc_16_8, axiom, !( (Ext_Mem_Acc_16_8) -o (Ext_Bus * Active_16 * Memory_8) ) ).
fof(Begin_Ext_Acc_10_2, axiom, !( (Memory_2 * Ext_Bus * Queue_10) -o (Ext_Mem_Acc_10_2) ) ).
fof(End_Ext_Acc_6_15, axiom, !( (Ext_Mem_Acc_6_15) -o (Memory_15 * Active_6 * Ext_Bus) ) ).
fof(End_Ext_Acc_5_3, axiom, !( (Ext_Mem_Acc_5_3) -o (Active_5 * Memory_3 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_6_20, axiom, !( (Queue_6 * Memory_20 * Ext_Bus) -o (Ext_Mem_Acc_6_20) ) ).
fof(Begin_Ext_Acc_15_10, axiom, !( (Memory_10 * Ext_Bus * Queue_15) -o (Ext_Mem_Acc_15_10) ) ).
fof(End_Ext_Acc_18_3, axiom, !( (Ext_Mem_Acc_18_3) -o (Memory_3 * Active_18 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_2_17, axiom, !( (Queue_2 * Ext_Bus * Memory_17) -o (Ext_Mem_Acc_2_17) ) ).
fof(Begin_Ext_Acc_6_13, axiom, !( (Queue_6 * Ext_Bus * Memory_13) -o (Ext_Mem_Acc_6_13) ) ).
fof(Begin_Ext_Acc_4_1, axiom, !( (Memory_1 * Ext_Bus * Queue_4) -o (Ext_Mem_Acc_4_1) ) ).
fof(Begin_Ext_Acc_13_18, axiom, !( (Queue_13 * Memory_18 * Ext_Bus) -o (Ext_Mem_Acc_13_18) ) ).
fof(Begin_Ext_Acc_19_6, axiom, !( (Ext_Bus * Memory_6 * Queue_19) -o (Ext_Mem_Acc_19_6) ) ).
fof(End_Ext_Acc_7_1, axiom, !( (Ext_Mem_Acc_7_1) -o (Ext_Bus * Active_7 * Memory_1) ) ).
fof(Begin_Ext_Acc_10_20, axiom, !( (Ext_Bus * Memory_20 * Queue_10) -o (Ext_Mem_Acc_10_20) ) ).
fof(Begin_Ext_Acc_16_14, axiom, !( (Ext_Bus * Memory_14 * Queue_16) -o (Ext_Mem_Acc_16_14) ) ).
fof(End_Ext_Acc_13_16, axiom, !( (Ext_Mem_Acc_13_16) -o (Memory_16 * Active_13 * Ext_Bus) ) ).
fof(End_Ext_Acc_7_14, axiom, !( (Ext_Mem_Acc_7_14) -o (Active_7 * Memory_14 * Ext_Bus) ) ).
fof(End_Ext_Acc_20_4, axiom, !( (Ext_Mem_Acc_20_4) -o (Ext_Bus * Active_20 * Memory_4) ) ).
fof(End_Ext_Acc_2_12, axiom, !( (Ext_Mem_Acc_2_12) -o (Ext_Bus * Memory_12 * Active_2) ) ).
fof(End_Ext_Acc_2_9, axiom, !( (Ext_Mem_Acc_2_9) -o (Ext_Bus * Memory_9 * Active_2) ) ).
fof(End_Ext_Acc_19_8, axiom, !( (Ext_Mem_Acc_19_8) -o (Ext_Bus * Active_19 * Memory_8) ) ).
fof(End_Ext_Acc_15_2, axiom, !( (Ext_Mem_Acc_15_2) -o (Ext_Bus * Active_15 * Memory_2) ) ).
fof(Begin_Ext_Acc_3_19, axiom, !( (Queue_3 * Ext_Bus * Memory_19) -o (Ext_Mem_Acc_3_19) ) ).
fof(End_Ext_Acc_5_12, axiom, !( (Ext_Mem_Acc_5_12) -o (Active_5 * Memory_12 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_18_2, axiom, !( (Queue_18 * Memory_2 * Ext_Bus) -o (Ext_Mem_Acc_18_2) ) ).
fof(End_Ext_Acc_11_17, axiom, !( (Ext_Mem_Acc_11_17) -o (Memory_17 * Active_11 * Ext_Bus) ) ).
fof(End_Ext_Acc_9_4, axiom, !( (Ext_Mem_Acc_9_4) -o (Ext_Bus * Memory_4 * Active_9) ) ).
fof(Begin_Ext_Acc_16_13, axiom, !( (Ext_Bus * Memory_13 * Queue_16) -o (Ext_Mem_Acc_16_13) ) ).
fof(Begin_Ext_Acc_4_2, axiom, !( (Ext_Bus * Memory_2 * Queue_4) -o (Ext_Mem_Acc_4_2) ) ).
fof(Req_Ext_Acc_2, axiom, !( (Active_2) -o (Queue_2) ) ).
fof(Begin_Ext_Acc_1_10, axiom, !( (Memory_10 * Ext_Bus * Queue_1) -o (Ext_Mem_Acc_1_10) ) ).
fof(End_Ext_Acc_7_19, axiom, !( (Ext_Mem_Acc_7_19) -o (Active_7 * Memory_19 * Ext_Bus) ) ).
fof(End_Ext_Acc_9_17, axiom, !( (Ext_Mem_Acc_9_17) -o (Memory_17 * Active_9 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_6_7, axiom, !( (Queue_6 * Memory_7 * Ext_Bus) -o (Ext_Mem_Acc_6_7) ) ).
fof(End_Ext_Acc_4_18, axiom, !( (Ext_Mem_Acc_4_18) -o (Memory_18 * Active_4 * Ext_Bus) ) ).
fof(End_Ext_Acc_16_6, axiom, !( (Ext_Mem_Acc_16_6) -o (Memory_6 * Active_16 * Ext_Bus) ) ).
fof(End_Ext_Acc_12_15, axiom, !( (Ext_Mem_Acc_12_15) -o (Ext_Bus * Active_12 * Memory_15) ) ).
fof(End_Ext_Acc_19_1, axiom, !( (Ext_Mem_Acc_19_1) -o (Memory_1 * Active_19 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_13_20, axiom, !( (Memory_20 * Ext_Bus * Queue_13) -o (Ext_Mem_Acc_13_20) ) ).
fof(Begin_Ext_Acc_3_5, axiom, !( (Ext_Bus * Memory_5 * Queue_3) -o (Ext_Mem_Acc_3_5) ) ).
fof(End_Ext_Acc_19_5, axiom, !( (Ext_Mem_Acc_19_5) -o (Memory_5 * Active_19 * Ext_Bus) ) ).
fof(End_Ext_Acc_20_5, axiom, !( (Ext_Mem_Acc_20_5) -o (Memory_5 * Active_20 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_4_11, axiom, !( (Queue_4 * Memory_11 * Ext_Bus) -o (Ext_Mem_Acc_4_11) ) ).
fof(Begin_Ext_Acc_17_18, axiom, !( (Queue_17 * Ext_Bus * Memory_18) -o (Ext_Mem_Acc_17_18) ) ).
fof(End_Ext_Acc_12_4, axiom, !( (Ext_Mem_Acc_12_4) -o (Active_12 * Memory_4 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_6_2, axiom, !( (Ext_Bus * Memory_2 * Queue_6) -o (Ext_Mem_Acc_6_2) ) ).
fof(Begin_Ext_Acc_11_13, axiom, !( (Queue_11 * Memory_13 * Ext_Bus) -o (Ext_Mem_Acc_11_13) ) ).
fof(End_Ext_Acc_13_19, axiom, !( (Ext_Mem_Acc_13_19) -o (Memory_19 * Active_13 * Ext_Bus) ) ).
fof(End_Ext_Acc_1_14, axiom, !( (Ext_Mem_Acc_1_14) -o (Ext_Bus * Active_1 * Memory_14) ) ).
fof(End_Ext_Acc_11_12, axiom, !( (Ext_Mem_Acc_11_12) -o (Memory_12 * Active_11 * Ext_Bus) ) ).
fof(Begin_Own_Acc_3, axiom, !( (Active_3) -o (OwnMemAcc_3) ) ).
fof(End_Ext_Acc_9_15, axiom, !( (Ext_Mem_Acc_9_15) -o (Memory_15 * Active_9 * Ext_Bus) ) ).
fof(Begin_Own_Acc_14, axiom, !( (Active_14) -o (OwnMemAcc_14) ) ).
fof(End_Ext_Acc_6_9, axiom, !( (Ext_Mem_Acc_6_9) -o (Ext_Bus * Memory_9 * Active_6) ) ).
fof(Begin_Ext_Acc_12_16, axiom, !( (Ext_Bus * Memory_16 * Queue_12) -o (Ext_Mem_Acc_12_16) ) ).
fof(End_Ext_Acc_1_9, axiom, !( (Ext_Mem_Acc_1_9) -o (Ext_Bus * Memory_9 * Active_1) ) ).
fof(End_Ext_Acc_15_17, axiom, !( (Ext_Mem_Acc_15_17) -o (Ext_Bus * Memory_17 * Active_15) ) ).
fof(End_Ext_Acc_4_16, axiom, !( (Ext_Mem_Acc_4_16) -o (Ext_Bus * Memory_16 * Active_4) ) ).
fof(End_Ext_Acc_18_4, axiom, !( (Ext_Mem_Acc_18_4) -o (Memory_4 * Active_18 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_19_7, axiom, !( (Ext_Bus * Memory_7 * Queue_19) -o (Ext_Mem_Acc_19_7) ) ).
fof(Begin_Ext_Acc_9_19, axiom, !( (Queue_9 * Memory_19 * Ext_Bus) -o (Ext_Mem_Acc_9_19) ) ).
fof(End_Ext_Acc_9_6, axiom, !( (Ext_Mem_Acc_9_6) -o (Ext_Bus * Memory_6 * Active_9) ) ).
fof(End_Ext_Acc_13_6, axiom, !( (Ext_Mem_Acc_13_6) -o (Ext_Bus * Active_13 * Memory_6) ) ).
fof(End_Ext_Acc_7_11, axiom, !( (Ext_Mem_Acc_7_11) -o (Active_7 * Memory_11 * Ext_Bus) ) ).
fof(Req_Ext_Acc_15, axiom, !( (Active_15) -o (Queue_15) ) ).
fof(End_Ext_Acc_15_13, axiom, !( (Ext_Mem_Acc_15_13) -o (Active_15 * Memory_13 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_4_8, axiom, !( (Queue_4 * Memory_8 * Ext_Bus) -o (Ext_Mem_Acc_4_8) ) ).
fof(Begin_Ext_Acc_6_8, axiom, !( (Queue_6 * Memory_8 * Ext_Bus) -o (Ext_Mem_Acc_6_8) ) ).
fof(Begin_Ext_Acc_5_7, axiom, !( (Memory_7 * Ext_Bus * Queue_5) -o (Ext_Mem_Acc_5_7) ) ).
fof(End_Ext_Acc_8_1, axiom, !( (Ext_Mem_Acc_8_1) -o (Ext_Bus * Active_8 * Memory_1) ) ).
fof(End_Ext_Acc_20_9, axiom, !( (Ext_Mem_Acc_20_9) -o (Active_20 * Memory_9 * Ext_Bus) ) ).
fof(End_Ext_Acc_1_7, axiom, !( (Ext_Mem_Acc_1_7) -o (Active_1 * Memory_7 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_15_16, axiom, !( (Memory_16 * Ext_Bus * Queue_15) -o (Ext_Mem_Acc_15_16) ) ).
fof(End_Ext_Acc_18_20, axiom, !( (Ext_Mem_Acc_18_20) -o (Ext_Bus * Memory_20 * Active_18) ) ).
fof(End_Ext_Acc_18_13, axiom, !( (Ext_Mem_Acc_18_13) -o (Ext_Bus * Memory_13 * Active_18) ) ).
fof(End_Ext_Acc_8_14, axiom, !( (Ext_Mem_Acc_8_14) -o (Active_8 * Memory_14 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_17_8, axiom, !( (Ext_Bus * Memory_8 * Queue_17) -o (Ext_Mem_Acc_17_8) ) ).
fof(End_Own_Acc_2_2, axiom, !( (OwnMemAcc_2 * Memory_2) -o (Active_2 * Memory_2) ) ).
fof(End_Ext_Acc_18_16, axiom, !( (Ext_Mem_Acc_18_16) -o (Ext_Bus * Active_18 * Memory_16) ) ).
fof(End_Ext_Acc_20_17, axiom, !( (Ext_Mem_Acc_20_17) -o (Ext_Bus * Active_20 * Memory_17) ) ).
fof(End_Ext_Acc_13_8, axiom, !( (Ext_Mem_Acc_13_8) -o (Memory_8 * Active_13 * Ext_Bus) ) ).
fof(Begin_Own_Acc_7, axiom, !( (Active_7) -o (OwnMemAcc_7) ) ).
fof(Begin_Ext_Acc_16_19, axiom, !( (Memory_19 * Ext_Bus * Queue_16) -o (Ext_Mem_Acc_16_19) ) ).
fof(End_Ext_Acc_13_10, axiom, !( (Ext_Mem_Acc_13_10) -o (Memory_10 * Active_13 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_5_9, axiom, !( (Memory_9 * Ext_Bus * Queue_5) -o (Ext_Mem_Acc_5_9) ) ).
fof(Begin_Ext_Acc_3_11, axiom, !( (Queue_3 * Memory_11 * Ext_Bus) -o (Ext_Mem_Acc_3_11) ) ).
fof(Begin_Ext_Acc_17_9, axiom, !( (Ext_Bus * Memory_9 * Queue_17) -o (Ext_Mem_Acc_17_9) ) ).
fof(Req_Ext_Acc_7, axiom, !( (Active_7) -o (Queue_7) ) ).
fof(End_Ext_Acc_7_18, axiom, !( (Ext_Mem_Acc_7_18) -o (Active_7 * Memory_18 * Ext_Bus) ) ).
fof(End_Ext_Acc_1_8, axiom, !( (Ext_Mem_Acc_1_8) -o (Ext_Bus * Active_1 * Memory_8) ) ).
fof(Begin_Ext_Acc_14_6, axiom, !( (Queue_14 * Memory_6 * Ext_Bus) -o (Ext_Mem_Acc_14_6) ) ).
fof(End_Ext_Acc_8_18, axiom, !( (Ext_Mem_Acc_8_18) -o (Active_8 * Memory_18 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_14_15, axiom, !( (Ext_Bus * Memory_15 * Queue_14) -o (Ext_Mem_Acc_14_15) ) ).
fof(Begin_Own_Acc_2, axiom, !( (Active_2) -o (OwnMemAcc_2) ) ).
fof(End_Ext_Acc_9_5, axiom, !( (Ext_Mem_Acc_9_5) -o (Active_9 * Memory_5 * Ext_Bus) ) ).
fof(End_Ext_Acc_14_18, axiom, !( (Ext_Mem_Acc_14_18) -o (Ext_Bus * Active_14 * Memory_18) ) ).
fof(Begin_Ext_Acc_6_19, axiom, !( (Queue_6 * Memory_19 * Ext_Bus) -o (Ext_Mem_Acc_6_19) ) ).
fof(End_Own_Acc_13_13, axiom, !( (OwnMemAcc_13 * Memory_13) -o (Active_13 * Memory_13) ) ).
fof(Begin_Ext_Acc_4_16, axiom, !( (Queue_4 * Ext_Bus * Memory_16) -o (Ext_Mem_Acc_4_16) ) ).
fof(End_Ext_Acc_14_4, axiom, !( (Ext_Mem_Acc_14_4) -o (Active_14 * Memory_4 * Ext_Bus) ) ).
fof(End_Ext_Acc_2_19, axiom, !( (Ext_Mem_Acc_2_19) -o (Active_2 * Memory_19 * Ext_Bus) ) ).
fof(End_Own_Acc_15_15, axiom, !( (Memory_15 * OwnMemAcc_15) -o (Memory_15 * Active_15) ) ).
fof(End_Own_Acc_1_1, axiom, !( (Memory_1 * OwnMemAcc_1) -o (Memory_1 * Active_1) ) ).
fof(Begin_Ext_Acc_5_14, axiom, !( (Queue_5 * Ext_Bus * Memory_14) -o (Ext_Mem_Acc_5_14) ) ).
fof(End_Ext_Acc_11_19, axiom, !( (Ext_Mem_Acc_11_19) -o (Memory_19 * Active_11 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_9_2, axiom, !( (Ext_Bus * Memory_2 * Queue_9) -o (Ext_Mem_Acc_9_2) ) ).
fof(Begin_Ext_Acc_18_17, axiom, !( (Queue_18 * Memory_17 * Ext_Bus) -o (Ext_Mem_Acc_18_17) ) ).
fof(End_Ext_Acc_12_19, axiom, !( (Ext_Mem_Acc_12_19) -o (Memory_19 * Active_12 * Ext_Bus) ) ).
fof(End_Ext_Acc_8_2, axiom, !( (Ext_Mem_Acc_8_2) -o (Ext_Bus * Memory_2 * Active_8) ) ).
fof(End_Ext_Acc_10_13, axiom, !( (Ext_Mem_Acc_10_13) -o (Memory_13 * Active_10 * Ext_Bus) ) ).
fof(End_Ext_Acc_1_18, axiom, !( (Ext_Mem_Acc_1_18) -o (Memory_18 * Active_1 * Ext_Bus) ) ).
fof(End_Ext_Acc_11_6, axiom, !( (Ext_Mem_Acc_11_6) -o (Ext_Bus * Active_11 * Memory_6) ) ).
fof(Begin_Ext_Acc_17_2, axiom, !( (Queue_17 * Ext_Bus * Memory_2) -o (Ext_Mem_Acc_17_2) ) ).
fof(End_Ext_Acc_12_13, axiom, !( (Ext_Mem_Acc_12_13) -o (Active_12 * Memory_13 * Ext_Bus) ) ).
fof(End_Ext_Acc_16_7, axiom, !( (Ext_Mem_Acc_16_7) -o (Memory_7 * Active_16 * Ext_Bus) ) ).
fof(End_Ext_Acc_10_19, axiom, !( (Ext_Mem_Acc_10_19) -o (Memory_19 * Active_10 * Ext_Bus) ) ).
fof(End_Own_Acc_4_4, axiom, !( (OwnMemAcc_4 * Memory_4) -o (Active_4 * Memory_4) ) ).
fof(End_Ext_Acc_19_20, axiom, !( (Ext_Mem_Acc_19_20) -o (Memory_20 * Active_19 * Ext_Bus) ) ).
fof(End_Ext_Acc_14_11, axiom, !( (Ext_Mem_Acc_14_11) -o (Memory_11 * Active_14 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_12_10, axiom, !( (Queue_12 * Memory_10 * Ext_Bus) -o (Ext_Mem_Acc_12_10) ) ).
fof(Begin_Ext_Acc_2_9, axiom, !( (Ext_Bus * Memory_9 * Queue_2) -o (Ext_Mem_Acc_2_9) ) ).
fof(Begin_Ext_Acc_4_12, axiom, !( (Queue_4 * Ext_Bus * Memory_12) -o (Ext_Mem_Acc_4_12) ) ).
fof(Begin_Ext_Acc_7_8, axiom, !( (Queue_7 * Ext_Bus * Memory_8) -o (Ext_Mem_Acc_7_8) ) ).
fof(Begin_Ext_Acc_17_5, axiom, !( (Queue_17 * Memory_5 * Ext_Bus) -o (Ext_Mem_Acc_17_5) ) ).
fof(Begin_Ext_Acc_18_12, axiom, !( (Ext_Bus * Memory_12 * Queue_18) -o (Ext_Mem_Acc_18_12) ) ).
fof(Begin_Ext_Acc_14_10, axiom, !( (Memory_10 * Ext_Bus * Queue_14) -o (Ext_Mem_Acc_14_10) ) ).
fof(End_Ext_Acc_18_6, axiom, !( (Ext_Mem_Acc_18_6) -o (Active_18 * Memory_6 * Ext_Bus) ) ).
fof(End_Ext_Acc_12_17, axiom, !( (Ext_Mem_Acc_12_17) -o (Ext_Bus * Memory_17 * Active_12) ) ).
fof(Begin_Ext_Acc_2_13, axiom, !( (Memory_13 * Ext_Bus * Queue_2) -o (Ext_Mem_Acc_2_13) ) ).
fof(Begin_Ext_Acc_8_6, axiom, !( (Memory_6 * Ext_Bus * Queue_8) -o (Ext_Mem_Acc_8_6) ) ).
fof(End_Ext_Acc_2_6, axiom, !( (Ext_Mem_Acc_2_6) -o (Active_2 * Memory_6 * Ext_Bus) ) ).
fof(End_Ext_Acc_8_20, axiom, !( (Ext_Mem_Acc_8_20) -o (Memory_20 * Active_8 * Ext_Bus) ) ).
fof(End_Ext_Acc_15_20, axiom, !( (Ext_Mem_Acc_15_20) -o (Ext_Bus * Memory_20 * Active_15) ) ).
fof(Begin_Ext_Acc_13_6, axiom, !( (Queue_13 * Ext_Bus * Memory_6) -o (Ext_Mem_Acc_13_6) ) ).
fof(End_Ext_Acc_13_17, axiom, !( (Ext_Mem_Acc_13_17) -o (Ext_Bus * Memory_17 * Active_13) ) ).
fof(End_Ext_Acc_7_6, axiom, !( (Ext_Mem_Acc_7_6) -o (Ext_Bus * Memory_6 * Active_7) ) ).
fof(Req_Ext_Acc_10, axiom, !( (Active_10) -o (Queue_10) ) ).
fof(Begin_Ext_Acc_9_11, axiom, !( (Queue_9 * Ext_Bus * Memory_11) -o (Ext_Mem_Acc_9_11) ) ).
fof(Begin_Ext_Acc_17_1, axiom, !( (Memory_1 * Ext_Bus * Queue_17) -o (Ext_Mem_Acc_17_1) ) ).
fof(End_Ext_Acc_15_1, axiom, !( (Ext_Mem_Acc_15_1) -o (Active_15 * Memory_1 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_19_15, axiom, !( (Memory_15 * Ext_Bus * Queue_19) -o (Ext_Mem_Acc_19_15) ) ).
fof(End_Ext_Acc_1_16, axiom, !( (Ext_Mem_Acc_1_16) -o (Ext_Bus * Active_1 * Memory_16) ) ).
fof(End_Ext_Acc_9_3, axiom, !( (Ext_Mem_Acc_9_3) -o (Ext_Bus * Memory_3 * Active_9) ) ).
fof(End_Ext_Acc_15_4, axiom, !( (Ext_Mem_Acc_15_4) -o (Active_15 * Memory_4 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_4_15, axiom, !( (Queue_4 * Ext_Bus * Memory_15) -o (Ext_Mem_Acc_4_15) ) ).
fof(Begin_Ext_Acc_18_10, axiom, !( (Ext_Bus * Memory_10 * Queue_18) -o (Ext_Mem_Acc_18_10) ) ).
fof(End_Ext_Acc_8_19, axiom, !( (Ext_Mem_Acc_8_19) -o (Active_8 * Memory_19 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_12_13, axiom, !( (Ext_Bus * Memory_13 * Queue_12) -o (Ext_Mem_Acc_12_13) ) ).
fof(Begin_Ext_Acc_12_15, axiom, !( (Ext_Bus * Memory_15 * Queue_12) -o (Ext_Mem_Acc_12_15) ) ).
fof(End_Ext_Acc_14_9, axiom, !( (Ext_Mem_Acc_14_9) -o (Memory_9 * Active_14 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_19_4, axiom, !( (Memory_4 * Ext_Bus * Queue_19) -o (Ext_Mem_Acc_19_4) ) ).
fof(End_Ext_Acc_5_17, axiom, !( (Ext_Mem_Acc_5_17) -o (Active_5 * Memory_17 * Ext_Bus) ) ).
fof(End_Ext_Acc_2_4, axiom, !( (Ext_Mem_Acc_2_4) -o (Active_2 * Memory_4 * Ext_Bus) ) ).
fof(End_Ext_Acc_6_3, axiom, !( (Ext_Mem_Acc_6_3) -o (Active_6 * Memory_3 * Ext_Bus) ) ).
fof(End_Ext_Acc_14_19, axiom, !( (Ext_Mem_Acc_14_19) -o (Ext_Bus * Active_14 * Memory_19) ) ).
fof(Begin_Ext_Acc_5_4, axiom, !( (Ext_Bus * Memory_4 * Queue_5) -o (Ext_Mem_Acc_5_4) ) ).
fof(Begin_Ext_Acc_1_4, axiom, !( (Memory_4 * Ext_Bus * Queue_1) -o (Ext_Mem_Acc_1_4) ) ).
fof(Begin_Ext_Acc_17_14, axiom, !( (Ext_Bus * Memory_14 * Queue_17) -o (Ext_Mem_Acc_17_14) ) ).
fof(Begin_Ext_Acc_17_4, axiom, !( (Memory_4 * Ext_Bus * Queue_17) -o (Ext_Mem_Acc_17_4) ) ).
fof(End_Ext_Acc_11_20, axiom, !( (Ext_Mem_Acc_11_20) -o (Ext_Bus * Active_11 * Memory_20) ) ).
fof(Begin_Ext_Acc_20_10, axiom, !( (Ext_Bus * Memory_10 * Queue_20) -o (Ext_Mem_Acc_20_10) ) ).
fof(End_Ext_Acc_4_17, axiom, !( (Ext_Mem_Acc_4_17) -o (Active_4 * Memory_17 * Ext_Bus) ) ).
fof(End_Ext_Acc_7_2, axiom, !( (Ext_Mem_Acc_7_2) -o (Ext_Bus * Memory_2 * Active_7) ) ).
fof(Begin_Ext_Acc_4_3, axiom, !( (Ext_Bus * Memory_3 * Queue_4) -o (Ext_Mem_Acc_4_3) ) ).
fof(Begin_Ext_Acc_12_8, axiom, !( (Memory_8 * Ext_Bus * Queue_12) -o (Ext_Mem_Acc_12_8) ) ).
fof(Begin_Ext_Acc_10_5, axiom, !( (Queue_10 * Ext_Bus * Memory_5) -o (Ext_Mem_Acc_10_5) ) ).
fof(Begin_Ext_Acc_11_2, axiom, !( (Memory_2 * Ext_Bus * Queue_11) -o (Ext_Mem_Acc_11_2) ) ).
fof(End_Ext_Acc_17_20, axiom, !( (Ext_Mem_Acc_17_20) -o (Ext_Bus * Memory_20 * Active_17) ) ).
fof(Begin_Ext_Acc_13_7, axiom, !( (Queue_13 * Ext_Bus * Memory_7) -o (Ext_Mem_Acc_13_7) ) ).
fof(Begin_Ext_Acc_18_5, axiom, !( (Queue_18 * Memory_5 * Ext_Bus) -o (Ext_Mem_Acc_18_5) ) ).
fof(Begin_Ext_Acc_18_1, axiom, !( (Memory_1 * Ext_Bus * Queue_18) -o (Ext_Mem_Acc_18_1) ) ).
fof(End_Ext_Acc_16_5, axiom, !( (Ext_Mem_Acc_16_5) -o (Memory_5 * Active_16 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_13_19, axiom, !( (Ext_Bus * Memory_19 * Queue_13) -o (Ext_Mem_Acc_13_19) ) ).
fof(End_Ext_Acc_3_19, axiom, !( (Ext_Mem_Acc_3_19) -o (Active_3 * Memory_19 * Ext_Bus) ) ).
fof(End_Ext_Acc_10_14, axiom, !( (Ext_Mem_Acc_10_14) -o (Memory_14 * Active_10 * Ext_Bus) ) ).
fof(End_Ext_Acc_3_11, axiom, !( (Ext_Mem_Acc_3_11) -o (Ext_Bus * Memory_11 * Active_3) ) ).
fof(Begin_Ext_Acc_15_4, axiom, !( (Queue_15 * Ext_Bus * Memory_4) -o (Ext_Mem_Acc_15_4) ) ).
fof(End_Ext_Acc_4_7, axiom, !( (Ext_Mem_Acc_4_7) -o (Ext_Bus * Memory_7 * Active_4) ) ).
fof(End_Ext_Acc_6_20, axiom, !( (Ext_Mem_Acc_6_20) -o (Active_6 * Memory_20 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_20_15, axiom, !( (Memory_15 * Ext_Bus * Queue_20) -o (Ext_Mem_Acc_20_15) ) ).
fof(Begin_Ext_Acc_10_14, axiom, !( (Memory_14 * Ext_Bus * Queue_10) -o (Ext_Mem_Acc_10_14) ) ).
fof(Begin_Ext_Acc_9_12, axiom, !( (Queue_9 * Ext_Bus * Memory_12) -o (Ext_Mem_Acc_9_12) ) ).
fof(Begin_Ext_Acc_2_18, axiom, !( (Queue_2 * Ext_Bus * Memory_18) -o (Ext_Mem_Acc_2_18) ) ).
fof(End_Ext_Acc_3_1, axiom, !( (Ext_Mem_Acc_3_1) -o (Memory_1 * Active_3 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_14_9, axiom, !( (Queue_14 * Memory_9 * Ext_Bus) -o (Ext_Mem_Acc_14_9) ) ).
fof(Begin_Ext_Acc_8_9, axiom, !( (Queue_8 * Ext_Bus * Memory_9) -o (Ext_Mem_Acc_8_9) ) ).
fof(Begin_Ext_Acc_2_20, axiom, !( (Queue_2 * Ext_Bus * Memory_20) -o (Ext_Mem_Acc_2_20) ) ).
fof(Begin_Ext_Acc_11_6, axiom, !( (Queue_11 * Ext_Bus * Memory_6) -o (Ext_Mem_Acc_11_6) ) ).
fof(Begin_Ext_Acc_10_18, axiom, !( (Ext_Bus * Memory_18 * Queue_10) -o (Ext_Mem_Acc_10_18) ) ).
fof(Begin_Ext_Acc_17_12, axiom, !( (Ext_Bus * Memory_12 * Queue_17) -o (Ext_Mem_Acc_17_12) ) ).
fof(Begin_Ext_Acc_5_10, axiom, !( (Queue_5 * Ext_Bus * Memory_10) -o (Ext_Mem_Acc_5_10) ) ).
fof(Begin_Ext_Acc_8_11, axiom, !( (Queue_8 * Ext_Bus * Memory_11) -o (Ext_Mem_Acc_8_11) ) ).
fof(Begin_Ext_Acc_16_7, axiom, !( (Memory_7 * Ext_Bus * Queue_16) -o (Ext_Mem_Acc_16_7) ) ).
fof(Begin_Ext_Acc_4_20, axiom, !( (Queue_4 * Memory_20 * Ext_Bus) -o (Ext_Mem_Acc_4_20) ) ).
fof(Begin_Ext_Acc_1_7, axiom, !( (Ext_Bus * Memory_7 * Queue_1) -o (Ext_Mem_Acc_1_7) ) ).
fof(End_Ext_Acc_9_19, axiom, !( (Ext_Mem_Acc_9_19) -o (Active_9 * Memory_19 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_11_10, axiom, !( (Queue_11 * Memory_10 * Ext_Bus) -o (Ext_Mem_Acc_11_10) ) ).
fof(Begin_Ext_Acc_2_7, axiom, !( (Memory_7 * Ext_Bus * Queue_2) -o (Ext_Mem_Acc_2_7) ) ).
fof(End_Ext_Acc_13_15, axiom, !( (Ext_Mem_Acc_13_15) -o (Ext_Bus * Active_13 * Memory_15) ) ).
fof(Begin_Ext_Acc_14_17, axiom, !( (Ext_Bus * Memory_17 * Queue_14) -o (Ext_Mem_Acc_14_17) ) ).
fof(Begin_Ext_Acc_10_17, axiom, !( (Memory_17 * Ext_Bus * Queue_10) -o (Ext_Mem_Acc_10_17) ) ).
fof(Begin_Ext_Acc_10_3, axiom, !( (Memory_3 * Ext_Bus * Queue_10) -o (Ext_Mem_Acc_10_3) ) ).
fof(Begin_Ext_Acc_3_6, axiom, !( (Ext_Bus * Memory_6 * Queue_3) -o (Ext_Mem_Acc_3_6) ) ).
fof(End_Ext_Acc_9_12, axiom, !( (Ext_Mem_Acc_9_12) -o (Memory_12 * Active_9 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_1_5, axiom, !( (Ext_Bus * Memory_5 * Queue_1) -o (Ext_Mem_Acc_1_5) ) ).
fof(End_Ext_Acc_20_3, axiom, !( (Ext_Mem_Acc_20_3) -o (Active_20 * Memory_3 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_16_9, axiom, !( (Queue_16 * Memory_9 * Ext_Bus) -o (Ext_Mem_Acc_16_9) ) ).
fof(End_Ext_Acc_1_17, axiom, !( (Ext_Mem_Acc_1_17) -o (Ext_Bus * Memory_17 * Active_1) ) ).
fof(Begin_Ext_Acc_1_16, axiom, !( (Memory_16 * Ext_Bus * Queue_1) -o (Ext_Mem_Acc_1_16) ) ).
fof(End_Own_Acc_14_14, axiom, !( (Memory_14 * OwnMemAcc_14) -o (Memory_14 * Active_14) ) ).
fof(Begin_Ext_Acc_1_3, axiom, !( (Queue_1 * Memory_3 * Ext_Bus) -o (Ext_Mem_Acc_1_3) ) ).
fof(End_Ext_Acc_10_7, axiom, !( (Ext_Mem_Acc_10_7) -o (Ext_Bus * Active_10 * Memory_7) ) ).
fof(Begin_Ext_Acc_18_9, axiom, !( (Ext_Bus * Memory_9 * Queue_18) -o (Ext_Mem_Acc_18_9) ) ).
fof(End_Ext_Acc_5_8, axiom, !( (Ext_Mem_Acc_5_8) -o (Ext_Bus * Memory_8 * Active_5) ) ).
fof(Begin_Ext_Acc_6_15, axiom, !( (Memory_15 * Ext_Bus * Queue_6) -o (Ext_Mem_Acc_6_15) ) ).
fof(Begin_Ext_Acc_20_11, axiom, !( (Queue_20 * Memory_11 * Ext_Bus) -o (Ext_Mem_Acc_20_11) ) ).
fof(Begin_Ext_Acc_8_18, axiom, !( (Memory_18 * Ext_Bus * Queue_8) -o (Ext_Mem_Acc_8_18) ) ).
fof(End_Ext_Acc_19_9, axiom, !( (Ext_Mem_Acc_19_9) -o (Active_19 * Memory_9 * Ext_Bus) ) ).
fof(End_Ext_Acc_20_7, axiom, !( (Ext_Mem_Acc_20_7) -o (Ext_Bus * Active_20 * Memory_7) ) ).
fof(End_Ext_Acc_1_10, axiom, !( (Ext_Mem_Acc_1_10) -o (Ext_Bus * Memory_10 * Active_1) ) ).
fof(Begin_Ext_Acc_13_15, axiom, !( (Ext_Bus * Memory_15 * Queue_13) -o (Ext_Mem_Acc_13_15) ) ).
fof(End_Ext_Acc_13_3, axiom, !( (Ext_Mem_Acc_13_3) -o (Ext_Bus * Active_13 * Memory_3) ) ).
fof(End_Ext_Acc_18_5, axiom, !( (Ext_Mem_Acc_18_5) -o (Memory_5 * Active_18 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_15_1, axiom, !( (Queue_15 * Ext_Bus * Memory_1) -o (Ext_Mem_Acc_15_1) ) ).
fof(Begin_Ext_Acc_11_14, axiom, !( (Memory_14 * Ext_Bus * Queue_11) -o (Ext_Mem_Acc_11_14) ) ).
fof(End_Ext_Acc_5_19, axiom, !( (Ext_Mem_Acc_5_19) -o (Active_5 * Memory_19 * Ext_Bus) ) ).
fof(End_Ext_Acc_16_13, axiom, !( (Ext_Mem_Acc_16_13) -o (Active_16 * Memory_13 * Ext_Bus) ) ).
fof(End_Ext_Acc_7_16, axiom, !( (Ext_Mem_Acc_7_16) -o (Active_7 * Memory_16 * Ext_Bus) ) ).
fof(End_Own_Acc_20_20, axiom, !( (OwnMemAcc_20 * Memory_20) -o (Active_20 * Memory_20) ) ).
fof(End_Ext_Acc_3_12, axiom, !( (Ext_Mem_Acc_3_12) -o (Active_3 * Memory_12 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_19_2, axiom, !( (Queue_19 * Memory_2 * Ext_Bus) -o (Ext_Mem_Acc_19_2) ) ).
fof(End_Own_Acc_17_17, axiom, !( (Memory_17 * OwnMemAcc_17) -o (Memory_17 * Active_17) ) ).
fof(End_Ext_Acc_5_20, axiom, !( (Ext_Mem_Acc_5_20) -o (Active_5 * Memory_20 * Ext_Bus) ) ).
fof(End_Ext_Acc_1_2, axiom, !( (Ext_Mem_Acc_1_2) -o (Ext_Bus * Active_1 * Memory_2) ) ).
fof(End_Ext_Acc_11_9, axiom, !( (Ext_Mem_Acc_11_9) -o (Ext_Bus * Active_11 * Memory_9) ) ).
fof(End_Ext_Acc_19_7, axiom, !( (Ext_Mem_Acc_19_7) -o (Ext_Bus * Active_19 * Memory_7) ) ).
fof(Begin_Ext_Acc_8_17, axiom, !( (Memory_17 * Ext_Bus * Queue_8) -o (Ext_Mem_Acc_8_17) ) ).
fof(Begin_Ext_Acc_8_14, axiom, !( (Queue_8 * Ext_Bus * Memory_14) -o (Ext_Mem_Acc_8_14) ) ).
fof(End_Ext_Acc_17_10, axiom, !( (Ext_Mem_Acc_17_10) -o (Active_17 * Memory_10 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_6_1, axiom, !( (Ext_Bus * Memory_1 * Queue_6) -o (Ext_Mem_Acc_6_1) ) ).
fof(Begin_Ext_Acc_10_7, axiom, !( (Queue_10 * Memory_7 * Ext_Bus) -o (Ext_Mem_Acc_10_7) ) ).
fof(End_Ext_Acc_14_7, axiom, !( (Ext_Mem_Acc_14_7) -o (Active_14 * Memory_7 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_11_8, axiom, !( (Queue_11 * Ext_Bus * Memory_8) -o (Ext_Mem_Acc_11_8) ) ).
fof(Begin_Ext_Acc_7_10, axiom, !( (Queue_7 * Ext_Bus * Memory_10) -o (Ext_Mem_Acc_7_10) ) ).
fof(Begin_Ext_Acc_11_4, axiom, !( (Queue_11 * Memory_4 * Ext_Bus) -o (Ext_Mem_Acc_11_4) ) ).
fof(End_Ext_Acc_3_16, axiom, !( (Ext_Mem_Acc_3_16) -o (Ext_Bus * Memory_16 * Active_3) ) ).
fof(End_Ext_Acc_19_3, axiom, !( (Ext_Mem_Acc_19_3) -o (Active_19 * Memory_3 * Ext_Bus) ) ).
fof(Req_Ext_Acc_17, axiom, !( (Active_17) -o (Queue_17) ) ).
fof(End_Ext_Acc_3_15, axiom, !( (Ext_Mem_Acc_3_15) -o (Active_3 * Memory_15 * Ext_Bus) ) ).
fof(End_Ext_Acc_19_15, axiom, !( (Ext_Mem_Acc_19_15) -o (Ext_Bus * Active_19 * Memory_15) ) ).
fof(Begin_Ext_Acc_5_16, axiom, !( (Queue_5 * Ext_Bus * Memory_16) -o (Ext_Mem_Acc_5_16) ) ).
fof(End_Ext_Acc_2_11, axiom, !( (Ext_Mem_Acc_2_11) -o (Ext_Bus * Memory_11 * Active_2) ) ).
fof(Begin_Ext_Acc_8_19, axiom, !( (Queue_8 * Memory_19 * Ext_Bus) -o (Ext_Mem_Acc_8_19) ) ).
fof(Begin_Ext_Acc_9_6, axiom, !( (Memory_6 * Ext_Bus * Queue_9) -o (Ext_Mem_Acc_9_6) ) ).
fof(Begin_Ext_Acc_3_4, axiom, !( (Ext_Bus * Memory_4 * Queue_3) -o (Ext_Mem_Acc_3_4) ) ).
fof(End_Ext_Acc_8_11, axiom, !( (Ext_Mem_Acc_8_11) -o (Active_8 * Memory_11 * Ext_Bus) ) ).
fof(End_Ext_Acc_20_12, axiom, !( (Ext_Mem_Acc_20_12) -o (Ext_Bus * Memory_12 * Active_20) ) ).
fof(End_Ext_Acc_12_9, axiom, !( (Ext_Mem_Acc_12_9) -o (Ext_Bus * Active_12 * Memory_9) ) ).
fof(End_Ext_Acc_2_17, axiom, !( (Ext_Mem_Acc_2_17) -o (Ext_Bus * Memory_17 * Active_2) ) ).
fof(Begin_Ext_Acc_9_15, axiom, !( (Memory_15 * Ext_Bus * Queue_9) -o (Ext_Mem_Acc_9_15) ) ).
fof(End_Ext_Acc_1_13, axiom, !( (Ext_Mem_Acc_1_13) -o (Ext_Bus * Memory_13 * Active_1) ) ).
fof(Req_Ext_Acc_16, axiom, !( (Active_16) -o (Queue_16) ) ).
fof(End_Ext_Acc_9_2, axiom, !( (Ext_Mem_Acc_9_2) -o (Ext_Bus * Memory_2 * Active_9) ) ).
fof(Begin_Ext_Acc_17_10, axiom, !( (Memory_10 * Ext_Bus * Queue_17) -o (Ext_Mem_Acc_17_10) ) ).
fof(Begin_Ext_Acc_18_20, axiom, !( (Queue_18 * Memory_20 * Ext_Bus) -o (Ext_Mem_Acc_18_20) ) ).
fof(End_Ext_Acc_5_11, axiom, !( (Ext_Mem_Acc_5_11) -o (Ext_Bus * Memory_11 * Active_5) ) ).
fof(End_Ext_Acc_15_3, axiom, !( (Ext_Mem_Acc_15_3) -o (Memory_3 * Active_15 * Ext_Bus) ) ).
fof(End_Ext_Acc_5_7, axiom, !( (Ext_Mem_Acc_5_7) -o (Ext_Bus * Memory_7 * Active_5) ) ).
fof(End_Ext_Acc_10_4, axiom, !( (Ext_Mem_Acc_10_4) -o (Ext_Bus * Memory_4 * Active_10) ) ).
fof(Begin_Ext_Acc_19_3, axiom, !( (Memory_3 * Ext_Bus * Queue_19) -o (Ext_Mem_Acc_19_3) ) ).
fof(End_Ext_Acc_12_16, axiom, !( (Ext_Mem_Acc_12_16) -o (Memory_16 * Active_12 * Ext_Bus) ) ).
fof(End_Ext_Acc_1_20, axiom, !( (Ext_Mem_Acc_1_20) -o (Ext_Bus * Memory_20 * Active_1) ) ).
fof(Begin_Ext_Acc_3_16, axiom, !( (Queue_3 * Ext_Bus * Memory_16) -o (Ext_Mem_Acc_3_16) ) ).
fof(Begin_Ext_Acc_15_3, axiom, !( (Queue_15 * Memory_3 * Ext_Bus) -o (Ext_Mem_Acc_15_3) ) ).
fof(Begin_Ext_Acc_3_2, axiom, !( (Ext_Bus * Memory_2 * Queue_3) -o (Ext_Mem_Acc_3_2) ) ).
fof(Begin_Ext_Acc_4_18, axiom, !( (Queue_4 * Ext_Bus * Memory_18) -o (Ext_Mem_Acc_4_18) ) ).
fof(Begin_Ext_Acc_6_4, axiom, !( (Ext_Bus * Memory_4 * Queue_6) -o (Ext_Mem_Acc_6_4) ) ).
fof(End_Ext_Acc_19_4, axiom, !( (Ext_Mem_Acc_19_4) -o (Memory_4 * Active_19 * Ext_Bus) ) ).
fof(End_Ext_Acc_10_5, axiom, !( (Ext_Mem_Acc_10_5) -o (Active_10 * Memory_5 * Ext_Bus) ) ).
fof(Req_Ext_Acc_11, axiom, !( (Active_11) -o (Queue_11) ) ).
fof(End_Ext_Acc_17_19, axiom, !( (Ext_Mem_Acc_17_19) -o (Ext_Bus * Active_17 * Memory_19) ) ).
fof(Begin_Ext_Acc_10_15, axiom, !( (Ext_Bus * Memory_15 * Queue_10) -o (Ext_Mem_Acc_10_15) ) ).
fof(Begin_Ext_Acc_4_19, axiom, !( (Queue_4 * Ext_Bus * Memory_19) -o (Ext_Mem_Acc_4_19) ) ).
fof(End_Ext_Acc_8_10, axiom, !( (Ext_Mem_Acc_8_10) -o (Ext_Bus * Active_8 * Memory_10) ) ).
fof(End_Ext_Acc_1_3, axiom, !( (Ext_Mem_Acc_1_3) -o (Memory_3 * Active_1 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_20_3, axiom, !( (Memory_3 * Ext_Bus * Queue_20) -o (Ext_Mem_Acc_20_3) ) ).
fof(Begin_Ext_Acc_13_2, axiom, !( (Memory_2 * Ext_Bus * Queue_13) -o (Ext_Mem_Acc_13_2) ) ).
fof(End_Ext_Acc_2_7, axiom, !( (Ext_Mem_Acc_2_7) -o (Ext_Bus * Memory_7 * Active_2) ) ).
fof(Begin_Ext_Acc_2_6, axiom, !( (Ext_Bus * Memory_6 * Queue_2) -o (Ext_Mem_Acc_2_6) ) ).
fof(Begin_Ext_Acc_7_17, axiom, !( (Queue_7 * Memory_17 * Ext_Bus) -o (Ext_Mem_Acc_7_17) ) ).
fof(End_Ext_Acc_6_13, axiom, !( (Ext_Mem_Acc_6_13) -o (Ext_Bus * Active_6 * Memory_13) ) ).
fof(End_Ext_Acc_6_4, axiom, !( (Ext_Mem_Acc_6_4) -o (Ext_Bus * Active_6 * Memory_4) ) ).
fof(End_Ext_Acc_12_14, axiom, !( (Ext_Mem_Acc_12_14) -o (Memory_14 * Active_12 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_15_13, axiom, !( (Ext_Bus * Memory_13 * Queue_15) -o (Ext_Mem_Acc_15_13) ) ).
fof(Begin_Ext_Acc_18_13, axiom, !( (Memory_13 * Ext_Bus * Queue_18) -o (Ext_Mem_Acc_18_13) ) ).
fof(Begin_Ext_Acc_15_6, axiom, !( (Queue_15 * Memory_6 * Ext_Bus) -o (Ext_Mem_Acc_15_6) ) ).
fof(End_Ext_Acc_19_2, axiom, !( (Ext_Mem_Acc_19_2) -o (Memory_2 * Active_19 * Ext_Bus) ) ).
fof(End_Ext_Acc_9_16, axiom, !( (Ext_Mem_Acc_9_16) -o (Active_9 * Memory_16 * Ext_Bus) ) ).
fof(End_Ext_Acc_8_16, axiom, !( (Ext_Mem_Acc_8_16) -o (Active_8 * Memory_16 * Ext_Bus) ) ).
fof(Begin_Own_Acc_11, axiom, !( (Active_11) -o (OwnMemAcc_11) ) ).
fof(Begin_Ext_Acc_12_5, axiom, !( (Queue_12 * Ext_Bus * Memory_5) -o (Ext_Mem_Acc_12_5) ) ).
fof(End_Ext_Acc_3_9, axiom, !( (Ext_Mem_Acc_3_9) -o (Ext_Bus * Memory_9 * Active_3) ) ).
fof(Begin_Ext_Acc_3_18, axiom, !( (Queue_3 * Ext_Bus * Memory_18) -o (Ext_Mem_Acc_3_18) ) ).
fof(End_Own_Acc_10_10, axiom, !( (OwnMemAcc_10 * Memory_10) -o (Active_10 * Memory_10) ) ).
fof(Begin_Ext_Acc_3_15, axiom, !( (Queue_3 * Ext_Bus * Memory_15) -o (Ext_Mem_Acc_3_15) ) ).
fof(Begin_Ext_Acc_7_4, axiom, !( (Ext_Bus * Memory_4 * Queue_7) -o (Ext_Mem_Acc_7_4) ) ).
fof(Begin_Ext_Acc_15_9, axiom, !( (Queue_15 * Memory_9 * Ext_Bus) -o (Ext_Mem_Acc_15_9) ) ).
fof(Begin_Ext_Acc_19_13, axiom, !( (Memory_13 * Ext_Bus * Queue_19) -o (Ext_Mem_Acc_19_13) ) ).
fof(End_Own_Acc_3_3, axiom, !( (OwnMemAcc_3 * Memory_3) -o (Active_3 * Memory_3) ) ).
fof(End_Ext_Acc_11_18, axiom, !( (Ext_Mem_Acc_11_18) -o (Ext_Bus * Memory_18 * Active_11) ) ).
fof(Begin_Ext_Acc_13_4, axiom, !( (Queue_13 * Ext_Bus * Memory_4) -o (Ext_Mem_Acc_13_4) ) ).
fof(End_Ext_Acc_20_8, axiom, !( (Ext_Mem_Acc_20_8) -o (Ext_Bus * Memory_8 * Active_20) ) ).
fof(End_Ext_Acc_5_9, axiom, !( (Ext_Mem_Acc_5_9) -o (Ext_Bus * Memory_9 * Active_5) ) ).
fof(End_Ext_Acc_6_17, axiom, !( (Ext_Mem_Acc_6_17) -o (Active_6 * Memory_17 * Ext_Bus) ) ).
fof(End_Ext_Acc_19_11, axiom, !( (Ext_Mem_Acc_19_11) -o (Ext_Bus * Memory_11 * Active_19) ) ).
fof(Begin_Ext_Acc_2_15, axiom, !( (Queue_2 * Ext_Bus * Memory_15) -o (Ext_Mem_Acc_2_15) ) ).
fof(End_Ext_Acc_16_3, axiom, !( (Ext_Mem_Acc_16_3) -o (Memory_3 * Active_16 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_15_20, axiom, !( (Queue_15 * Memory_20 * Ext_Bus) -o (Ext_Mem_Acc_15_20) ) ).
fof(End_Ext_Acc_11_13, axiom, !( (Ext_Mem_Acc_11_13) -o (Memory_13 * Active_11 * Ext_Bus) ) ).
fof(End_Ext_Acc_4_5, axiom, !( (Ext_Mem_Acc_4_5) -o (Ext_Bus * Memory_5 * Active_4) ) ).
fof(Begin_Ext_Acc_20_4, axiom, !( (Ext_Bus * Memory_4 * Queue_20) -o (Ext_Mem_Acc_20_4) ) ).
fof(Begin_Ext_Acc_13_10, axiom, !( (Queue_13 * Memory_10 * Ext_Bus) -o (Ext_Mem_Acc_13_10) ) ).
fof(Begin_Ext_Acc_11_9, axiom, !( (Queue_11 * Ext_Bus * Memory_9) -o (Ext_Mem_Acc_11_9) ) ).
fof(End_Ext_Acc_2_13, axiom, !( (Ext_Mem_Acc_2_13) -o (Ext_Bus * Memory_13 * Active_2) ) ).
fof(Begin_Ext_Acc_11_15, axiom, !( (Ext_Bus * Memory_15 * Queue_11) -o (Ext_Mem_Acc_11_15) ) ).
fof(Begin_Ext_Acc_6_12, axiom, !( (Queue_6 * Ext_Bus * Memory_12) -o (Ext_Mem_Acc_6_12) ) ).
fof(Begin_Ext_Acc_16_1, axiom, !( (Queue_16 * Ext_Bus * Memory_1) -o (Ext_Mem_Acc_16_1) ) ).
fof(End_Ext_Acc_11_1, axiom, !( (Ext_Mem_Acc_11_1) -o (Ext_Bus * Memory_1 * Active_11) ) ).
fof(Begin_Ext_Acc_6_14, axiom, !( (Queue_6 * Ext_Bus * Memory_14) -o (Ext_Mem_Acc_6_14) ) ).
fof(End_Ext_Acc_1_11, axiom, !( (Ext_Mem_Acc_1_11) -o (Ext_Bus * Active_1 * Memory_11) ) ).
fof(Begin_Own_Acc_12, axiom, !( (Active_12) -o (OwnMemAcc_12) ) ).
fof(Begin_Ext_Acc_4_10, axiom, !( (Memory_10 * Ext_Bus * Queue_4) -o (Ext_Mem_Acc_4_10) ) ).
fof(End_Ext_Acc_2_8, axiom, !( (Ext_Mem_Acc_2_8) -o (Ext_Bus * Active_2 * Memory_8) ) ).
fof(Begin_Own_Acc_5, axiom, !( (Active_5) -o (OwnMemAcc_5) ) ).
fof(Begin_Ext_Acc_7_20, axiom, !( (Ext_Bus * Memory_20 * Queue_7) -o (Ext_Mem_Acc_7_20) ) ).
fof(End_Ext_Acc_10_6, axiom, !( (Ext_Mem_Acc_10_6) -o (Ext_Bus * Active_10 * Memory_6) ) ).
fof(Begin_Ext_Acc_4_5, axiom, !( (Queue_4 * Memory_5 * Ext_Bus) -o (Ext_Mem_Acc_4_5) ) ).
fof(Begin_Ext_Acc_5_11, axiom, !( (Queue_5 * Memory_11 * Ext_Bus) -o (Ext_Mem_Acc_5_11) ) ).
fof(End_Ext_Acc_8_15, axiom, !( (Ext_Mem_Acc_8_15) -o (Memory_15 * Active_8 * Ext_Bus) ) ).
fof(End_Ext_Acc_20_2, axiom, !( (Ext_Mem_Acc_20_2) -o (Memory_2 * Active_20 * Ext_Bus) ) ).
fof(End_Ext_Acc_5_18, axiom, !( (Ext_Mem_Acc_5_18) -o (Active_5 * Memory_18 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_8_12, axiom, !( (Queue_8 * Ext_Bus * Memory_12) -o (Ext_Mem_Acc_8_12) ) ).
fof(Begin_Own_Acc_16, axiom, !( (Active_16) -o (OwnMemAcc_16) ) ).
fof(Begin_Ext_Acc_5_18, axiom, !( (Memory_18 * Ext_Bus * Queue_5) -o (Ext_Mem_Acc_5_18) ) ).
fof(Begin_Ext_Acc_10_4, axiom, !( (Queue_10 * Memory_4 * Ext_Bus) -o (Ext_Mem_Acc_10_4) ) ).
fof(Begin_Ext_Acc_11_20, axiom, !( (Memory_20 * Ext_Bus * Queue_11) -o (Ext_Mem_Acc_11_20) ) ).
fof(Begin_Ext_Acc_15_8, axiom, !( (Memory_8 * Ext_Bus * Queue_15) -o (Ext_Mem_Acc_15_8) ) ).
fof(Begin_Ext_Acc_9_3, axiom, !( (Memory_3 * Ext_Bus * Queue_9) -o (Ext_Mem_Acc_9_3) ) ).
fof(Req_Ext_Acc_9, axiom, !( (Active_9) -o (Queue_9) ) ).
fof(End_Ext_Acc_13_1, axiom, !( (Ext_Mem_Acc_13_1) -o (Active_13 * Memory_1 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_9_1, axiom, !( (Queue_9 * Memory_1 * Ext_Bus) -o (Ext_Mem_Acc_9_1) ) ).
fof(Begin_Ext_Acc_1_17, axiom, !( (Queue_1 * Ext_Bus * Memory_17) -o (Ext_Mem_Acc_1_17) ) ).
fof(End_Ext_Acc_4_1, axiom, !( (Ext_Mem_Acc_4_1) -o (Memory_1 * Active_4 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_8_15, axiom, !( (Memory_15 * Ext_Bus * Queue_8) -o (Ext_Mem_Acc_8_15) ) ).
fof(Begin_Ext_Acc_12_6, axiom, !( (Queue_12 * Ext_Bus * Memory_6) -o (Ext_Mem_Acc_12_6) ) ).
fof(End_Ext_Acc_7_3, axiom, !( (Ext_Mem_Acc_7_3) -o (Ext_Bus * Memory_3 * Active_7) ) ).
fof(Begin_Ext_Acc_19_10, axiom, !( (Ext_Bus * Memory_10 * Queue_19) -o (Ext_Mem_Acc_19_10) ) ).
fof(Begin_Ext_Acc_7_3, axiom, !( (Memory_3 * Ext_Bus * Queue_7) -o (Ext_Mem_Acc_7_3) ) ).
fof(Begin_Ext_Acc_15_5, axiom, !( (Queue_15 * Ext_Bus * Memory_5) -o (Ext_Mem_Acc_15_5) ) ).
fof(Begin_Ext_Acc_5_20, axiom, !( (Queue_5 * Memory_20 * Ext_Bus) -o (Ext_Mem_Acc_5_20) ) ).
fof(End_Ext_Acc_6_14, axiom, !( (Ext_Mem_Acc_6_14) -o (Active_6 * Memory_14 * Ext_Bus) ) ).
fof(End_Ext_Acc_2_5, axiom, !( (Ext_Mem_Acc_2_5) -o (Ext_Bus * Active_2 * Memory_5) ) ).
fof(End_Ext_Acc_3_5, axiom, !( (Ext_Mem_Acc_3_5) -o (Ext_Bus * Active_3 * Memory_5) ) ).
fof(End_Ext_Acc_14_10, axiom, !( (Ext_Mem_Acc_14_10) -o (Active_14 * Memory_10 * Ext_Bus) ) ).
fof(End_Ext_Acc_20_6, axiom, !( (Ext_Mem_Acc_20_6) -o (Active_20 * Memory_6 * Ext_Bus) ) ).
fof(End_Ext_Acc_8_3, axiom, !( (Ext_Mem_Acc_8_3) -o (Ext_Bus * Memory_3 * Active_8) ) ).
fof(Begin_Ext_Acc_2_12, axiom, !( (Queue_2 * Memory_12 * Ext_Bus) -o (Ext_Mem_Acc_2_12) ) ).
fof(Begin_Ext_Acc_10_8, axiom, !( (Queue_10 * Ext_Bus * Memory_8) -o (Ext_Mem_Acc_10_8) ) ).
fof(Begin_Ext_Acc_19_9, axiom, !( (Ext_Bus * Memory_9 * Queue_19) -o (Ext_Mem_Acc_19_9) ) ).
fof(Begin_Ext_Acc_15_11, axiom, !( (Ext_Bus * Memory_11 * Queue_15) -o (Ext_Mem_Acc_15_11) ) ).
fof(Begin_Ext_Acc_2_14, axiom, !( (Queue_2 * Memory_14 * Ext_Bus) -o (Ext_Mem_Acc_2_14) ) ).
fof(Begin_Ext_Acc_8_10, axiom, !( (Queue_8 * Ext_Bus * Memory_10) -o (Ext_Mem_Acc_8_10) ) ).
fof(Begin_Ext_Acc_18_19, axiom, !( (Queue_18 * Ext_Bus * Memory_19) -o (Ext_Mem_Acc_18_19) ) ).
fof(Begin_Ext_Acc_13_3, axiom, !( (Queue_13 * Ext_Bus * Memory_3) -o (Ext_Mem_Acc_13_3) ) ).
fof(End_Ext_Acc_14_15, axiom, !( (Ext_Mem_Acc_14_15) -o (Ext_Bus * Memory_15 * Active_14) ) ).
fof(Begin_Ext_Acc_7_15, axiom, !( (Memory_15 * Ext_Bus * Queue_7) -o (Ext_Mem_Acc_7_15) ) ).
fof(End_Ext_Acc_13_2, axiom, !( (Ext_Mem_Acc_13_2) -o (Ext_Bus * Memory_2 * Active_13) ) ).
fof(End_Ext_Acc_10_17, axiom, !( (Ext_Mem_Acc_10_17) -o (Memory_17 * Active_10 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_12_20, axiom, !( (Memory_20 * Ext_Bus * Queue_12) -o (Ext_Mem_Acc_12_20) ) ).
fof(Begin_Ext_Acc_10_9, axiom, !( (Queue_10 * Ext_Bus * Memory_9) -o (Ext_Mem_Acc_10_9) ) ).
fof(End_Ext_Acc_10_15, axiom, !( (Ext_Mem_Acc_10_15) -o (Ext_Bus * Active_10 * Memory_15) ) ).
fof(Begin_Ext_Acc_1_20, axiom, !( (Queue_1 * Ext_Bus * Memory_20) -o (Ext_Mem_Acc_1_20) ) ).
fof(End_Ext_Acc_3_18, axiom, !( (Ext_Mem_Acc_3_18) -o (Memory_18 * Active_3 * Ext_Bus) ) ).
fof(End_Ext_Acc_3_20, axiom, !( (Ext_Mem_Acc_3_20) -o (Active_3 * Memory_20 * Ext_Bus) ) ).
fof(End_Ext_Acc_3_17, axiom, !( (Ext_Mem_Acc_3_17) -o (Ext_Bus * Memory_17 * Active_3) ) ).
fof(End_Ext_Acc_4_12, axiom, !( (Ext_Mem_Acc_4_12) -o (Active_4 * Memory_12 * Ext_Bus) ) ).
fof(End_Own_Acc_9_9, axiom, !( (Memory_9 * OwnMemAcc_9) -o (Memory_9 * Active_9) ) ).
fof(End_Ext_Acc_16_1, axiom, !( (Ext_Mem_Acc_16_1) -o (Active_16 * Memory_1 * Ext_Bus) ) ).
fof(End_Ext_Acc_19_6, axiom, !( (Ext_Mem_Acc_19_6) -o (Active_19 * Memory_6 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_17_16, axiom, !( (Memory_16 * Ext_Bus * Queue_17) -o (Ext_Mem_Acc_17_16) ) ).
fof(End_Ext_Acc_4_9, axiom, !( (Ext_Mem_Acc_4_9) -o (Ext_Bus * Memory_9 * Active_4) ) ).
fof(End_Ext_Acc_11_5, axiom, !( (Ext_Mem_Acc_11_5) -o (Active_11 * Memory_5 * Ext_Bus) ) ).
fof(End_Ext_Acc_6_1, axiom, !( (Ext_Mem_Acc_6_1) -o (Ext_Bus * Active_6 * Memory_1) ) ).
fof(Begin_Ext_Acc_12_17, axiom, !( (Ext_Bus * Memory_17 * Queue_12) -o (Ext_Mem_Acc_12_17) ) ).
fof(Begin_Ext_Acc_5_2, axiom, !( (Ext_Bus * Memory_2 * Queue_5) -o (Ext_Mem_Acc_5_2) ) ).
fof(Begin_Ext_Acc_1_9, axiom, !( (Ext_Bus * Memory_9 * Queue_1) -o (Ext_Mem_Acc_1_9) ) ).
fof(Begin_Ext_Acc_1_14, axiom, !( (Queue_1 * Memory_14 * Ext_Bus) -o (Ext_Mem_Acc_1_14) ) ).
fof(Begin_Ext_Acc_7_19, axiom, !( (Queue_7 * Memory_19 * Ext_Bus) -o (Ext_Mem_Acc_7_19) ) ).
fof(Begin_Ext_Acc_20_18, axiom, !( (Queue_20 * Ext_Bus * Memory_18) -o (Ext_Mem_Acc_20_18) ) ).
fof(End_Ext_Acc_12_7, axiom, !( (Ext_Mem_Acc_12_7) -o (Active_12 * Memory_7 * Ext_Bus) ) ).
fof(End_Ext_Acc_20_16, axiom, !( (Ext_Mem_Acc_20_16) -o (Ext_Bus * Memory_16 * Active_20) ) ).
fof(Begin_Ext_Acc_10_11, axiom, !( (Memory_11 * Ext_Bus * Queue_10) -o (Ext_Mem_Acc_10_11) ) ).
fof(End_Ext_Acc_10_1, axiom, !( (Ext_Mem_Acc_10_1) -o (Ext_Bus * Memory_1 * Active_10) ) ).
fof(End_Ext_Acc_18_17, axiom, !( (Ext_Mem_Acc_18_17) -o (Ext_Bus * Active_18 * Memory_17) ) ).
fof(Begin_Ext_Acc_4_6, axiom, !( (Ext_Bus * Memory_6 * Queue_4) -o (Ext_Mem_Acc_4_6) ) ).
fof(Begin_Ext_Acc_9_4, axiom, !( (Queue_9 * Memory_4 * Ext_Bus) -o (Ext_Mem_Acc_9_4) ) ).
fof(End_Ext_Acc_5_1, axiom, !( (Ext_Mem_Acc_5_1) -o (Ext_Bus * Active_5 * Memory_1) ) ).
fof(End_Ext_Acc_7_8, axiom, !( (Ext_Mem_Acc_7_8) -o (Active_7 * Memory_8 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_19_8, axiom, !( (Ext_Bus * Memory_8 * Queue_19) -o (Ext_Mem_Acc_19_8) ) ).
fof(End_Ext_Acc_5_16, axiom, !( (Ext_Mem_Acc_5_16) -o (Ext_Bus * Memory_16 * Active_5) ) ).
fof(Begin_Ext_Acc_2_1, axiom, !( (Memory_1 * Ext_Bus * Queue_2) -o (Ext_Mem_Acc_2_1) ) ).
fof(Begin_Ext_Acc_19_1, axiom, !( (Memory_1 * Ext_Bus * Queue_19) -o (Ext_Mem_Acc_19_1) ) ).
fof(Begin_Ext_Acc_7_5, axiom, !( (Queue_7 * Memory_5 * Ext_Bus) -o (Ext_Mem_Acc_7_5) ) ).
fof(End_Ext_Acc_6_11, axiom, !( (Ext_Mem_Acc_6_11) -o (Active_6 * Memory_11 * Ext_Bus) ) ).
fof(Begin_Own_Acc_15, axiom, !( (Active_15) -o (OwnMemAcc_15) ) ).
fof(Begin_Ext_Acc_13_17, axiom, !( (Ext_Bus * Memory_17 * Queue_13) -o (Ext_Mem_Acc_13_17) ) ).
fof(End_Ext_Acc_5_2, axiom, !( (Ext_Mem_Acc_5_2) -o (Ext_Bus * Active_5 * Memory_2) ) ).
fof(Begin_Ext_Acc_8_2, axiom, !( (Ext_Bus * Memory_2 * Queue_8) -o (Ext_Mem_Acc_8_2) ) ).
fof(Begin_Ext_Acc_3_1, axiom, !( (Memory_1 * Ext_Bus * Queue_3) -o (Ext_Mem_Acc_3_1) ) ).
fof(Begin_Ext_Acc_20_14, axiom, !( (Queue_20 * Memory_14 * Ext_Bus) -o (Ext_Mem_Acc_20_14) ) ).
fof(Begin_Ext_Acc_10_6, axiom, !( (Queue_10 * Ext_Bus * Memory_6) -o (Ext_Mem_Acc_10_6) ) ).
fof(Begin_Ext_Acc_13_5, axiom, !( (Queue_13 * Ext_Bus * Memory_5) -o (Ext_Mem_Acc_13_5) ) ).
fof(Begin_Ext_Acc_16_17, axiom, !( (Queue_16 * Memory_17 * Ext_Bus) -o (Ext_Mem_Acc_16_17) ) ).
fof(Begin_Ext_Acc_18_7, axiom, !( (Memory_7 * Ext_Bus * Queue_18) -o (Ext_Mem_Acc_18_7) ) ).
fof(Begin_Ext_Acc_16_4, axiom, !( (Memory_4 * Ext_Bus * Queue_16) -o (Ext_Mem_Acc_16_4) ) ).
fof(Begin_Ext_Acc_15_19, axiom, !( (Memory_19 * Ext_Bus * Queue_15) -o (Ext_Mem_Acc_15_19) ) ).
fof(End_Ext_Acc_20_11, axiom, !( (Ext_Mem_Acc_20_11) -o (Ext_Bus * Memory_11 * Active_20) ) ).
fof(Begin_Ext_Acc_6_17, axiom, !( (Queue_6 * Memory_17 * Ext_Bus) -o (Ext_Mem_Acc_6_17) ) ).
fof(End_Ext_Acc_19_10, axiom, !( (Ext_Mem_Acc_19_10) -o (Ext_Bus * Active_19 * Memory_10) ) ).
fof(Begin_Ext_Acc_8_20, axiom, !( (Ext_Bus * Memory_20 * Queue_8) -o (Ext_Mem_Acc_8_20) ) ).
fof(Begin_Ext_Acc_12_14, axiom, !( (Memory_14 * Ext_Bus * Queue_12) -o (Ext_Mem_Acc_12_14) ) ).
fof(Req_Ext_Acc_18, axiom, !( (Active_18) -o (Queue_18) ) ).
fof(Begin_Ext_Acc_8_4, axiom, !( (Queue_8 * Memory_4 * Ext_Bus) -o (Ext_Mem_Acc_8_4) ) ).
fof(Begin_Ext_Acc_8_5, axiom, !( (Queue_8 * Memory_5 * Ext_Bus) -o (Ext_Mem_Acc_8_5) ) ).
fof(Begin_Ext_Acc_11_3, axiom, !( (Queue_11 * Ext_Bus * Memory_3) -o (Ext_Mem_Acc_11_3) ) ).
fof(End_Ext_Acc_3_13, axiom, !( (Ext_Mem_Acc_3_13) -o (Ext_Bus * Memory_13 * Active_3) ) ).
fof(Begin_Ext_Acc_18_3, axiom, !( (Queue_18 * Memory_3 * Ext_Bus) -o (Ext_Mem_Acc_18_3) ) ).
fof(Begin_Ext_Acc_9_8, axiom, !( (Queue_9 * Ext_Bus * Memory_8) -o (Ext_Mem_Acc_9_8) ) ).
fof(End_Ext_Acc_20_15, axiom, !( (Ext_Mem_Acc_20_15) -o (Ext_Bus * Active_20 * Memory_15) ) ).
fof(Begin_Ext_Acc_7_2, axiom, !( (Ext_Bus * Memory_2 * Queue_7) -o (Ext_Mem_Acc_7_2) ) ).
fof(Begin_Ext_Acc_3_7, axiom, !( (Memory_7 * Ext_Bus * Queue_3) -o (Ext_Mem_Acc_3_7) ) ).
fof(End_Ext_Acc_7_5, axiom, !( (Ext_Mem_Acc_7_5) -o (Ext_Bus * Memory_5 * Active_7) ) ).
fof(Begin_Ext_Acc_15_17, axiom, !( (Ext_Bus * Memory_17 * Queue_15) -o (Ext_Mem_Acc_15_17) ) ).
fof(End_Ext_Acc_15_11, axiom, !( (Ext_Mem_Acc_15_11) -o (Ext_Bus * Active_15 * Memory_11) ) ).
fof(End_Ext_Acc_6_2, axiom, !( (Ext_Mem_Acc_6_2) -o (Ext_Bus * Memory_2 * Active_6) ) ).
fof(End_Ext_Acc_4_14, axiom, !( (Ext_Mem_Acc_4_14) -o (Ext_Bus * Active_4 * Memory_14) ) ).
fof(Begin_Ext_Acc_3_12, axiom, !( (Queue_3 * Ext_Bus * Memory_12) -o (Ext_Mem_Acc_3_12) ) ).
fof(End_Ext_Acc_16_20, axiom, !( (Ext_Mem_Acc_16_20) -o (Ext_Bus * Memory_20 * Active_16) ) ).
fof(Begin_Ext_Acc_20_6, axiom, !( (Ext_Bus * Memory_6 * Queue_20) -o (Ext_Mem_Acc_20_6) ) ).
fof(End_Ext_Acc_17_11, axiom, !( (Ext_Mem_Acc_17_11) -o (Ext_Bus * Active_17 * Memory_11) ) ).
fof(End_Ext_Acc_17_1, axiom, !( (Ext_Mem_Acc_17_1) -o (Memory_1 * Active_17 * Ext_Bus) ) ).
fof(End_Ext_Acc_13_4, axiom, !( (Ext_Mem_Acc_13_4) -o (Active_13 * Memory_4 * Ext_Bus) ) ).
fof(End_Ext_Acc_14_17, axiom, !( (Ext_Mem_Acc_14_17) -o (Ext_Bus * Memory_17 * Active_14) ) ).
fof(End_Ext_Acc_2_1, axiom, !( (Ext_Mem_Acc_2_1) -o (Memory_1 * Active_2 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_1_19, axiom, !( (Queue_1 * Ext_Bus * Memory_19) -o (Ext_Mem_Acc_1_19) ) ).
fof(Begin_Ext_Acc_12_1, axiom, !( (Queue_12 * Memory_1 * Ext_Bus) -o (Ext_Mem_Acc_12_1) ) ).
fof(Begin_Ext_Acc_14_4, axiom, !( (Queue_14 * Ext_Bus * Memory_4) -o (Ext_Mem_Acc_14_4) ) ).
fof(Req_Ext_Acc_1, axiom, !( (Active_1) -o (Queue_1) ) ).
fof(Begin_Ext_Acc_9_18, axiom, !( (Ext_Bus * Memory_18 * Queue_9) -o (Ext_Mem_Acc_9_18) ) ).
fof(End_Ext_Acc_4_13, axiom, !( (Ext_Mem_Acc_4_13) -o (Ext_Bus * Active_4 * Memory_13) ) ).
fof(Begin_Ext_Acc_17_11, axiom, !( (Ext_Bus * Memory_11 * Queue_17) -o (Ext_Mem_Acc_17_11) ) ).
fof(End_Ext_Acc_11_14, axiom, !( (Ext_Mem_Acc_11_14) -o (Memory_14 * Active_11 * Ext_Bus) ) ).
fof(Begin_Own_Acc_8, axiom, !( (Active_8) -o (OwnMemAcc_8) ) ).
fof(End_Ext_Acc_10_9, axiom, !( (Ext_Mem_Acc_10_9) -o (Ext_Bus * Active_10 * Memory_9) ) ).
fof(End_Ext_Acc_16_18, axiom, !( (Ext_Mem_Acc_16_18) -o (Ext_Bus * Active_16 * Memory_18) ) ).
fof(End_Ext_Acc_10_12, axiom, !( (Ext_Mem_Acc_10_12) -o (Memory_12 * Active_10 * Ext_Bus) ) ).
fof(Req_Ext_Acc_4, axiom, !( (Active_4) -o (Queue_4) ) ).
fof(Begin_Ext_Acc_2_3, axiom, !( (Ext_Bus * Memory_3 * Queue_2) -o (Ext_Mem_Acc_2_3) ) ).
fof(Begin_Ext_Acc_10_19, axiom, !( (Ext_Bus * Memory_19 * Queue_10) -o (Ext_Mem_Acc_10_19) ) ).
fof(End_Ext_Acc_12_3, axiom, !( (Ext_Mem_Acc_12_3) -o (Ext_Bus * Active_12 * Memory_3) ) ).
fof(End_Ext_Acc_7_10, axiom, !( (Ext_Mem_Acc_7_10) -o (Ext_Bus * Active_7 * Memory_10) ) ).
fof(End_Ext_Acc_8_7, axiom, !( (Ext_Mem_Acc_8_7) -o (Ext_Bus * Active_8 * Memory_7) ) ).
fof(Begin_Ext_Acc_11_18, axiom, !( (Ext_Bus * Memory_18 * Queue_11) -o (Ext_Mem_Acc_11_18) ) ).
fof(End_Own_Acc_8_8, axiom, !( (Memory_8 * OwnMemAcc_8) -o (Memory_8 * Active_8) ) ).
fof(End_Ext_Acc_4_15, axiom, !( (Ext_Mem_Acc_4_15) -o (Active_4 * Memory_15 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_16_12, axiom, !( (Ext_Bus * Memory_12 * Queue_16) -o (Ext_Mem_Acc_16_12) ) ).
fof(End_Ext_Acc_4_3, axiom, !( (Ext_Mem_Acc_4_3) -o (Active_4 * Memory_3 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_19_16, axiom, !( (Memory_16 * Ext_Bus * Queue_19) -o (Ext_Mem_Acc_19_16) ) ).
fof(Begin_Ext_Acc_16_2, axiom, !( (Queue_16 * Ext_Bus * Memory_2) -o (Ext_Mem_Acc_16_2) ) ).
fof(End_Ext_Acc_16_4, axiom, !( (Ext_Mem_Acc_16_4) -o (Memory_4 * Active_16 * Ext_Bus) ) ).
fof(End_Ext_Acc_10_18, axiom, !( (Ext_Mem_Acc_10_18) -o (Ext_Bus * Memory_18 * Active_10) ) ).
fof(End_Ext_Acc_19_13, axiom, !( (Ext_Mem_Acc_19_13) -o (Ext_Bus * Memory_13 * Active_19) ) ).
fof(Begin_Ext_Acc_12_19, axiom, !( (Ext_Bus * Memory_19 * Queue_12) -o (Ext_Mem_Acc_12_19) ) ).
fof(End_Ext_Acc_15_7, axiom, !( (Ext_Mem_Acc_15_7) -o (Memory_7 * Active_15 * Ext_Bus) ) ).
fof(End_Ext_Acc_10_11, axiom, !( (Ext_Mem_Acc_10_11) -o (Memory_11 * Active_10 * Ext_Bus) ) ).
fof(End_Own_Acc_11_11, axiom, !( (OwnMemAcc_11 * Memory_11) -o (Active_11 * Memory_11) ) ).
fof(Begin_Ext_Acc_19_12, axiom, !( (Ext_Bus * Memory_12 * Queue_19) -o (Ext_Mem_Acc_19_12) ) ).
fof(End_Ext_Acc_9_14, axiom, !( (Ext_Mem_Acc_9_14) -o (Memory_14 * Active_9 * Ext_Bus) ) ).
fof(End_Ext_Acc_16_2, axiom, !( (Ext_Mem_Acc_16_2) -o (Ext_Bus * Active_16 * Memory_2) ) ).
fof(End_Ext_Acc_17_13, axiom, !( (Ext_Mem_Acc_17_13) -o (Ext_Bus * Memory_13 * Active_17) ) ).
fof(Begin_Ext_Acc_20_1, axiom, !( (Memory_1 * Ext_Bus * Queue_20) -o (Ext_Mem_Acc_20_1) ) ).
fof(Begin_Ext_Acc_3_20, axiom, !( (Queue_3 * Memory_20 * Ext_Bus) -o (Ext_Mem_Acc_3_20) ) ).
fof(End_Ext_Acc_18_8, axiom, !( (Ext_Mem_Acc_18_8) -o (Ext_Bus * Active_18 * Memory_8) ) ).
fof(End_Own_Acc_18_18, axiom, !( (OwnMemAcc_18 * Memory_18) -o (Active_18 * Memory_18) ) ).
fof(Begin_Ext_Acc_11_1, axiom, !( (Queue_11 * Memory_1 * Ext_Bus) -o (Ext_Mem_Acc_11_1) ) ).
fof(Begin_Ext_Acc_9_17, axiom, !( (Memory_17 * Ext_Bus * Queue_9) -o (Ext_Mem_Acc_9_17) ) ).
fof(End_Ext_Acc_8_4, axiom, !( (Ext_Mem_Acc_8_4) -o (Ext_Bus * Memory_4 * Active_8) ) ).
fof(End_Ext_Acc_3_6, axiom, !( (Ext_Mem_Acc_3_6) -o (Active_3 * Memory_6 * Ext_Bus) ) ).
fof(End_Ext_Acc_15_5, axiom, !( (Ext_Mem_Acc_15_5) -o (Memory_5 * Active_15 * Ext_Bus) ) ).
fof(End_Ext_Acc_2_15, axiom, !( (Ext_Mem_Acc_2_15) -o (Active_2 * Memory_15 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_10_13, axiom, !( (Queue_10 * Memory_13 * Ext_Bus) -o (Ext_Mem_Acc_10_13) ) ).
fof(Begin_Ext_Acc_14_11, axiom, !( (Memory_11 * Ext_Bus * Queue_14) -o (Ext_Mem_Acc_14_11) ) ).
fof(Begin_Ext_Acc_16_6, axiom, !( (Queue_16 * Memory_6 * Ext_Bus) -o (Ext_Mem_Acc_16_6) ) ).
fof(Begin_Ext_Acc_1_2, axiom, !( (Ext_Bus * Memory_2 * Queue_1) -o (Ext_Mem_Acc_1_2) ) ).
fof(Begin_Ext_Acc_14_2, axiom, !( (Queue_14 * Ext_Bus * Memory_2) -o (Ext_Mem_Acc_14_2) ) ).
fof(Begin_Ext_Acc_4_17, axiom, !( (Queue_4 * Memory_17 * Ext_Bus) -o (Ext_Mem_Acc_4_17) ) ).
fof(End_Ext_Acc_8_17, axiom, !( (Ext_Mem_Acc_8_17) -o (Memory_17 * Active_8 * Ext_Bus) ) ).
fof(End_Ext_Acc_7_20, axiom, !( (Ext_Mem_Acc_7_20) -o (Memory_20 * Active_7 * Ext_Bus) ) ).
fof(End_Ext_Acc_6_12, axiom, !( (Ext_Mem_Acc_6_12) -o (Active_6 * Memory_12 * Ext_Bus) ) ).
fof(End_Ext_Acc_17_6, axiom, !( (Ext_Mem_Acc_17_6) -o (Memory_6 * Active_17 * Ext_Bus) ) ).
fof(End_Ext_Acc_12_20, axiom, !( (Ext_Mem_Acc_12_20) -o (Ext_Bus * Active_12 * Memory_20) ) ).
fof(End_Ext_Acc_8_5, axiom, !( (Ext_Mem_Acc_8_5) -o (Ext_Bus * Memory_5 * Active_8) ) ).
fof(End_Ext_Acc_6_16, axiom, !( (Ext_Mem_Acc_6_16) -o (Ext_Bus * Memory_16 * Active_6) ) ).
fof(Begin_Ext_Acc_17_19, axiom, !( (Memory_19 * Ext_Bus * Queue_17) -o (Ext_Mem_Acc_17_19) ) ).
fof(End_Ext_Acc_5_10, axiom, !( (Ext_Mem_Acc_5_10) -o (Ext_Bus * Active_5 * Memory_10) ) ).
fof(Begin_Ext_Acc_14_16, axiom, !( (Ext_Bus * Memory_16 * Queue_14) -o (Ext_Mem_Acc_14_16) ) ).
fof(Begin_Own_Acc_20, axiom, !( (Active_20) -o (OwnMemAcc_20) ) ).
fof(Begin_Ext_Acc_14_13, axiom, !( (Ext_Bus * Memory_13 * Queue_14) -o (Ext_Mem_Acc_14_13) ) ).
fof(End_Ext_Acc_16_12, axiom, !( (Ext_Mem_Acc_16_12) -o (Active_16 * Memory_12 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_15_7, axiom, !( (Memory_7 * Ext_Bus * Queue_15) -o (Ext_Mem_Acc_15_7) ) ).
fof(End_Ext_Acc_17_18, axiom, !( (Ext_Mem_Acc_17_18) -o (Memory_18 * Active_17 * Ext_Bus) ) ).
fof(Begin_Own_Acc_17, axiom, !( (Active_17) -o (OwnMemAcc_17) ) ).
fof(End_Ext_Acc_5_6, axiom, !( (Ext_Mem_Acc_5_6) -o (Ext_Bus * Memory_6 * Active_5) ) ).
fof(End_Ext_Acc_4_2, axiom, !( (Ext_Mem_Acc_4_2) -o (Ext_Bus * Active_4 * Memory_2) ) ).
fof(Begin_Ext_Acc_1_18, axiom, !( (Queue_1 * Ext_Bus * Memory_18) -o (Ext_Mem_Acc_1_18) ) ).
fof(Begin_Ext_Acc_13_12, axiom, !( (Queue_13 * Memory_12 * Ext_Bus) -o (Ext_Mem_Acc_13_12) ) ).
fof(Begin_Ext_Acc_17_20, axiom, !( (Queue_17 * Memory_20 * Ext_Bus) -o (Ext_Mem_Acc_17_20) ) ).
fof(Begin_Ext_Acc_8_13, axiom, !( (Queue_8 * Memory_13 * Ext_Bus) -o (Ext_Mem_Acc_8_13) ) ).
fof(End_Own_Acc_7_7, axiom, !( (Memory_7 * OwnMemAcc_7) -o (Memory_7 * Active_7) ) ).
fof(Begin_Ext_Acc_17_13, axiom, !( (Memory_13 * Ext_Bus * Queue_17) -o (Ext_Mem_Acc_17_13) ) ).
fof(Begin_Ext_Acc_13_16, axiom, !( (Ext_Bus * Memory_16 * Queue_13) -o (Ext_Mem_Acc_13_16) ) ).
fof(Begin_Ext_Acc_14_3, axiom, !( (Queue_14 * Ext_Bus * Memory_3) -o (Ext_Mem_Acc_14_3) ) ).
fof(End_Ext_Acc_3_10, axiom, !( (Ext_Mem_Acc_3_10) -o (Ext_Bus * Memory_10 * Active_3) ) ).
fof(Begin_Ext_Acc_2_11, axiom, !( (Queue_2 * Memory_11 * Ext_Bus) -o (Ext_Mem_Acc_2_11) ) ).
fof(End_Ext_Acc_11_16, axiom, !( (Ext_Mem_Acc_11_16) -o (Memory_16 * Active_11 * Ext_Bus) ) ).
fof(End_Ext_Acc_10_20, axiom, !( (Ext_Mem_Acc_10_20) -o (Memory_20 * Active_10 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_4_9, axiom, !( (Memory_9 * Ext_Bus * Queue_4) -o (Ext_Mem_Acc_4_9) ) ).
fof(End_Ext_Acc_9_7, axiom, !( (Ext_Mem_Acc_9_7) -o (Ext_Bus * Active_9 * Memory_7) ) ).
fof(End_Ext_Acc_12_18, axiom, !( (Ext_Mem_Acc_12_18) -o (Ext_Bus * Memory_18 * Active_12) ) ).
fof(End_Ext_Acc_15_19, axiom, !( (Ext_Mem_Acc_15_19) -o (Ext_Bus * Active_15 * Memory_19) ) ).
fof(End_Ext_Acc_2_20, axiom, !( (Ext_Mem_Acc_2_20) -o (Ext_Bus * Memory_20 * Active_2) ) ).
fof(Req_Ext_Acc_14, axiom, !( (Active_14) -o (Queue_14) ) ).
fof(Req_Ext_Acc_6, axiom, !( (Active_6) -o (Queue_6) ) ).
fof(Begin_Ext_Acc_13_1, axiom, !( (Queue_13 * Ext_Bus * Memory_1) -o (Ext_Mem_Acc_13_1) ) ).
fof(End_Ext_Acc_17_2, axiom, !( (Ext_Mem_Acc_17_2) -o (Ext_Bus * Active_17 * Memory_2) ) ).
fof(End_Ext_Acc_18_2, axiom, !( (Ext_Mem_Acc_18_2) -o (Memory_2 * Active_18 * Ext_Bus) ) ).
fof(End_Ext_Acc_12_5, axiom, !( (Ext_Mem_Acc_12_5) -o (Active_12 * Memory_5 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_9_20, axiom, !( (Ext_Bus * Memory_20 * Queue_9) -o (Ext_Mem_Acc_9_20) ) ).
fof(End_Ext_Acc_15_10, axiom, !( (Ext_Mem_Acc_15_10) -o (Active_15 * Memory_10 * Ext_Bus) ) ).
fof(End_Ext_Acc_18_14, axiom, !( (Ext_Mem_Acc_18_14) -o (Ext_Bus * Memory_14 * Active_18) ) ).
fof(Begin_Ext_Acc_9_5, axiom, !( (Queue_9 * Ext_Bus * Memory_5) -o (Ext_Mem_Acc_9_5) ) ).
fof(End_Ext_Acc_20_19, axiom, !( (Ext_Mem_Acc_20_19) -o (Ext_Bus * Memory_19 * Active_20) ) ).
fof(Begin_Ext_Acc_10_16, axiom, !( (Queue_10 * Memory_16 * Ext_Bus) -o (Ext_Mem_Acc_10_16) ) ).
fof(End_Ext_Acc_2_18, axiom, !( (Ext_Mem_Acc_2_18) -o (Memory_18 * Active_2 * Ext_Bus) ) ).
fof(End_Ext_Acc_4_19, axiom, !( (Ext_Mem_Acc_4_19) -o (Active_4 * Memory_19 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_18_6, axiom, !( (Ext_Bus * Memory_6 * Queue_18) -o (Ext_Mem_Acc_18_6) ) ).
fof(Begin_Ext_Acc_15_14, axiom, !( (Ext_Bus * Memory_14 * Queue_15) -o (Ext_Mem_Acc_15_14) ) ).
fof(End_Own_Acc_19_19, axiom, !( (OwnMemAcc_19 * Memory_19) -o (Active_19 * Memory_19) ) ).
fof(End_Ext_Acc_11_10, axiom, !( (Ext_Mem_Acc_11_10) -o (Memory_10 * Active_11 * Ext_Bus) ) ).
fof(End_Ext_Acc_12_11, axiom, !( (Ext_Mem_Acc_12_11) -o (Memory_11 * Active_12 * Ext_Bus) ) ).
fof(End_Ext_Acc_5_13, axiom, !( (Ext_Mem_Acc_5_13) -o (Ext_Bus * Active_5 * Memory_13) ) ).
fof(Begin_Ext_Acc_8_16, axiom, !( (Queue_8 * Memory_16 * Ext_Bus) -o (Ext_Mem_Acc_8_16) ) ).
fof(End_Ext_Acc_15_12, axiom, !( (Ext_Mem_Acc_15_12) -o (Memory_12 * Active_15 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_6_9, axiom, !( (Memory_9 * Ext_Bus * Queue_6) -o (Ext_Mem_Acc_6_9) ) ).
fof(Begin_Ext_Acc_18_14, axiom, !( (Queue_18 * Memory_14 * Ext_Bus) -o (Ext_Mem_Acc_18_14) ) ).
fof(End_Ext_Acc_3_4, axiom, !( (Ext_Mem_Acc_3_4) -o (Ext_Bus * Active_3 * Memory_4) ) ).
fof(End_Ext_Acc_13_14, axiom, !( (Ext_Mem_Acc_13_14) -o (Ext_Bus * Active_13 * Memory_14) ) ).
fof(End_Ext_Acc_9_18, axiom, !( (Ext_Mem_Acc_9_18) -o (Ext_Bus * Memory_18 * Active_9) ) ).
fof(End_Ext_Acc_1_15, axiom, !( (Ext_Mem_Acc_1_15) -o (Ext_Bus * Memory_15 * Active_1) ) ).
fof(End_Ext_Acc_3_14, axiom, !( (Ext_Mem_Acc_3_14) -o (Ext_Bus * Active_3 * Memory_14) ) ).
fof(End_Ext_Acc_1_12, axiom, !( (Ext_Mem_Acc_1_12) -o (Ext_Bus * Memory_12 * Active_1) ) ).
fof(End_Ext_Acc_9_20, axiom, !( (Ext_Mem_Acc_9_20) -o (Memory_20 * Active_9 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_20_13, axiom, !( (Memory_13 * Ext_Bus * Queue_20) -o (Ext_Mem_Acc_20_13) ) ).
fof(Begin_Ext_Acc_17_6, axiom, !( (Queue_17 * Memory_6 * Ext_Bus) -o (Ext_Mem_Acc_17_6) ) ).
fof(Begin_Ext_Acc_2_4, axiom, !( (Memory_4 * Ext_Bus * Queue_2) -o (Ext_Mem_Acc_2_4) ) ).
fof(Req_Ext_Acc_19, axiom, !( (Active_19) -o (Queue_19) ) ).
fof(End_Ext_Acc_14_3, axiom, !( (Ext_Mem_Acc_14_3) -o (Ext_Bus * Active_14 * Memory_3) ) ).
fof(Begin_Ext_Acc_3_17, axiom, !( (Queue_3 * Ext_Bus * Memory_17) -o (Ext_Mem_Acc_3_17) ) ).
fof(Begin_Ext_Acc_6_18, axiom, !( (Memory_18 * Ext_Bus * Queue_6) -o (Ext_Mem_Acc_6_18) ) ).
fof(End_Ext_Acc_6_19, axiom, !( (Ext_Mem_Acc_6_19) -o (Active_6 * Memory_19 * Ext_Bus) ) ).
fof(End_Ext_Acc_17_3, axiom, !( (Ext_Mem_Acc_17_3) -o (Memory_3 * Active_17 * Ext_Bus) ) ).
fof(End_Ext_Acc_18_15, axiom, !( (Ext_Mem_Acc_18_15) -o (Ext_Bus * Memory_15 * Active_18) ) ).
fof(End_Ext_Acc_12_6, axiom, !( (Ext_Mem_Acc_12_6) -o (Ext_Bus * Active_12 * Memory_6) ) ).
fof(End_Ext_Acc_20_18, axiom, !( (Ext_Mem_Acc_20_18) -o (Memory_18 * Active_20 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_16_10, axiom, !( (Memory_10 * Ext_Bus * Queue_16) -o (Ext_Mem_Acc_16_10) ) ).
fof(Begin_Ext_Acc_2_8, axiom, !( (Ext_Bus * Memory_8 * Queue_2) -o (Ext_Mem_Acc_2_8) ) ).
fof(Begin_Ext_Acc_3_9, axiom, !( (Ext_Bus * Memory_9 * Queue_3) -o (Ext_Mem_Acc_3_9) ) ).
fof(Begin_Ext_Acc_2_16, axiom, !( (Memory_16 * Ext_Bus * Queue_2) -o (Ext_Mem_Acc_2_16) ) ).
fof(End_Ext_Acc_10_2, axiom, !( (Ext_Mem_Acc_10_2) -o (Ext_Bus * Memory_2 * Active_10) ) ).
fof(End_Ext_Acc_7_13, axiom, !( (Ext_Mem_Acc_7_13) -o (Ext_Bus * Active_7 * Memory_13) ) ).
fof(End_Ext_Acc_2_10, axiom, !( (Ext_Mem_Acc_2_10) -o (Ext_Bus * Memory_10 * Active_2) ) ).
fof(End_Ext_Acc_17_9, axiom, !( (Ext_Mem_Acc_17_9) -o (Active_17 * Memory_9 * Ext_Bus) ) ).
fof(End_Ext_Acc_6_8, axiom, !( (Ext_Mem_Acc_6_8) -o (Ext_Bus * Memory_8 * Active_6) ) ).
fof(Begin_Ext_Acc_2_19, axiom, !( (Queue_2 * Ext_Bus * Memory_19) -o (Ext_Mem_Acc_2_19) ) ).
fof(Begin_Ext_Acc_20_17, axiom, !( (Queue_20 * Memory_17 * Ext_Bus) -o (Ext_Mem_Acc_20_17) ) ).
fof(Begin_Ext_Acc_9_7, axiom, !( (Queue_9 * Memory_7 * Ext_Bus) -o (Ext_Mem_Acc_9_7) ) ).
fof(End_Ext_Acc_15_9, axiom, !( (Ext_Mem_Acc_15_9) -o (Memory_9 * Active_15 * Ext_Bus) ) ).
fof(End_Ext_Acc_9_1, axiom, !( (Ext_Mem_Acc_9_1) -o (Ext_Bus * Memory_1 * Active_9) ) ).
fof(End_Ext_Acc_17_15, axiom, !( (Ext_Mem_Acc_17_15) -o (Ext_Bus * Memory_15 * Active_17) ) ).
fof(End_Ext_Acc_14_16, axiom, !( (Ext_Mem_Acc_14_16) -o (Memory_16 * Active_14 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_13_14, axiom, !( (Ext_Bus * Memory_14 * Queue_13) -o (Ext_Mem_Acc_13_14) ) ).
fof(Begin_Ext_Acc_11_17, axiom, !( (Memory_17 * Ext_Bus * Queue_11) -o (Ext_Mem_Acc_11_17) ) ).
fof(Begin_Own_Acc_18, axiom, !( (Active_18) -o (OwnMemAcc_18) ) ).
fof(Begin_Own_Acc_4, axiom, !( (Active_4) -o (OwnMemAcc_4) ) ).
fof(End_Ext_Acc_16_14, axiom, !( (Ext_Mem_Acc_16_14) -o (Ext_Bus * Active_16 * Memory_14) ) ).
fof(End_Ext_Acc_13_11, axiom, !( (Ext_Mem_Acc_13_11) -o (Memory_11 * Active_13 * Ext_Bus) ) ).
fof(End_Ext_Acc_11_3, axiom, !( (Ext_Mem_Acc_11_3) -o (Ext_Bus * Active_11 * Memory_3) ) ).
fof(End_Ext_Acc_12_10, axiom, !( (Ext_Mem_Acc_12_10) -o (Memory_10 * Active_12 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_11_12, axiom, !( (Queue_11 * Memory_12 * Ext_Bus) -o (Ext_Mem_Acc_11_12) ) ).
fof(End_Own_Acc_5_5, axiom, !( (OwnMemAcc_5 * Memory_5) -o (Active_5 * Memory_5) ) ).
fof(Begin_Ext_Acc_6_16, axiom, !( (Queue_6 * Ext_Bus * Memory_16) -o (Ext_Mem_Acc_6_16) ) ).
fof(Begin_Ext_Acc_9_16, axiom, !( (Queue_9 * Memory_16 * Ext_Bus) -o (Ext_Mem_Acc_9_16) ) ).
fof(End_Ext_Acc_1_5, axiom, !( (Ext_Mem_Acc_1_5) -o (Ext_Bus * Active_1 * Memory_5) ) ).
fof(End_Ext_Acc_19_14, axiom, !( (Ext_Mem_Acc_19_14) -o (Ext_Bus * Memory_14 * Active_19) ) ).
fof(Begin_Ext_Acc_3_13, axiom, !( (Memory_13 * Ext_Bus * Queue_3) -o (Ext_Mem_Acc_3_13) ) ).
fof(Begin_Ext_Acc_8_1, axiom, !( (Ext_Bus * Memory_1 * Queue_8) -o (Ext_Mem_Acc_8_1) ) ).
fof(Begin_Ext_Acc_19_17, axiom, !( (Queue_19 * Memory_17 * Ext_Bus) -o (Ext_Mem_Acc_19_17) ) ).
fof(Begin_Ext_Acc_1_15, axiom, !( (Queue_1 * Memory_15 * Ext_Bus) -o (Ext_Mem_Acc_1_15) ) ).
fof(Req_Ext_Acc_3, axiom, !( (Active_3) -o (Queue_3) ) ).
fof(Begin_Ext_Acc_5_1, axiom, !( (Ext_Bus * Memory_1 * Queue_5) -o (Ext_Mem_Acc_5_1) ) ).
fof(End_Ext_Acc_14_2, axiom, !( (Ext_Mem_Acc_14_2) -o (Ext_Bus * Active_14 * Memory_2) ) ).
fof(End_Ext_Acc_13_18, axiom, !( (Ext_Mem_Acc_13_18) -o (Ext_Bus * Active_13 * Memory_18) ) ).
fof(Begin_Own_Acc_6, axiom, !( (Active_6) -o (OwnMemAcc_6) ) ).
fof(End_Ext_Acc_15_18, axiom, !( (Ext_Mem_Acc_15_18) -o (Ext_Bus * Active_15 * Memory_18) ) ).
fof(End_Ext_Acc_20_1, axiom, !( (Ext_Mem_Acc_20_1) -o (Memory_1 * Active_20 * Ext_Bus) ) ).
fof(End_Ext_Acc_14_1, axiom, !( (Ext_Mem_Acc_14_1) -o (Active_14 * Memory_1 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_20_9, axiom, !( (Ext_Bus * Memory_9 * Queue_20) -o (Ext_Mem_Acc_20_9) ) ).
fof(Begin_Ext_Acc_17_7, axiom, !( (Memory_7 * Ext_Bus * Queue_17) -o (Ext_Mem_Acc_17_7) ) ).
fof(Begin_Ext_Acc_6_3, axiom, !( (Ext_Bus * Memory_3 * Queue_6) -o (Ext_Mem_Acc_6_3) ) ).
fof(Begin_Ext_Acc_4_13, axiom, !( (Queue_4 * Ext_Bus * Memory_13) -o (Ext_Mem_Acc_4_13) ) ).
fof(End_Own_Acc_16_16, axiom, !( (Memory_16 * OwnMemAcc_16) -o (Memory_16 * Active_16) ) ).
fof(Begin_Ext_Acc_5_15, axiom, !( (Queue_5 * Ext_Bus * Memory_15) -o (Ext_Mem_Acc_5_15) ) ).
fof(Begin_Ext_Acc_14_5, axiom, !( (Queue_14 * Ext_Bus * Memory_5) -o (Ext_Mem_Acc_14_5) ) ).
fof(Begin_Ext_Acc_1_12, axiom, !( (Queue_1 * Memory_12 * Ext_Bus) -o (Ext_Mem_Acc_1_12) ) ).
fof(Begin_Ext_Acc_4_7, axiom, !( (Memory_7 * Ext_Bus * Queue_4) -o (Ext_Mem_Acc_4_7) ) ).
fof(End_Ext_Acc_11_15, axiom, !( (Ext_Mem_Acc_11_15) -o (Ext_Bus * Active_11 * Memory_15) ) ).
fof(Begin_Ext_Acc_5_3, axiom, !( (Ext_Bus * Memory_3 * Queue_5) -o (Ext_Mem_Acc_5_3) ) ).
fof(Begin_Ext_Acc_12_18, axiom, !( (Ext_Bus * Memory_18 * Queue_12) -o (Ext_Mem_Acc_12_18) ) ).
fof(End_Ext_Acc_9_13, axiom, !( (Ext_Mem_Acc_9_13) -o (Memory_13 * Active_9 * Ext_Bus) ) ).
fof(Req_Ext_Acc_20, axiom, !( (Active_20) -o (Queue_20) ) ).
fof(End_Ext_Acc_19_18, axiom, !( (Ext_Mem_Acc_19_18) -o (Memory_18 * Active_19 * Ext_Bus) ) ).
fof(End_Ext_Acc_14_8, axiom, !( (Ext_Mem_Acc_14_8) -o (Memory_8 * Active_14 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_16_5, axiom, !( (Queue_16 * Ext_Bus * Memory_5) -o (Ext_Mem_Acc_16_5) ) ).
fof(Begin_Ext_Acc_20_2, axiom, !( (Queue_20 * Memory_2 * Ext_Bus) -o (Ext_Mem_Acc_20_2) ) ).
fof(End_Ext_Acc_19_16, axiom, !( (Ext_Mem_Acc_19_16) -o (Ext_Bus * Active_19 * Memory_16) ) ).
fof(End_Ext_Acc_7_15, axiom, !( (Ext_Mem_Acc_7_15) -o (Memory_15 * Active_7 * Ext_Bus) ) ).
fof(End_Ext_Acc_3_7, axiom, !( (Ext_Mem_Acc_3_7) -o (Ext_Bus * Memory_7 * Active_3) ) ).
fof(End_Ext_Acc_16_11, axiom, !( (Ext_Mem_Acc_16_11) -o (Ext_Bus * Active_16 * Memory_11) ) ).
fof(Begin_Ext_Acc_12_3, axiom, !( (Queue_12 * Ext_Bus * Memory_3) -o (Ext_Mem_Acc_12_3) ) ).
fof(Begin_Ext_Acc_20_7, axiom, !( (Ext_Bus * Memory_7 * Queue_20) -o (Ext_Mem_Acc_20_7) ) ).
fof(End_Ext_Acc_18_11, axiom, !( (Ext_Mem_Acc_18_11) -o (Ext_Bus * Active_18 * Memory_11) ) ).
fof(End_Ext_Acc_7_9, axiom, !( (Ext_Mem_Acc_7_9) -o (Ext_Bus * Memory_9 * Active_7) ) ).
fof(Begin_Ext_Acc_9_14, axiom, !( (Memory_14 * Ext_Bus * Queue_9) -o (Ext_Mem_Acc_9_14) ) ).
fof(Req_Ext_Acc_12, axiom, !( (Active_12) -o (Queue_12) ) ).
fof(Begin_Ext_Acc_14_12, axiom, !( (Queue_14 * Memory_12 * Ext_Bus) -o (Ext_Mem_Acc_14_12) ) ).
fof(Begin_Ext_Acc_11_19, axiom, !( (Ext_Bus * Memory_19 * Queue_11) -o (Ext_Mem_Acc_11_19) ) ).
fof(Begin_Own_Acc_9, axiom, !( (Active_9) -o (OwnMemAcc_9) ) ).
fof(End_Ext_Acc_16_17, axiom, !( (Ext_Mem_Acc_16_17) -o (Ext_Bus * Active_16 * Memory_17) ) ).
fof(Begin_Ext_Acc_11_16, axiom, !( (Ext_Bus * Memory_16 * Queue_11) -o (Ext_Mem_Acc_11_16) ) ).
fof(End_Ext_Acc_13_5, axiom, !( (Ext_Mem_Acc_13_5) -o (Memory_5 * Active_13 * Ext_Bus) ) ).
fof(End_Ext_Acc_3_8, axiom, !( (Ext_Mem_Acc_3_8) -o (Ext_Bus * Memory_8 * Active_3) ) ).
fof(Begin_Ext_Acc_5_17, axiom, !( (Queue_5 * Memory_17 * Ext_Bus) -o (Ext_Mem_Acc_5_17) ) ).
fof(End_Ext_Acc_18_9, axiom, !( (Ext_Mem_Acc_18_9) -o (Active_18 * Memory_9 * Ext_Bus) ) ).
fof(End_Own_Acc_6_6, axiom, !( (Memory_6 * OwnMemAcc_6) -o (Memory_6 * Active_6) ) ).
fof(Begin_Ext_Acc_19_11, axiom, !( (Queue_19 * Memory_11 * Ext_Bus) -o (Ext_Mem_Acc_19_11) ) ).
fof(Begin_Ext_Acc_19_14, axiom, !( (Queue_19 * Memory_14 * Ext_Bus) -o (Ext_Mem_Acc_19_14) ) ).
fof(Begin_Ext_Acc_13_8, axiom, !( (Memory_8 * Ext_Bus * Queue_13) -o (Ext_Mem_Acc_13_8) ) ).
fof(Begin_Ext_Acc_20_12, axiom, !( (Memory_12 * Ext_Bus * Queue_20) -o (Ext_Mem_Acc_20_12) ) ).
fof(End_Ext_Acc_19_12, axiom, !( (Ext_Mem_Acc_19_12) -o (Active_19 * Memory_12 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_1_13, axiom, !( (Memory_13 * Ext_Bus * Queue_1) -o (Ext_Mem_Acc_1_13) ) ).
fof(Begin_Own_Acc_19, axiom, !( (Active_19) -o (OwnMemAcc_19) ) ).
fof(Begin_Ext_Acc_18_4, axiom, !( (Memory_4 * Ext_Bus * Queue_18) -o (Ext_Mem_Acc_18_4) ) ).
fof(Begin_Ext_Acc_20_8, axiom, !( (Ext_Bus * Memory_8 * Queue_20) -o (Ext_Mem_Acc_20_8) ) ).
fof(Begin_Ext_Acc_8_7, axiom, !( (Queue_8 * Memory_7 * Ext_Bus) -o (Ext_Mem_Acc_8_7) ) ).
fof(End_Ext_Acc_20_10, axiom, !( (Ext_Mem_Acc_20_10) -o (Ext_Bus * Active_20 * Memory_10) ) ).
fof(End_Ext_Acc_17_7, axiom, !( (Ext_Mem_Acc_17_7) -o (Memory_7 * Active_17 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_12_11, axiom, !( (Memory_11 * Ext_Bus * Queue_12) -o (Ext_Mem_Acc_12_11) ) ).
fof(Begin_Ext_Acc_16_20, axiom, !( (Queue_16 * Memory_20 * Ext_Bus) -o (Ext_Mem_Acc_16_20) ) ).
fof(Begin_Ext_Acc_11_7, axiom, !( (Queue_11 * Ext_Bus * Memory_7) -o (Ext_Mem_Acc_11_7) ) ).
fof(End_Ext_Acc_1_6, axiom, !( (Ext_Mem_Acc_1_6) -o (Active_1 * Memory_6 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_14_1, axiom, !( (Queue_14 * Ext_Bus * Memory_1) -o (Ext_Mem_Acc_14_1) ) ).
fof(End_Ext_Acc_18_7, axiom, !( (Ext_Mem_Acc_18_7) -o (Memory_7 * Active_18 * Ext_Bus) ) ).
fof(End_Ext_Acc_4_11, axiom, !( (Ext_Mem_Acc_4_11) -o (Ext_Bus * Memory_11 * Active_4) ) ).
fof(Begin_Ext_Acc_20_5, axiom, !( (Queue_20 * Memory_5 * Ext_Bus) -o (Ext_Mem_Acc_20_5) ) ).
fof(End_Ext_Acc_10_3, axiom, !( (Ext_Mem_Acc_10_3) -o (Ext_Bus * Memory_3 * Active_10) ) ).
fof(Begin_Ext_Acc_14_18, axiom, !( (Queue_14 * Memory_18 * Ext_Bus) -o (Ext_Mem_Acc_14_18) ) ).
fof(End_Ext_Acc_19_17, axiom, !( (Ext_Mem_Acc_19_17) -o (Ext_Bus * Active_19 * Memory_17) ) ).
fof(End_Ext_Acc_16_10, axiom, !( (Ext_Mem_Acc_16_10) -o (Active_16 * Memory_10 * Ext_Bus) ) ).
fof(End_Ext_Acc_16_19, axiom, !( (Ext_Mem_Acc_16_19) -o (Ext_Bus * Active_16 * Memory_19) ) ).
fof(Begin_Ext_Acc_10_1, axiom, !( (Queue_10 * Memory_1 * Ext_Bus) -o (Ext_Mem_Acc_10_1) ) ).
fof(End_Ext_Acc_7_17, axiom, !( (Ext_Mem_Acc_7_17) -o (Active_7 * Memory_17 * Ext_Bus) ) ).
fof(End_Ext_Acc_5_14, axiom, !( (Ext_Mem_Acc_5_14) -o (Active_5 * Memory_14 * Ext_Bus) ) ).
fof(End_Ext_Acc_13_12, axiom, !( (Ext_Mem_Acc_13_12) -o (Memory_12 * Active_13 * Ext_Bus) ) ).
fof(End_Ext_Acc_8_12, axiom, !( (Ext_Mem_Acc_8_12) -o (Memory_12 * Active_8 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_1_8, axiom, !( (Ext_Bus * Memory_8 * Queue_1) -o (Ext_Mem_Acc_1_8) ) ).
fof(End_Ext_Acc_8_9, axiom, !( (Ext_Mem_Acc_8_9) -o (Ext_Bus * Active_8 * Memory_9) ) ).
fof(Begin_Ext_Acc_16_11, axiom, !( (Ext_Bus * Memory_11 * Queue_16) -o (Ext_Mem_Acc_16_11) ) ).
fof(End_Ext_Acc_4_6, axiom, !( (Ext_Mem_Acc_4_6) -o (Active_4 * Memory_6 * Ext_Bus) ) ).
fof(End_Ext_Acc_15_14, axiom, !( (Ext_Mem_Acc_15_14) -o (Ext_Bus * Active_15 * Memory_14) ) ).
fof(End_Ext_Acc_12_2, axiom, !( (Ext_Mem_Acc_12_2) -o (Ext_Bus * Memory_2 * Active_12) ) ).
fof(Begin_Ext_Acc_2_10, axiom, !( (Memory_10 * Ext_Bus * Queue_2) -o (Ext_Mem_Acc_2_10) ) ).
fof(End_Own_Acc_12_12, axiom, !( (OwnMemAcc_12 * Memory_12) -o (Active_12 * Memory_12) ) ).
fof(End_Ext_Acc_15_6, axiom, !( (Ext_Mem_Acc_15_6) -o (Memory_6 * Active_15 * Ext_Bus) ) ).
fof(End_Ext_Acc_8_6, axiom, !( (Ext_Mem_Acc_8_6) -o (Ext_Bus * Memory_6 * Active_8) ) ).
fof(End_Ext_Acc_2_16, axiom, !( (Ext_Mem_Acc_2_16) -o (Ext_Bus * Active_2 * Memory_16) ) ).
fof(End_Ext_Acc_1_4, axiom, !( (Ext_Mem_Acc_1_4) -o (Active_1 * Memory_4 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_7_16, axiom, !( (Queue_7 * Memory_16 * Ext_Bus) -o (Ext_Mem_Acc_7_16) ) ).
fof(End_Ext_Acc_18_1, axiom, !( (Ext_Mem_Acc_18_1) -o (Memory_1 * Active_18 * Ext_Bus) ) ).
fof(End_Ext_Acc_20_14, axiom, !( (Ext_Mem_Acc_20_14) -o (Ext_Bus * Memory_14 * Active_20) ) ).
fof(Begin_Ext_Acc_18_15, axiom, !( (Ext_Bus * Memory_15 * Queue_18) -o (Ext_Mem_Acc_18_15) ) ).
fof(End_Ext_Acc_4_20, axiom, !( (Ext_Mem_Acc_4_20) -o (Active_4 * Memory_20 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_2_5, axiom, !( (Ext_Bus * Memory_5 * Queue_2) -o (Ext_Mem_Acc_2_5) ) ).
fof(Begin_Ext_Acc_15_12, axiom, !( (Queue_15 * Memory_12 * Ext_Bus) -o (Ext_Mem_Acc_15_12) ) ).
fof(End_Ext_Acc_20_13, axiom, !( (Ext_Mem_Acc_20_13) -o (Ext_Bus * Memory_13 * Active_20) ) ).
fof(Begin_Ext_Acc_6_10, axiom, !( (Queue_6 * Ext_Bus * Memory_10) -o (Ext_Mem_Acc_6_10) ) ).
fof(End_Ext_Acc_17_14, axiom, !( (Ext_Mem_Acc_17_14) -o (Ext_Bus * Active_17 * Memory_14) ) ).
fof(Begin_Ext_Acc_9_10, axiom, !( (Queue_9 * Memory_10 * Ext_Bus) -o (Ext_Mem_Acc_9_10) ) ).
fof(End_Ext_Acc_14_5, axiom, !( (Ext_Mem_Acc_14_5) -o (Memory_5 * Active_14 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_5_12, axiom, !( (Queue_5 * Ext_Bus * Memory_12) -o (Ext_Mem_Acc_5_12) ) ).
fof(Begin_Own_Acc_13, axiom, !( (Active_13) -o (OwnMemAcc_13) ) ).
fof(Begin_Ext_Acc_7_1, axiom, !( (Ext_Bus * Memory_1 * Queue_7) -o (Ext_Mem_Acc_7_1) ) ).
fof(Begin_Ext_Acc_4_14, axiom, !( (Queue_4 * Memory_14 * Ext_Bus) -o (Ext_Mem_Acc_4_14) ) ).
fof(Begin_Ext_Acc_12_4, axiom, !( (Queue_12 * Ext_Bus * Memory_4) -o (Ext_Mem_Acc_12_4) ) ).
fof(End_Ext_Acc_2_3, axiom, !( (Ext_Mem_Acc_2_3) -o (Active_2 * Memory_3 * Ext_Bus) ) ).
fof(End_Ext_Acc_17_12, axiom, !( (Ext_Mem_Acc_17_12) -o (Active_17 * Memory_12 * Ext_Bus) ) ).
fof(End_Ext_Acc_17_8, axiom, !( (Ext_Mem_Acc_17_8) -o (Ext_Bus * Active_17 * Memory_8) ) ).
fof(Req_Ext_Acc_5, axiom, !( (Active_5) -o (Queue_5) ) ).
fof(Req_Ext_Acc_13, axiom, !( (Active_13) -o (Queue_13) ) ).
fof(End_Ext_Acc_14_20, axiom, !( (Ext_Mem_Acc_14_20) -o (Ext_Bus * Active_14 * Memory_20) ) ).
fof(End_Ext_Acc_16_9, axiom, !( (Ext_Mem_Acc_16_9) -o (Memory_9 * Active_16 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_12_2, axiom, !( (Memory_2 * Ext_Bus * Queue_12) -o (Ext_Mem_Acc_12_2) ) ).
fof(Begin_Ext_Acc_14_20, axiom, !( (Memory_20 * Ext_Bus * Queue_14) -o (Ext_Mem_Acc_14_20) ) ).
fof(Begin_Ext_Acc_11_5, axiom, !( (Queue_11 * Ext_Bus * Memory_5) -o (Ext_Mem_Acc_11_5) ) ).
fof(Begin_Ext_Acc_10_12, axiom, !( (Queue_10 * Ext_Bus * Memory_12) -o (Ext_Mem_Acc_10_12) ) ).
fof(End_Ext_Acc_10_16, axiom, !( (Ext_Mem_Acc_10_16) -o (Active_10 * Memory_16 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_18_11, axiom, !( (Ext_Bus * Memory_11 * Queue_18) -o (Ext_Mem_Acc_18_11) ) ).
fof(Begin_Ext_Acc_13_11, axiom, !( (Memory_11 * Ext_Bus * Queue_13) -o (Ext_Mem_Acc_13_11) ) ).
fof(End_Ext_Acc_18_19, axiom, !( (Ext_Mem_Acc_18_19) -o (Ext_Bus * Memory_19 * Active_18) ) ).
fof(End_Ext_Acc_14_12, axiom, !( (Ext_Mem_Acc_14_12) -o (Memory_12 * Active_14 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_12_7, axiom, !( (Queue_12 * Ext_Bus * Memory_7) -o (Ext_Mem_Acc_12_7) ) ).
fof(End_Ext_Acc_13_9, axiom, !( (Ext_Mem_Acc_13_9) -o (Memory_9 * Active_13 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_16_3, axiom, !( (Queue_16 * Memory_3 * Ext_Bus) -o (Ext_Mem_Acc_16_3) ) ).
fof(Begin_Ext_Acc_19_20, axiom, !( (Queue_19 * Ext_Bus * Memory_20) -o (Ext_Mem_Acc_19_20) ) ).
fof(Begin_Ext_Acc_14_19, axiom, !( (Memory_19 * Ext_Bus * Queue_14) -o (Ext_Mem_Acc_14_19) ) ).
fof(Req_Ext_Acc_8, axiom, !( (Active_8) -o (Queue_8) ) ).
fof(Begin_Ext_Acc_18_16, axiom, !( (Memory_16 * Ext_Bus * Queue_18) -o (Ext_Mem_Acc_18_16) ) ).
fof(End_Ext_Acc_6_10, axiom, !( (Ext_Mem_Acc_6_10) -o (Ext_Bus * Active_6 * Memory_10) ) ).
fof(End_Ext_Acc_5_4, axiom, !( (Ext_Mem_Acc_5_4) -o (Ext_Bus * Active_5 * Memory_4) ) ).
fof(Begin_Ext_Acc_1_6, axiom, !( (Ext_Bus * Memory_6 * Queue_1) -o (Ext_Mem_Acc_1_6) ) ).
fof(End_Ext_Acc_17_5, axiom, !( (Ext_Mem_Acc_17_5) -o (Memory_5 * Active_17 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_7_12, axiom, !( (Queue_7 * Ext_Bus * Memory_12) -o (Ext_Mem_Acc_7_12) ) ).
fof(End_Ext_Acc_14_6, axiom, !( (Ext_Mem_Acc_14_6) -o (Memory_6 * Active_14 * Ext_Bus) ) ).
fof(Begin_Own_Acc_1, axiom, !( (Active_1) -o (OwnMemAcc_1) ) ).
fof(End_Ext_Acc_11_8, axiom, !( (Ext_Mem_Acc_11_8) -o (Active_11 * Memory_8 * Ext_Bus) ) ).
fof(End_Ext_Acc_5_15, axiom, !( (Ext_Mem_Acc_5_15) -o (Active_5 * Memory_15 * Ext_Bus) ) ).
fof(End_Ext_Acc_8_13, axiom, !( (Ext_Mem_Acc_8_13) -o (Memory_13 * Active_8 * Ext_Bus) ) ).
fof(End_Ext_Acc_9_8, axiom, !( (Ext_Mem_Acc_9_8) -o (Active_9 * Memory_8 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_5_8, axiom, !( (Queue_5 * Memory_8 * Ext_Bus) -o (Ext_Mem_Acc_5_8) ) ).
fof(End_Ext_Acc_12_8, axiom, !( (Ext_Mem_Acc_12_8) -o (Memory_8 * Active_12 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_7_18, axiom, !( (Memory_18 * Ext_Bus * Queue_7) -o (Ext_Mem_Acc_7_18) ) ).
fof(End_Ext_Acc_10_8, axiom, !( (Ext_Mem_Acc_10_8) -o (Active_10 * Memory_8 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_12_9, axiom, !( (Queue_12 * Ext_Bus * Memory_9) -o (Ext_Mem_Acc_12_9) ) ).
fof(Begin_Ext_Acc_17_15, axiom, !( (Ext_Bus * Memory_15 * Queue_17) -o (Ext_Mem_Acc_17_15) ) ).
fof(Begin_Ext_Acc_8_3, axiom, !( (Memory_3 * Ext_Bus * Queue_8) -o (Ext_Mem_Acc_8_3) ) ).
fof(End_Ext_Acc_4_8, axiom, !( (Ext_Mem_Acc_4_8) -o (Ext_Bus * Memory_8 * Active_4) ) ).
fof(End_Ext_Acc_4_10, axiom, !( (Ext_Mem_Acc_4_10) -o (Ext_Bus * Memory_10 * Active_4) ) ).
fof(Begin_Ext_Acc_6_11, axiom, !( (Queue_6 * Ext_Bus * Memory_11) -o (Ext_Mem_Acc_6_11) ) ).
fof(End_Ext_Acc_7_12, axiom, !( (Ext_Mem_Acc_7_12) -o (Memory_12 * Active_7 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_3_8, axiom, !( (Queue_3 * Memory_8 * Ext_Bus) -o (Ext_Mem_Acc_3_8) ) ).
fof(Begin_Ext_Acc_6_5, axiom, !( (Queue_6 * Memory_5 * Ext_Bus) -o (Ext_Mem_Acc_6_5) ) ).
fof(End_Ext_Acc_17_16, axiom, !( (Ext_Mem_Acc_17_16) -o (Ext_Bus * Active_17 * Memory_16) ) ).
fof(End_Ext_Acc_15_8, axiom, !( (Ext_Mem_Acc_15_8) -o (Memory_8 * Active_15 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_17_3, axiom, !( (Queue_17 * Memory_3 * Ext_Bus) -o (Ext_Mem_Acc_17_3) ) ).
fof(Begin_Ext_Acc_14_8, axiom, !( (Memory_8 * Ext_Bus * Queue_14) -o (Ext_Mem_Acc_14_8) ) ).
fof(End_Ext_Acc_11_4, axiom, !( (Ext_Mem_Acc_11_4) -o (Ext_Bus * Memory_4 * Active_11) ) ).
fof(Begin_Ext_Acc_13_9, axiom, !( (Queue_13 * Memory_9 * Ext_Bus) -o (Ext_Mem_Acc_13_9) ) ).
fof(Begin_Ext_Acc_19_18, axiom, !( (Queue_19 * Ext_Bus * Memory_18) -o (Ext_Mem_Acc_19_18) ) ).
fof(End_Ext_Acc_12_1, axiom, !( (Ext_Mem_Acc_12_1) -o (Ext_Bus * Memory_1 * Active_12) ) ).
fof(End_Ext_Acc_6_7, axiom, !( (Ext_Mem_Acc_6_7) -o (Ext_Bus * Active_6 * Memory_7) ) ).
fof(Begin_Ext_Acc_7_11, axiom, !( (Queue_7 * Ext_Bus * Memory_11) -o (Ext_Mem_Acc_7_11) ) ).
fof(End_Ext_Acc_13_7, axiom, !( (Ext_Mem_Acc_13_7) -o (Active_13 * Memory_7 * Ext_Bus) ) ).
fof(Begin_Ext_Acc_20_16, axiom, !( (Queue_20 * Ext_Bus * Memory_16) -o (Ext_Mem_Acc_20_16) ) ).
fof(Begin_Ext_Acc_3_14, axiom, !( (Queue_3 * Memory_14 * Ext_Bus) -o (Ext_Mem_Acc_3_14) ) ).
fof(con1, conjecture, Active_1 * Active_11 * Active_12 * Active_13 * Active_15 * Active_16 * Active_17 * Active_18 * Active_19 * Active_20 * Active_4 * Active_5 * Active_6 * Active_7 * Active_8 * Active_9 * Ext_Mem_Acc_2_17 * Memory_1 * Memory_10 * Memory_11 * Memory_12 * Memory_13 * Memory_14 * Memory_15 * Memory_16 * Memory_18 * Memory_19 * Memory_2 * Memory_20 * Memory_3 * Memory_4 * Memory_5 * Memory_6 * Memory_7 * Memory_8 * Memory_9 * OwnMemAcc_10 * OwnMemAcc_14 * OwnMemAcc_3).

%--------------------------------------------------------------------------
