
%--------------------------------------------------------------------------
% File     : 
% Domain   : Petri-nets
% Problem  : SwimmingPool 
% Version  : 1.0
% Refs     : The Model Checking Contest
% Source   : https://pnrepository.lip6.fr/mcc/models/all/browser.html
%
% Status (linear) : Theorem
% Rating (linear) : 0.00 v1.0.0
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
fof(inital_state, axiom, Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags).
fof(GetK, axiom, !( (Entered * Cabins) -o (WaitBag) ) ).
fof(GetB, axiom, !( (WaitBag * Bags) -o (Undress) ) ).
fof(RelK, axiom, !( (Undress) -o (Cabins * InBath) ) ).
fof(GetK2, axiom, !( (Cabins * InBath) -o (Dress) ) ).
fof(RBag, axiom, !( (Dress) -o (Bags * Dressed) ) ).
fof(RKey, axiom, !( (Dressed) -o (Out * Cabins) ) ).
fof(Enter, axiom, !( (Out) -o (Entered) ) ).
fof(con1, conjecture, Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Bags * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Cabins * Entered * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Out * Undress * Undress * Undress * Undress * Undress * Undress * Undress * Undress * Undress * Undress * Undress * Undress * Undress * Undress * Undress * Undress * Undress * Undress * Undress * Undress * Undress * Undress * Undress * Undress * Undress * Undress * Undress * Undress * Undress * Undress * Undress * Undress * Undress).
